/-
This file is generated by `scripts/generate_toda_table.py` from
`research/report-data/mimura_toda_unstable_stem_20.csv`.
Do not edit it by hand.
-/

import HomotopyGroups.TodaTable

open scoped Topology

namespace HomotopyGroups

/-- The complete Mimura--Toda 20-stem code; `nIndex = 0` denotes `S^2`. -/
def mimuraTodaStemTwentyGroupCode (nIndex : Fin 21) : TodaIntegralGroupCode :=
  match nIndex.val with
  | 0 => .product (.finiteCyclic 132) ((.finiteCyclic 2))
  | 1 => .product (.finiteCyclic 2) ((.finiteCyclic 2))
  | 2 => .product (.finiteCyclic 2) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) ((.finiteCyclic 2))))))
  | 3 => .product (.finiteCyclic 6) (.product (.finiteCyclic 2) ((.finiteCyclic 2)))
  | 4 => .product (.finiteCyclic 480) ((.finiteCyclic 12))
  | 5 => (.finiteCyclic 24)
  | 6 => .product (.finiteCyclic 24) ((.finiteCyclic 3))
  | 7 => (.finiteCyclic 24)
  | 8 => .product (.finiteCyclic 504) ((.finiteCyclic 24))
  | 9 => .product (.finiteCyclic 24) (.product (.finiteCyclic 2) ((.finiteCyclic 2)))
  | 10 => .product (.finiteCyclic 24) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) ((.finiteCyclic 2))))))
  | 11 => .product (.finiteCyclic 24) (.product (.finiteCyclic 2) (.product (.finiteCyclic 2) ((.finiteCyclic 2))))
  | 12 => .product (.finiteCyclic 240) ((.finiteCyclic 24))
  | 13 => (.finiteCyclic 24)
  | 14 => (.finiteCyclic 24)
  | 15 => (.finiteCyclic 24)
  | 16 => .product (.finiteCyclic 24) ((.finiteCyclic 12))
  | 17 => .product (.finiteCyclic 24) ((.finiteCyclic 2))
  | 18 => .product (.finiteCyclic 24) (.product (.finiteCyclic 2) ((.finiteCyclic 2)))
  | 19 => .product (.finiteCyclic 24) ((.finiteCyclic 2))
  | 20 => (.finiteCyclic 24)
  | _ => .finiteCyclic 1

/-- The actual group represented by `mimuraTodaStemTwentyGroupCode`. -/
noncomputable def mimuraTodaStemTwentyGroup (nIndex : Fin 21) : GrpCat :=
  (mimuraTodaStemTwentyGroupCode nIndex).asGrp

/--
Mimura and Toda's complete integral 20-stem for sphere dimensions 2 through 22.
The finite index encodes `n = nIndex + 2`; the target is `pi_(n+20)(S^n)`.
-/
@[eval_problem]
theorem mimura_toda_unstable_integral_stem_twenty (nIndex : Fin 21) :
    Nonempty
      (HomotopyGroup.Pi (nIndex.val + 22)
          (SphereSpace (nIndex.val + 2)) (sphereBasepoint (nIndex.val + 2)) ≃*
        mimuraTodaStemTwentyGroup nIndex) := by
  sorry

end HomotopyGroups
