/-
This file is generated by `scripts/generate_three_primary_table.py` from the
audited handoff table `stable_3_primary_groups_0_108.csv`.
Do not edit it by hand.
-/

import EvalTools.Markers
import HomotopyGroups.StableStems
import Mathlib.Algebra.Category.Grp.Basic
import Mathlib.GroupTheory.Torsion

open scoped Topology

namespace HomotopyGroups

/-- The eight finite abelian 3-groups occurring in positive stems through 108. -/
inductive StableThreePrimaryGroupCode where
  | trivial
  | c3
  | c3Squared
  | c3Cubed
  | c9
  | c3TimesC9
  | c27
  | c3SquaredTimesC81

namespace StableThreePrimaryGroupCode

/-- Interpret a table code as an actual bundled multiplicative group. -/
noncomputable def asGrp : StableThreePrimaryGroupCode → GrpCat
  | .trivial => GrpCat.of (Multiplicative (ZMod 1))
  | .c3 => GrpCat.of (Multiplicative (ZMod 3))
  | .c3Squared => GrpCat.of (Multiplicative (ZMod 3 × ZMod 3))
  | .c3Cubed => GrpCat.of (Multiplicative (ZMod 3 × (ZMod 3 × ZMod 3)))
  | .c9 => GrpCat.of (Multiplicative (ZMod 9))
  | .c3TimesC9 => GrpCat.of (Multiplicative (ZMod 3 × ZMod 9))
  | .c27 => GrpCat.of (Multiplicative (ZMod 27))
  | .c3SquaredTimesC81 => GrpCat.of (Multiplicative (ZMod 3 × (ZMod 3 × ZMod 81)))

end StableThreePrimaryGroupCode

/-- Table A3.2 plus image J, in positive stems; index zero represents stable stem one. -/
def stableThreePrimaryGroupCode (stemIndex : Fin 108) : StableThreePrimaryGroupCode :=
  match stemIndex.val with
  | 0 => .trivial
  | 1 => .trivial
  | 2 => .c3
  | 3 => .trivial
  | 4 => .trivial
  | 5 => .trivial
  | 6 => .c3
  | 7 => .trivial
  | 8 => .trivial
  | 9 => .c3
  | 10 => .c9
  | 11 => .trivial
  | 12 => .c3
  | 13 => .trivial
  | 14 => .c3
  | 15 => .trivial
  | 16 => .trivial
  | 17 => .trivial
  | 18 => .c3
  | 19 => .c3
  | 20 => .trivial
  | 21 => .trivial
  | 22 => .c3TimesC9
  | 23 => .trivial
  | 24 => .trivial
  | 25 => .c3
  | 26 => .c3
  | 27 => .trivial
  | 28 => .c3
  | 29 => .c3
  | 30 => .c3
  | 31 => .trivial
  | 32 => .trivial
  | 33 => .trivial
  | 34 => .c27
  | 35 => .c3
  | 36 => .c3
  | 37 => .c3
  | 38 => .c3Squared
  | 39 => .c3
  | 40 => .trivial
  | 41 => .c3
  | 42 => .c3
  | 43 => .trivial
  | 44 => .c9
  | 45 => .c3
  | 46 => .c3TimesC9
  | 47 => .trivial
  | 48 => .c3
  | 49 => .c3
  | 50 => .c3
  | 51 => .c3
  | 52 => .trivial
  | 53 => .trivial
  | 54 => .c3Squared
  | 55 => .trivial
  | 56 => .trivial
  | 57 => .trivial
  | 58 => .c9
  | 59 => .trivial
  | 60 => .trivial
  | 61 => .c3
  | 62 => .c3
  | 63 => .trivial
  | 64 => .c3
  | 65 => .trivial
  | 66 => .c3
  | 67 => .c3
  | 68 => .trivial
  | 69 => .trivial
  | 70 => .c27
  | 71 => .c3
  | 72 => .trivial
  | 73 => .c3
  | 74 => .c3TimesC9
  | 75 => .trivial
  | 76 => .trivial
  | 77 => .c3
  | 78 => .c3
  | 79 => .trivial
  | 80 => .c3Squared
  | 81 => .c3
  | 82 => .c9
  | 83 => .c3Squared
  | 84 => .c3Squared
  | 85 => .c3
  | 86 => .c3
  | 87 => .trivial
  | 88 => .trivial
  | 89 => .c3
  | 90 => .c3Cubed
  | 91 => .c3Squared
  | 92 => .c9
  | 93 => .c3Squared
  | 94 => .c3TimesC9
  | 95 => .trivial
  | 96 => .trivial
  | 97 => .trivial
  | 98 => .c3Squared
  | 99 => .c3
  | 100 => .c3Squared
  | 101 => .c3Squared
  | 102 => .c3
  | 103 => .c3
  | 104 => .trivial
  | 105 => .c3
  | 106 => .c3SquaredTimesC81
  | 107 => .c3
  | _ => .trivial

/-- The finite abelian group represented by `stableThreePrimaryGroupCode`. -/
noncomputable def stableThreePrimaryGroup (stemIndex : Fin 108) : GrpCat :=
  (stableThreePrimaryGroupCode stemIndex).asGrp

/--
The exact 3-primary components of the positive stable stems 1 through 108.
The finite index `stemIndex` represents stable stem `stemIndex + 1`; the
chosen homotopy group is the same canonical Freudenthal-range representative
used by `HomotopyGroups.StableStems`.

Stem zero is deliberately excluded: its `Z_(3)` entry is a localization of the
infinite cyclic group, not the primary torsion subgroup defined by Mathlib.

Source: Ravenel, *Complex Cobordism and Stable Homotopy Groups of Spheres*,
digital third edition (2026), Table A3.2 plus the image-of-J formula: https://www.sas.rochester.edu/mth/sites/doug-ravenel/mybooks/ravenel3rd.pdf
-/
@[eval_problem]
theorem stable_three_primary_groups_001_108 (stemIndex : Fin 108) :
    Nonempty
      (CommGroup.primaryComponent
          (π_ (2 * (stemIndex.val + 1) + 2)
            (StableStems.StableSphere (stemIndex.val + 3))
            (StableStems.stableSphereBasepoint (stemIndex.val + 3))) 3 ≃*
        stableThreePrimaryGroup stemIndex) := by
  sorry

end HomotopyGroups
