/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.ComplexProjectivePlaneTrisectionMeridianQuotients

/-!
# Splittings of the trisection fundamental-group sequences

A surjection with cyclic kernel generated by a class of unit integral coordinate is jointly
classified by that coordinate and the surjection.  Applying this observation to the three
central-to-pairwise maps gives explicit product decompositions

`pi_1(T^2) = Z x pi_1(S^1)`.

In each decomposition the named meridian is the positive generator of the integer factor and
the original induced map is the second projection.  Taking the inverse image of the second
factor therefore supplies a homomorphic right inverse, so all three short exact sequences split.
-/

noncomputable section

open CategoryTheory Simplicial
open scoped Topology Topology.Homotopy

namespace Submission

/-- A surjection and an integer coordinate jointly classify the source when its kernel is
generated by a class of coordinate one. -/
theorem monoidHom_prod_bijective_of_surjective_of_ker_eq_zpowers_of_apply_eq_one
    {G H : Type*} [Group G] [Group H]
    (f : G →* H) (hf : Function.Surjective f)
    (coordinate : G →* Multiplicative ℤ) (g : G)
    (hker : f.ker = Subgroup.zpowers g)
    (hcoordinate : coordinate g = Multiplicative.ofAdd (1 : ℤ)) :
    Function.Bijective (coordinate.prod f) := by
  have hfg : f g = 1 := by
    rw [← MonoidHom.mem_ker, hker]
    exact Subgroup.mem_zpowers g
  constructor
  · intro x y hxy
    have hcoordinateXY : coordinate x = coordinate y :=
      congrArg Prod.fst hxy
    have hfXY : f x = f y := congrArg Prod.snd hxy
    have hxyMem : x * y⁻¹ ∈ f.ker := by
      rw [MonoidHom.mem_ker, map_mul, map_inv, hfXY, mul_inv_cancel]
    rw [hker] at hxyMem
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hxyMem
    have hcoordinateOne : coordinate (x * y⁻¹) = 1 := by
      rw [map_mul, map_inv, hcoordinateXY, mul_inv_cancel]
    rw [← hn, map_zpow, hcoordinate] at hcoordinateOne
    have hnZero : n = 0 := by
      have h := congrArg Multiplicative.toAdd hcoordinateOne
      simpa using h
    apply mul_inv_eq_one.mp
    rw [← hn, hnZero, zpow_zero]
  · rintro ⟨z, h⟩
    obtain ⟨y, hy⟩ := hf h
    let n : ℤ := z.toAdd - (coordinate y).toAdd
    refine ⟨g ^ n * y, ?_⟩
    apply Prod.ext
    · change coordinate (g ^ n * y) = z
      rw [map_mul, map_zpow, hcoordinate]
      apply Multiplicative.toAdd.injective
      simp [n]
    · change f (g ^ n * y) = h
      rw [map_mul, map_zpow, hfg, one_zpow, one_mul, hy]

/-- The multiplicative equivalence jointly induced by an integral coordinate and a surjection
whose kernel is generated by a class of coordinate one. -/
noncomputable def monoidHomProdMulEquivOfSurjectiveOfKerEqZPowersOfApplyEqOne
    {G H : Type*} [Group G] [Group H]
    (f : G →* H) (hf : Function.Surjective f)
    (coordinate : G →* Multiplicative ℤ) (g : G)
    (hker : f.ker = Subgroup.zpowers g)
    (hcoordinate : coordinate g = Multiplicative.ofAdd (1 : ℤ)) :
    G ≃* Multiplicative ℤ × H :=
  MulEquiv.ofBijective (coordinate.prod f)
    (monoidHom_prod_bijective_of_surjective_of_ker_eq_zpowers_of_apply_eq_one
      f hf coordinate g hker hcoordinate)

end Submission

namespace Submission.ComplexProjectivePlaneTriangulation

open FiniteOrderedComplex

/-- The zero-five central fundamental group decomposes into its meridian coordinate and the
pairwise fundamental group. -/
noncomputable def zeroFiveCentralInterfacePiOneMeridianProdEquiv :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        zeroFiveCentralRealizationBase ≃*
      Multiplicative ℤ ×
        HomotopyGroup.Pi 1
          (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 0 5)))
          ((SSet.toTop.map
            (zeroFiveMeridianBoundaryInclCentral ≫
              zeroFiveCentralInterfaceInclPairwise)).hom
            zeroFiveBoundaryRealizationBase) :=
  monoidHomProdMulEquivOfSurjectiveOfKerEqZPowersOfApplyEqOne
    (HomotopyGroup.mapHom (N := Fin 1)
      (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
      zeroFiveCentralRealizationBase_map_pairwise_eq)
    zeroFiveCentralInterfaceInclPairwise_piOne_map_surjective
    zeroFiveCentralRealizationPiOneFirstCoordinate
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers
    zeroFiveCentralRealizationPiOneFirstCoordinate_class

/-- The zero-five product decomposition sends its meridian to the positive integer generator. -/
theorem zeroFiveCentralInterfacePiOneMeridianProdEquiv_meridian :
    zeroFiveCentralInterfacePiOneMeridianProdEquiv
        zeroFiveCentralRealizationPiOneClass =
      (Multiplicative.ofAdd (1 : ℤ), 1) := by
  apply Prod.ext
  · exact zeroFiveCentralRealizationPiOneFirstCoordinate_class
  · exact zeroFiveCentralInterfaceInclPairwise_piOne_map_class_eq_one

/-- A homomorphic section of the zero-five central-to-pairwise fundamental-group map. -/
noncomputable def zeroFiveCentralInterfaceInclPairwisePiOneSection :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 0 5)))
        ((SSet.toTop.map
          (zeroFiveMeridianBoundaryInclCentral ≫
            zeroFiveCentralInterfaceInclPairwise)).hom
          zeroFiveBoundaryRealizationBase) →*
      HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        zeroFiveCentralRealizationBase :=
  zeroFiveCentralInterfacePiOneMeridianProdEquiv.symm.toMonoidHom.comp
    (MonoidHom.inr (Multiplicative ℤ) _)

/-- The zero-five section is a right inverse of the induced fundamental-group map. -/
theorem zeroFiveCentralInterfaceInclPairwisePiOneSection_rightInverse :
    (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
        zeroFiveCentralRealizationBase_map_pairwise_eq).comp
      zeroFiveCentralInterfaceInclPairwisePiOneSection =
    MonoidHom.id _ := by
  ext h
  have hpair :=
    zeroFiveCentralInterfacePiOneMeridianProdEquiv.apply_symm_apply (1, h)
  exact congrArg Prod.snd hpair

/-- The five-four central fundamental group decomposes into its meridian coordinate and the
pairwise fundamental group. -/
noncomputable def fiveFourCentralInterfacePiOneMeridianProdEquiv :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fiveFourCentralRealizationBase ≃*
      Multiplicative ℤ ×
        HomotopyGroup.Pi 1
          (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 5 4)))
          ((SSet.toTop.map
            (fiveFourMeridianBoundaryInclCentral ≫
              fiveFourCentralInterfaceInclPairwise)).hom
            fiveFourBoundaryRealizationBase) :=
  monoidHomProdMulEquivOfSurjectiveOfKerEqZPowersOfApplyEqOne
    (HomotopyGroup.mapHom (N := Fin 1)
      (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
      fiveFourCentralRealizationBase_map_pairwise_eq)
    fiveFourCentralInterfaceInclPairwise_piOne_map_surjective
    fiveFourCentralRealizationPiOneSecondCoordinate
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers
    fiveFourCentralRealizationPiOneSecondCoordinate_class

/-- The five-four product decomposition sends its meridian to the positive integer generator. -/
theorem fiveFourCentralInterfacePiOneMeridianProdEquiv_meridian :
    fiveFourCentralInterfacePiOneMeridianProdEquiv
        fiveFourCentralRealizationPiOneClass =
      (Multiplicative.ofAdd (1 : ℤ), 1) := by
  apply Prod.ext
  · exact fiveFourCentralRealizationPiOneSecondCoordinate_class
  · exact fiveFourCentralInterfaceInclPairwise_piOne_map_class_eq_one

/-- A homomorphic section of the five-four central-to-pairwise fundamental-group map. -/
noncomputable def fiveFourCentralInterfaceInclPairwisePiOneSection :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 5 4)))
        ((SSet.toTop.map
          (fiveFourMeridianBoundaryInclCentral ≫
            fiveFourCentralInterfaceInclPairwise)).hom
          fiveFourBoundaryRealizationBase) →*
      HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fiveFourCentralRealizationBase :=
  fiveFourCentralInterfacePiOneMeridianProdEquiv.symm.toMonoidHom.comp
    (MonoidHom.inr (Multiplicative ℤ) _)

/-- The five-four section is a right inverse of the induced fundamental-group map. -/
theorem fiveFourCentralInterfaceInclPairwisePiOneSection_rightInverse :
    (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
        fiveFourCentralRealizationBase_map_pairwise_eq).comp
      fiveFourCentralInterfaceInclPairwisePiOneSection =
    MonoidHom.id _ := by
  ext h
  have hpair :=
    fiveFourCentralInterfacePiOneMeridianProdEquiv.apply_symm_apply (1, h)
  exact congrArg Prod.snd hpair

/-- The sign-normalized integer coordinate on the four-zero meridian. -/
noncomputable def fourZeroCentralRealizationPiOneMeridianCoordinate :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fourZeroCentralRealizationBase →*
      Multiplicative ℤ :=
  (AddEquiv.neg ℤ).toMultiplicative.toMonoidHom.comp
    fourZeroCentralRealizationPiOneFirstCoordinate

/-- The normalized four-zero meridian coordinate is positive one. -/
theorem fourZeroCentralRealizationPiOneMeridianCoordinate_class :
    fourZeroCentralRealizationPiOneMeridianCoordinate
        fourZeroCentralRealizationPiOneClass =
      Multiplicative.ofAdd (1 : ℤ) := by
  rw [fourZeroCentralRealizationPiOneMeridianCoordinate,
    MonoidHom.comp_apply,
    fourZeroCentralRealizationPiOneFirstCoordinate_class]
  rfl

/-- The four-zero central fundamental group decomposes into its normalized meridian coordinate
and the pairwise fundamental group. -/
noncomputable def fourZeroCentralInterfacePiOneMeridianProdEquiv :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fourZeroCentralRealizationBase ≃*
      Multiplicative ℤ ×
        HomotopyGroup.Pi 1
          (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 4 0)))
          ((SSet.toTop.map
            (fourZeroMeridianBoundaryInclCentral ≫
              fourZeroCentralInterfaceInclPairwise)).hom
            fourZeroBoundaryRealizationBase) :=
  monoidHomProdMulEquivOfSurjectiveOfKerEqZPowersOfApplyEqOne
    (HomotopyGroup.mapHom (N := Fin 1)
      (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
      fourZeroCentralRealizationBase_map_pairwise_eq)
    fourZeroCentralInterfaceInclPairwise_piOne_map_surjective
    fourZeroCentralRealizationPiOneMeridianCoordinate
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers
    fourZeroCentralRealizationPiOneMeridianCoordinate_class

/-- The four-zero product decomposition sends its meridian to the positive integer generator. -/
theorem fourZeroCentralInterfacePiOneMeridianProdEquiv_meridian :
    fourZeroCentralInterfacePiOneMeridianProdEquiv
        fourZeroCentralRealizationPiOneClass =
      (Multiplicative.ofAdd (1 : ℤ), 1) := by
  apply Prod.ext
  · exact fourZeroCentralRealizationPiOneMeridianCoordinate_class
  · exact fourZeroCentralInterfaceInclPairwise_piOne_map_class_eq_one

/-- A homomorphic section of the four-zero central-to-pairwise fundamental-group map. -/
noncomputable def fourZeroCentralInterfaceInclPairwisePiOneSection :
    HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 4 0)))
        ((SSet.toTop.map
          (fourZeroMeridianBoundaryInclCentral ≫
            fourZeroCentralInterfaceInclPairwise)).hom
          fourZeroBoundaryRealizationBase) →*
      HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fourZeroCentralRealizationBase :=
  fourZeroCentralInterfacePiOneMeridianProdEquiv.symm.toMonoidHom.comp
    (MonoidHom.inr (Multiplicative ℤ) _)

/-- The four-zero section is a right inverse of the induced fundamental-group map. -/
theorem fourZeroCentralInterfaceInclPairwisePiOneSection_rightInverse :
    (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
        fourZeroCentralRealizationBase_map_pairwise_eq).comp
      fourZeroCentralInterfaceInclPairwisePiOneSection =
    MonoidHom.id _ := by
  ext h
  have hpair :=
    fourZeroCentralInterfacePiOneMeridianProdEquiv.apply_symm_apply (1, h)
  exact congrArg Prod.snd hpair

end Submission.ComplexProjectivePlaneTriangulation
