/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Submission.ComplexProjectivePlaneTrisectionRelativeHomotopy
import Submission.Homotopy.HomotopyLesTools
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# The relative second homotopy groups of the trisection interfaces

The group-valued long exact sequence sharpens the preceding pointed-set computation.  The
mapping-cylinder ambient spaces have trivial second homotopy groups, so each relative boundary
map is injective.  Its previously computed image is the cyclic subgroup generated by the
transported meridian.  Consequently the relative second homotopy group of every interface pair is
not merely infinite: it is multiplicatively equivalent to the integers, with its integral
coordinate characterized by the exact meridian-power boundary formula.
-/

open CategoryTheory Simplicial
open scoped Topology Topology.Homotopy

noncomputable section

namespace Submission

/-! ## Generic range classification -/

/-- The boundary map is injective when the preceding absolute homotopy group is trivial. -/
theorem RelHomotopyGroup.bdHom_injective_of_subsingleton
    (n : ℕ) (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (hX : Subsingleton (HomotopyGroup.Pi (n + 2) X (a : X))) :
    Function.Injective (RelHomotopyGroup.bdHom n X A a) := by
  refine (injective_iff_map_eq_one
    (RelHomotopyGroup.bdHom n X A a)).mpr fun z hz => ?_
  obtain ⟨w, rfl⟩ :=
    (RelHomotopyGroup.mulExact_jStarHom_bdHom n X A a z).mp hz
  rw [hX.elim w 1, map_one]

/-- An injective group homomorphism is equivalent to its range. -/
noncomputable def MonoidHom.mulEquivRangeOfInjective
    {G H : Type*} [Group G] [Group H] (f : G →* H)
    (hf : Function.Injective f) : G ≃* f.range :=
  MulEquiv.ofBijective f.rangeRestrict
    ⟨(MonoidHom.rangeRestrict_injective_iff.mpr hf),
      f.rangeRestrict_surjective⟩

/-- An injective relative boundary map with cyclic image identifies the relative group with that
cyclic subgroup. -/
noncomputable def RelHomotopyGroup.bdMulEquivZpowers
    (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (g : HomotopyGroup.Pi 1 A a)
    (hinjective : Function.Injective
      (RelHomotopyGroup.bdHom 0 X A a))
    (hrange : Set.range (RelHomotopyGroup.bd 1 X A a) =
      (Subgroup.zpowers g : Set (HomotopyGroup.Pi 1 A a))) :
    RelHomotopyGroup 2 X A a ≃* Subgroup.zpowers g := by
  have hrange' : (RelHomotopyGroup.bdHom 0 X A a).range =
      Subgroup.zpowers g := by
    ext y
    change y ∈ Set.range (RelHomotopyGroup.bd 1 X A a) ↔
      y ∈ (Subgroup.zpowers g : Set (HomotopyGroup.Pi 1 A a))
    exact Set.ext_iff.mp hrange y
  exact (MonoidHom.mulEquivRangeOfInjective
    (RelHomotopyGroup.bdHom 0 X A a) hinjective).trans
      (MulEquiv.subgroupCongr hrange')

/-- The distinguished generator generates its entire cyclic subgroup, now regarded as a group in
its own right. -/
theorem Subgroup.zpowers_subtype_generator_eq_top
    {G : Type*} [Group G] (g : G) :
    Subgroup.zpowers
        (⟨g, Subgroup.mem_zpowers g⟩ : Subgroup.zpowers g) = ⊤ := by
  rw [eq_top_iff]
  intro x _hx
  obtain ⟨z, hz⟩ := Subgroup.mem_zpowers_iff.mp x.property
  apply Subgroup.mem_zpowers_iff.mpr
  refine ⟨z, ?_⟩
  apply Subtype.ext
  exact hz

/-- An infinite relative second homotopy group whose injective boundary has cyclic image is
infinite cyclic. -/
noncomputable def RelHomotopyGroup.mulEquivIntOfBdRangeZpowers
    (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (g : HomotopyGroup.Pi 1 A a)
    (hinjective : Function.Injective
      (RelHomotopyGroup.bdHom 0 X A a))
    (hrange : Set.range (RelHomotopyGroup.bd 1 X A a) =
      (Subgroup.zpowers g : Set (HomotopyGroup.Pi 1 A a)))
    (hinfinite : Infinite (RelHomotopyGroup 2 X A a)) :
    RelHomotopyGroup 2 X A a ≃* Multiplicative ℤ := by
  let e := RelHomotopyGroup.bdMulEquivZpowers X A a g hinjective hrange
  letI : Infinite (RelHomotopyGroup 2 X A a) := hinfinite
  letI : Infinite (Subgroup.zpowers g) :=
    Infinite.of_injective e e.injective
  exact e.trans
    (intEquivOfZPowersEqTop
      (⟨g, Subgroup.mem_zpowers g⟩ : Subgroup.zpowers g)
      (Subgroup.zpowers_subtype_generator_eq_top g)).symm

/-- The cyclic-range equivalence is literally the relative boundary map after coercion. -/
theorem RelHomotopyGroup.coe_bdMulEquivZpowers_apply
    (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (g : HomotopyGroup.Pi 1 A a)
    (hinjective : Function.Injective
      (RelHomotopyGroup.bdHom 0 X A a))
    (hrange : Set.range (RelHomotopyGroup.bd 1 X A a) =
      (Subgroup.zpowers g : Set (HomotopyGroup.Pi 1 A a)))
    (r : RelHomotopyGroup 2 X A a) :
    ((RelHomotopyGroup.bdMulEquivZpowers
      X A a g hinjective hrange r : Subgroup.zpowers g) :
        HomotopyGroup.Pi 1 A a) =
      RelHomotopyGroup.bd 1 X A a r := by
  rfl

/-- The integer coordinate supplied by the cyclic classification is characterized by the exact
power of the meridian occurring as the relative boundary. -/
theorem RelHomotopyGroup.bd_eq_zpow_mulEquivIntOfBdRangeZpowers
    (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (g : HomotopyGroup.Pi 1 A a)
    (hinjective : Function.Injective
      (RelHomotopyGroup.bdHom 0 X A a))
    (hrange : Set.range (RelHomotopyGroup.bd 1 X A a) =
      (Subgroup.zpowers g : Set (HomotopyGroup.Pi 1 A a)))
    (hinfinite : Infinite (RelHomotopyGroup 2 X A a))
    (r : RelHomotopyGroup 2 X A a) :
    RelHomotopyGroup.bd 1 X A a r =
      g ^ (RelHomotopyGroup.mulEquivIntOfBdRangeZpowers
        X A a g hinjective hrange hinfinite r).toAdd := by
  let e := RelHomotopyGroup.bdMulEquivZpowers X A a g hinjective hrange
  letI : Infinite (RelHomotopyGroup 2 X A a) := hinfinite
  letI : Infinite (Subgroup.zpowers g) :=
    Infinite.of_injective e e.injective
  let gen : Subgroup.zpowers g := ⟨g, Subgroup.mem_zpowers g⟩
  let hgen : Subgroup.zpowers gen = ⊤ :=
    Subgroup.zpowers_subtype_generator_eq_top g
  have h := congrArg Subtype.val
    ((intEquivOfZPowersEqTop gen hgen).apply_symm_apply (e r))
  exact h.symm

/-- A relative class whose boundary is the `z`-th meridian power has integer coordinate `z`. -/
theorem RelHomotopyGroup.mulEquivIntOfBdRangeZpowers_apply_of_bd_eq_zpow
    (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (g : HomotopyGroup.Pi 1 A a)
    (hinjective : Function.Injective
      (RelHomotopyGroup.bdHom 0 X A a))
    (hrange : Set.range (RelHomotopyGroup.bd 1 X A a) =
      (Subgroup.zpowers g : Set (HomotopyGroup.Pi 1 A a)))
    (hinfinite : Infinite (RelHomotopyGroup 2 X A a))
    (r : RelHomotopyGroup 2 X A a) (z : ℤ)
    (hboundary : RelHomotopyGroup.bd 1 X A a r = g ^ z) :
    RelHomotopyGroup.mulEquivIntOfBdRangeZpowers
        X A a g hinjective hrange hinfinite r =
      Multiplicative.ofAdd z := by
  let e := RelHomotopyGroup.bdMulEquivZpowers X A a g hinjective hrange
  letI : Infinite (RelHomotopyGroup 2 X A a) := hinfinite
  letI : Infinite (Subgroup.zpowers g) :=
    Infinite.of_injective e e.injective
  let gen : Subgroup.zpowers g := ⟨g, Subgroup.mem_zpowers g⟩
  let hgen : Subgroup.zpowers gen = ⊤ :=
    Subgroup.zpowers_subtype_generator_eq_top g
  have he : e r = gen ^ z := by
    apply Subtype.ext
    exact hboundary
  change (intEquivOfZPowersEqTop gen hgen).symm (e r) =
    Multiplicative.ofAdd z
  rw [he, mulintEquivOfZPowersEqTop_symm_apply_zpow hgen]

end Submission

namespace Submission.ComplexProjectivePlaneTriangulation

open FiniteOrderedComplex

/-! ## The zero-five interface -/

theorem zeroFiveMapCyl_piTwo_subsingleton :
    Subsingleton
      (HomotopyGroup.Pi 2
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase :
            TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)) := by
  apply subsingleton_homotopyGroup_of_homotopyEquiv
    (TopCat.MapCyl.homotopyEquivBase
      zeroFiveCentralInterfaceInclPairwiseTopCat)
  intro y
  exact pairwiseInterface_higher_homotopy_subsingleton
    0 (by decide) 5 (by decide) (by decide) 0 y

theorem zeroFiveRelativePiTwo_boundary_injective :
    Function.Injective
      (RelHomotopyGroup.bdHom 0
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase)) := by
  exact RelHomotopyGroup.bdHom_injective_of_subsingleton
    0 (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
      zeroFiveCentralRealizationBase)
    zeroFiveMapCyl_piTwo_subsingleton

noncomputable def zeroFiveRelativePiTwoMulEquivZpowers :
    RelHomotopyGroup 2
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase) ≃*
      Subgroup.zpowers zeroFiveMapCylTopMeridianClass :=
  RelHomotopyGroup.bdMulEquivZpowers
    (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
      zeroFiveCentralRealizationBase)
    zeroFiveMapCylTopMeridianClass
    zeroFiveRelativePiTwo_boundary_injective
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_boundary_range

noncomputable def zeroFiveRelativePiTwoMulEquivInt :
    RelHomotopyGroup 2
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase) ≃*
      Multiplicative ℤ :=
  RelHomotopyGroup.mulEquivIntOfBdRangeZpowers
    (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
      zeroFiveCentralRealizationBase)
    zeroFiveMapCylTopMeridianClass
    zeroFiveRelativePiTwo_boundary_injective
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_infinite

theorem zeroFiveRelativePiTwoMulEquivInt_boundary
    (r : RelHomotopyGroup 2
      (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop
        zeroFiveCentralInterfaceInclPairwiseTopCat
        zeroFiveCentralRealizationBase)) :
    RelHomotopyGroup.bd 1
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase) r =
      zeroFiveMapCylTopMeridianClass ^
        (zeroFiveRelativePiTwoMulEquivInt r).toAdd := by
  exact RelHomotopyGroup.bd_eq_zpow_mulEquivIntOfBdRangeZpowers
    (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
      zeroFiveCentralRealizationBase)
    zeroFiveMapCylTopMeridianClass
    zeroFiveRelativePiTwo_boundary_injective
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_infinite r

theorem zeroFiveRelativePiTwoMulEquivInt_meridianLift
    (z : Multiplicative ℤ) :
    zeroFiveRelativePiTwoMulEquivInt
        (zeroFiveRelativePiTwoMeridianLift z) = z := by
  change zeroFiveRelativePiTwoMulEquivInt
      (zeroFiveRelativePiTwoMeridianLift z) = Multiplicative.ofAdd z.toAdd
  exact RelHomotopyGroup.mulEquivIntOfBdRangeZpowers_apply_of_bd_eq_zpow
    (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
      zeroFiveCentralRealizationBase)
    zeroFiveMapCylTopMeridianClass
    zeroFiveRelativePiTwo_boundary_injective
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_infinite
    (zeroFiveRelativePiTwoMeridianLift z) z.toAdd
    (zeroFiveRelativePiTwoMeridianLift_boundary z)

theorem zeroFiveRelativePiTwoMeridianLift_eq_mulEquivInt_symm
    (z : Multiplicative ℤ) :
    zeroFiveRelativePiTwoMeridianLift z =
      zeroFiveRelativePiTwoMulEquivInt.symm z := by
  apply zeroFiveRelativePiTwoMulEquivInt.injective
  rw [zeroFiveRelativePiTwoMulEquivInt_meridianLift,
    zeroFiveRelativePiTwoMulEquivInt.apply_symm_apply]

theorem zeroFiveRelativePiTwoMeridianLift_surjective :
    Function.Surjective zeroFiveRelativePiTwoMeridianLift := by
  intro r
  refine ⟨zeroFiveRelativePiTwoMulEquivInt r, ?_⟩
  rw [zeroFiveRelativePiTwoMeridianLift_eq_mulEquivInt_symm,
    zeroFiveRelativePiTwoMulEquivInt.symm_apply_apply]

theorem zeroFiveRelativePiTwoMeridianLift_bijective :
    Function.Bijective zeroFiveRelativePiTwoMeridianLift :=
  ⟨zeroFiveRelativePiTwoMeridianLift_injective,
    zeroFiveRelativePiTwoMeridianLift_surjective⟩

/-! ## The five-four interface -/

theorem fiveFourMapCyl_piTwo_subsingleton :
    Subsingleton
      (HomotopyGroup.Pi 2
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase :
            TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)) := by
  apply subsingleton_homotopyGroup_of_homotopyEquiv
    (TopCat.MapCyl.homotopyEquivBase
      fiveFourCentralInterfaceInclPairwiseTopCat)
  intro y
  exact pairwiseInterface_higher_homotopy_subsingleton
    5 (by decide) 4 (by decide) (by decide) 0 y

theorem fiveFourRelativePiTwo_boundary_injective :
    Function.Injective
      (RelHomotopyGroup.bdHom 0
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase)) := by
  exact RelHomotopyGroup.bdHom_injective_of_subsingleton
    0 (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
      fiveFourCentralRealizationBase)
    fiveFourMapCyl_piTwo_subsingleton

noncomputable def fiveFourRelativePiTwoMulEquivZpowers :
    RelHomotopyGroup 2
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase) ≃*
      Subgroup.zpowers fiveFourMapCylTopMeridianClass :=
  RelHomotopyGroup.bdMulEquivZpowers
    (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
      fiveFourCentralRealizationBase)
    fiveFourMapCylTopMeridianClass
    fiveFourRelativePiTwo_boundary_injective
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_boundary_range

noncomputable def fiveFourRelativePiTwoMulEquivInt :
    RelHomotopyGroup 2
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase) ≃*
      Multiplicative ℤ :=
  RelHomotopyGroup.mulEquivIntOfBdRangeZpowers
    (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
      fiveFourCentralRealizationBase)
    fiveFourMapCylTopMeridianClass
    fiveFourRelativePiTwo_boundary_injective
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_infinite

theorem fiveFourRelativePiTwoMulEquivInt_boundary
    (r : RelHomotopyGroup 2
      (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop
        fiveFourCentralInterfaceInclPairwiseTopCat
        fiveFourCentralRealizationBase)) :
    RelHomotopyGroup.bd 1
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase) r =
      fiveFourMapCylTopMeridianClass ^
        (fiveFourRelativePiTwoMulEquivInt r).toAdd := by
  exact RelHomotopyGroup.bd_eq_zpow_mulEquivIntOfBdRangeZpowers
    (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
      fiveFourCentralRealizationBase)
    fiveFourMapCylTopMeridianClass
    fiveFourRelativePiTwo_boundary_injective
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_infinite r

theorem fiveFourRelativePiTwoMulEquivInt_meridianLift
    (z : Multiplicative ℤ) :
    fiveFourRelativePiTwoMulEquivInt
        (fiveFourRelativePiTwoMeridianLift z) = z := by
  change fiveFourRelativePiTwoMulEquivInt
      (fiveFourRelativePiTwoMeridianLift z) = Multiplicative.ofAdd z.toAdd
  exact RelHomotopyGroup.mulEquivIntOfBdRangeZpowers_apply_of_bd_eq_zpow
    (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
      fiveFourCentralRealizationBase)
    fiveFourMapCylTopMeridianClass
    fiveFourRelativePiTwo_boundary_injective
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_infinite
    (fiveFourRelativePiTwoMeridianLift z) z.toAdd
    (fiveFourRelativePiTwoMeridianLift_boundary z)

theorem fiveFourRelativePiTwoMeridianLift_eq_mulEquivInt_symm
    (z : Multiplicative ℤ) :
    fiveFourRelativePiTwoMeridianLift z =
      fiveFourRelativePiTwoMulEquivInt.symm z := by
  apply fiveFourRelativePiTwoMulEquivInt.injective
  rw [fiveFourRelativePiTwoMulEquivInt_meridianLift,
    fiveFourRelativePiTwoMulEquivInt.apply_symm_apply]

theorem fiveFourRelativePiTwoMeridianLift_surjective :
    Function.Surjective fiveFourRelativePiTwoMeridianLift := by
  intro r
  refine ⟨fiveFourRelativePiTwoMulEquivInt r, ?_⟩
  rw [fiveFourRelativePiTwoMeridianLift_eq_mulEquivInt_symm,
    fiveFourRelativePiTwoMulEquivInt.symm_apply_apply]

theorem fiveFourRelativePiTwoMeridianLift_bijective :
    Function.Bijective fiveFourRelativePiTwoMeridianLift :=
  ⟨fiveFourRelativePiTwoMeridianLift_injective,
    fiveFourRelativePiTwoMeridianLift_surjective⟩

/-! ## The four-zero interface -/

theorem fourZeroMapCyl_piTwo_subsingleton :
    Subsingleton
      (HomotopyGroup.Pi 2
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase :
            TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)) := by
  apply subsingleton_homotopyGroup_of_homotopyEquiv
    (TopCat.MapCyl.homotopyEquivBase
      fourZeroCentralInterfaceInclPairwiseTopCat)
  intro y
  exact pairwiseInterface_higher_homotopy_subsingleton
    4 (by decide) 0 (by decide) (by decide) 0 y

theorem fourZeroRelativePiTwo_boundary_injective :
    Function.Injective
      (RelHomotopyGroup.bdHom 0
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase)) := by
  exact RelHomotopyGroup.bdHom_injective_of_subsingleton
    0 (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
      fourZeroCentralRealizationBase)
    fourZeroMapCyl_piTwo_subsingleton

noncomputable def fourZeroRelativePiTwoMulEquivZpowers :
    RelHomotopyGroup 2
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase) ≃*
      Subgroup.zpowers fourZeroMapCylTopMeridianClass :=
  RelHomotopyGroup.bdMulEquivZpowers
    (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
      fourZeroCentralRealizationBase)
    fourZeroMapCylTopMeridianClass
    fourZeroRelativePiTwo_boundary_injective
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_boundary_range

noncomputable def fourZeroRelativePiTwoMulEquivInt :
    RelHomotopyGroup 2
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase) ≃*
      Multiplicative ℤ :=
  RelHomotopyGroup.mulEquivIntOfBdRangeZpowers
    (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
      fourZeroCentralRealizationBase)
    fourZeroMapCylTopMeridianClass
    fourZeroRelativePiTwo_boundary_injective
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_infinite

theorem fourZeroRelativePiTwoMulEquivInt_boundary
    (r : RelHomotopyGroup 2
      (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop
        fourZeroCentralInterfaceInclPairwiseTopCat
        fourZeroCentralRealizationBase)) :
    RelHomotopyGroup.bd 1
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase) r =
      fourZeroMapCylTopMeridianClass ^
        (fourZeroRelativePiTwoMulEquivInt r).toAdd := by
  exact RelHomotopyGroup.bd_eq_zpow_mulEquivIntOfBdRangeZpowers
    (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
      fourZeroCentralRealizationBase)
    fourZeroMapCylTopMeridianClass
    fourZeroRelativePiTwo_boundary_injective
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_infinite r

theorem fourZeroRelativePiTwoMulEquivInt_meridianLift
    (z : Multiplicative ℤ) :
    fourZeroRelativePiTwoMulEquivInt
        (fourZeroRelativePiTwoMeridianLift z) = z := by
  change fourZeroRelativePiTwoMulEquivInt
      (fourZeroRelativePiTwoMeridianLift z) = Multiplicative.ofAdd z.toAdd
  exact RelHomotopyGroup.mulEquivIntOfBdRangeZpowers_apply_of_bd_eq_zpow
    (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
      fourZeroCentralRealizationBase)
    fourZeroMapCylTopMeridianClass
    fourZeroRelativePiTwo_boundary_injective
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_boundary_range
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_infinite
    (fourZeroRelativePiTwoMeridianLift z) z.toAdd
    (fourZeroRelativePiTwoMeridianLift_boundary z)

theorem fourZeroRelativePiTwoMeridianLift_eq_mulEquivInt_symm
    (z : Multiplicative ℤ) :
    fourZeroRelativePiTwoMeridianLift z =
      fourZeroRelativePiTwoMulEquivInt.symm z := by
  apply fourZeroRelativePiTwoMulEquivInt.injective
  rw [fourZeroRelativePiTwoMulEquivInt_meridianLift,
    fourZeroRelativePiTwoMulEquivInt.apply_symm_apply]

theorem fourZeroRelativePiTwoMeridianLift_surjective :
    Function.Surjective fourZeroRelativePiTwoMeridianLift := by
  intro r
  refine ⟨fourZeroRelativePiTwoMulEquivInt r, ?_⟩
  rw [fourZeroRelativePiTwoMeridianLift_eq_mulEquivInt_symm,
    fourZeroRelativePiTwoMulEquivInt.symm_apply_apply]

theorem fourZeroRelativePiTwoMeridianLift_bijective :
    Function.Bijective fourZeroRelativePiTwoMeridianLift :=
  ⟨fourZeroRelativePiTwoMeridianLift_injective,
    fourZeroRelativePiTwoMeridianLift_surjective⟩

end Submission.ComplexProjectivePlaneTriangulation
