/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.ComplexProjectivePlaneTrisectionInterfaceSolidTorus
import Submission.ComplexProjectivePlaneTrisectionSurface

/-!
# Meridian slopes in the projective-plane trisection

The three pairwise interfaces have a common seven-vertex torus boundary.  This file records
explicit oriented meridian loops on that boundary and three-triangle fillings in the respective
pairwise interfaces.  Their oriented sum bounds one central triangle.

Two integral edge cocycles on the central torus give coordinates `(1, -1)`, `(0, 1)`, and
`(-1, 0)` on the three meridians.  Thus every cyclic pair has determinant one.  The certificate
is entirely finite: triangle membership, cycle conditions, cocycle conditions, fillings, and
evaluations are all checked by the Lean kernel.
-/

namespace Submission

namespace ComplexProjectivePlaneTriangulation

open FiniteOrderedComplex

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

/-! ## Integral directed edge chains -/

/-- Evaluation of a directed edge list against an integral edge cochain. -/
def evaluateDirectedEdgeChain {V : Type} (cochain : V → V → ℤ)
    (edges : List (V × V)) : ℤ :=
  (edges.map fun edge ↦ cochain edge.1 edge.2).sum

/-- The signed boundary coefficient of a directed edge chain at a vertex. -/
def directedEdgeBoundaryCoefficient {V : Type} [DecidableEq V]
    (edges : List (V × V)) (vertex : V) : ℤ :=
  (edges.countP fun edge ↦ decide (edge.2 = vertex) : ℤ) -
    (edges.countP fun edge ↦ decide (edge.1 = vertex) : ℤ)

/-- A directed edge chain is a one-cycle when its signed boundary vanishes at every vertex. -/
def IsIntegralOneCycle {V : Type} [DecidableEq V] (edges : List (V × V)) : Prop :=
  ∀ vertex, directedEdgeBoundaryCoefficient edges vertex = 0

/-- Every directed edge in the chain occurs in the one-skeleton generated by `facets`. -/
def IsDirectedEdgeChainOn {V : Type} [DecidableEq V]
    (facets : Finset (Finset V)) (edges : List (V × V)) : Prop :=
  ∀ edge ∈ edges, {edge.1, edge.2} ∈ facesOfCard facets 2

/-- An integral edge cochain changes sign when an edge is reversed. -/
def IsAlternatingEdgeCochain {V : Type} (cochain : V → V → ℤ) : Prop :=
  ∀ first second, cochain first second = -cochain second first

/-- An alternating integral edge cochain is closed on every oriented triangle generated by
`facets`. -/
def IsClosedEdgeCochain {V : Type} [DecidableEq V]
    (facets : Finset (Finset V)) (cochain : V → V → ℤ) : Prop :=
  ∀ first second third,
    {first, second, third} ∈ facesOfCard facets 3 →
      cochain first second + cochain second third + cochain third first = 0

/-- A directed edge chain is the integral boundary of a finite list of oriented triangles in
`facets`.  Equality of edge chains is expressed by evaluation against every alternating
cochain; this quotients the two directed presentations of the same oriented edge. -/
def IsIntegralTriangleBoundary {V : Type} [DecidableEq V]
    (facets : Finset (Finset V)) (edges : List (V × V)) : Prop :=
  ∃ triangles : List (OrientedTriangle V),
    (∀ triangle ∈ triangles, triangle.vertices ∈ facesOfCard facets 3) ∧
      ∀ cochain : V → V → ℤ, IsAlternatingEdgeCochain cochain →
        evaluateDirectedEdgeChain cochain (orientedBoundaryEdges triangles) =
          evaluateDirectedEdgeChain cochain edges

/-- A closed edge cochain evaluates to zero on the boundary of an oriented triangle list. -/
theorem evaluate_orientedBoundaryEdges_eq_zero {V : Type} [DecidableEq V]
    {facets : Finset (Finset V)} {cochain : V → V → ℤ}
    (hclosed : IsClosedEdgeCochain facets cochain)
    (triangles : List (OrientedTriangle V))
    (hfaces : ∀ triangle ∈ triangles,
      triangle.vertices ∈ facesOfCard facets 3) :
    evaluateDirectedEdgeChain cochain (orientedBoundaryEdges triangles) = 0 := by
  induction triangles with
  | nil => rfl
  | cons triangle triangles inductionHypothesis =>
      have htriangle := hclosed triangle.first triangle.second triangle.third
        (hfaces triangle (by simp))
      have htail : ∀ other ∈ triangles,
          other.vertices ∈ facesOfCard facets 3 := by
        intro other hother
        exact hfaces other (by simp [hother])
      rw [orientedBoundaryEdges, List.flatMap_cons]
      simp only [evaluateDirectedEdgeChain, List.map_append, List.sum_append,
        OrientedTriangle.boundary, List.map_cons, List.map_nil, List.sum_cons,
        List.sum_nil, add_zero]
      change cochain triangle.first triangle.second +
          (cochain triangle.second triangle.third +
            cochain triangle.third triangle.first) +
        evaluateDirectedEdgeChain cochain (orientedBoundaryEdges triangles) = 0
      rw [inductionHypothesis htail]
      omega

/-- Consequently a closed alternating cochain vanishes on every integral triangle boundary. -/
theorem evaluate_eq_zero_of_isIntegralTriangleBoundary {V : Type} [DecidableEq V]
    {facets : Finset (Finset V)} {edges : List (V × V)}
    {cochain : V → V → ℤ}
    (hboundary : IsIntegralTriangleBoundary facets edges)
    (halternating : IsAlternatingEdgeCochain cochain)
    (hclosed : IsClosedEdgeCochain facets cochain) :
    evaluateDirectedEdgeChain cochain edges = 0 := by
  obtain ⟨triangles, hfaces, hevaluation⟩ := hboundary
  rw [← hevaluation cochain halternating]
  exact evaluate_orientedBoundaryEdges_eq_zero hclosed triangles hfaces

/-! ## The three meridian loops and their fillings -/

/-- Meridian of the interface between the pieces at `0` and `5`. -/
def zeroFiveMeridianLoop : List (TrisectionVertex × TrisectionVertex) :=
  [(1, 7), (7, 12), (12, 1)]

/-- The meridian bounds the cone at vertex `9` on the zero-five interface. -/
def zeroFiveMeridianDisk : List (OrientedTriangle TrisectionVertex) :=
  [⟨1, 7, 9⟩, ⟨7, 12, 9⟩, ⟨12, 1, 9⟩]

/-- Meridian of the interface between the pieces at `5` and `4`. -/
def fiveFourMeridianLoop : List (TrisectionVertex × TrisectionVertex) :=
  [(7, 3), (3, 12), (12, 7)]

/-- The rotated meridian bounds the cone at vertex `11` on the five-four interface. -/
def fiveFourMeridianDisk : List (OrientedTriangle TrisectionVertex) :=
  [⟨7, 3, 11⟩, ⟨3, 12, 11⟩, ⟨12, 7, 11⟩]

/-- Meridian of the interface between the pieces at `4` and `0`. -/
def fourZeroMeridianLoop : List (TrisectionVertex × TrisectionVertex) :=
  [(3, 1), (1, 12), (12, 3)]

/-- The twice-rotated meridian bounds the cone at vertex `10` on the four-zero interface. -/
def fourZeroMeridianDisk : List (OrientedTriangle TrisectionVertex) :=
  [⟨3, 1, 10⟩, ⟨1, 12, 10⟩, ⟨12, 3, 10⟩]

theorem zeroFiveMeridianLoop_isIntegralOneCycle :
    IsIntegralOneCycle zeroFiveMeridianLoop := by
  unfold IsIntegralOneCycle
  decide

theorem fiveFourMeridianLoop_isIntegralOneCycle :
    IsIntegralOneCycle fiveFourMeridianLoop := by
  unfold IsIntegralOneCycle
  decide

theorem fourZeroMeridianLoop_isIntegralOneCycle :
    IsIntegralOneCycle fourZeroMeridianLoop := by
  unfold IsIntegralOneCycle
  decide

theorem zeroFiveMeridianLoop_on_centralInterface :
    IsDirectedEdgeChainOn centralInterfaceFacets zeroFiveMeridianLoop := by
  simp [IsDirectedEdgeChainOn, zeroFiveMeridianLoop]
  decide

theorem fiveFourMeridianLoop_on_centralInterface :
    IsDirectedEdgeChainOn centralInterfaceFacets fiveFourMeridianLoop := by
  simp [IsDirectedEdgeChainOn, fiveFourMeridianLoop]
  decide

theorem fourZeroMeridianLoop_on_centralInterface :
    IsDirectedEdgeChainOn centralInterfaceFacets fourZeroMeridianLoop := by
  simp [IsDirectedEdgeChainOn, fourZeroMeridianLoop]
  decide

/-- The first meridian is an integral triangle boundary in its pairwise interface. -/
theorem zeroFiveMeridianLoop_bounds_pairwiseInterface :
    IsIntegralTriangleBoundary (pairwiseInterfaceFacets 0 5)
      zeroFiveMeridianLoop := by
  refine ⟨zeroFiveMeridianDisk, by decide, ?_⟩
  intro cochain halternating
  simp only [zeroFiveMeridianDisk, zeroFiveMeridianLoop, orientedBoundaryEdges,
    List.flatMap_cons, List.flatMap_nil, OrientedTriangle.boundary,
    evaluateDirectedEdgeChain, List.map_append, List.map_cons, List.map_nil,
    List.sum_append, List.sum_cons, List.sum_nil, add_zero]
  rw [halternating 9 1, halternating 9 7, halternating 9 12]
  ring

/-- The second meridian is an integral triangle boundary in its pairwise interface. -/
theorem fiveFourMeridianLoop_bounds_pairwiseInterface :
    IsIntegralTriangleBoundary (pairwiseInterfaceFacets 5 4)
      fiveFourMeridianLoop := by
  refine ⟨fiveFourMeridianDisk, by decide, ?_⟩
  intro cochain halternating
  simp only [fiveFourMeridianDisk, fiveFourMeridianLoop, orientedBoundaryEdges,
    List.flatMap_cons, List.flatMap_nil, OrientedTriangle.boundary,
    evaluateDirectedEdgeChain, List.map_append, List.map_cons, List.map_nil,
    List.sum_append, List.sum_cons, List.sum_nil, add_zero]
  rw [halternating 11 7, halternating 11 3, halternating 11 12]
  ring

/-- The third meridian is an integral triangle boundary in its pairwise interface. -/
theorem fourZeroMeridianLoop_bounds_pairwiseInterface :
    IsIntegralTriangleBoundary (pairwiseInterfaceFacets 4 0)
      fourZeroMeridianLoop := by
  refine ⟨fourZeroMeridianDisk, by decide, ?_⟩
  intro cochain halternating
  simp only [fourZeroMeridianDisk, fourZeroMeridianLoop, orientedBoundaryEdges,
    List.flatMap_cons, List.flatMap_nil, OrientedTriangle.boundary,
    evaluateDirectedEdgeChain, List.map_append, List.map_cons, List.map_nil,
    List.sum_append, List.sum_cons, List.sum_nil, add_zero]
  rw [halternating 10 3, halternating 10 1, halternating 10 12]
  ring

/-! ## Integral slope coordinates on the central torus -/

/-- An alternating indicator cochain generated by a list of positively oriented edges. -/
def alternatingEdgeIndicator {V : Type} [DecidableEq V]
    (positiveEdges : Finset (V × V)) (first second : V) : ℤ :=
  if (first, second) ∈ positiveEdges then 1
  else if (second, first) ∈ positiveEdges then -1
  else 0

/-- Positive edges for the first integral coordinate on the standard seven-vertex torus. -/
def standardTorusFirstCochainPositiveEdges : Finset (Fin 7 × Fin 7) :=
  {(0, 3), (1, 3), (1, 4), (2, 3), (2, 4), (2, 5)}

/-- Positive edges for the second integral coordinate on the standard seven-vertex torus. -/
def standardTorusSecondCochainPositiveEdges : Finset (Fin 7 × Fin 7) :=
  {(0, 1), (0, 5), (3, 1), (4, 1), (4, 2), (4, 5)}

/-- First integral edge cocycle, pulled back through the periodic central-interface coordinates. -/
def centralTorusFirstCochain (first second : TrisectionVertex) : ℤ :=
  alternatingEdgeIndicator standardTorusFirstCochainPositiveEdges
    (centralInterfaceCoordinate first) (centralInterfaceCoordinate second)

/-- Second integral edge cocycle, pulled back through the periodic central-interface coordinates. -/
def centralTorusSecondCochain (first second : TrisectionVertex) : ℤ :=
  alternatingEdgeIndicator standardTorusSecondCochainPositiveEdges
    (centralInterfaceCoordinate first) (centralInterfaceCoordinate second)

theorem centralTorusFirstCochain_alternating :
    IsAlternatingEdgeCochain centralTorusFirstCochain := by
  unfold IsAlternatingEdgeCochain
  decide

theorem centralTorusSecondCochain_alternating :
    IsAlternatingEdgeCochain centralTorusSecondCochain := by
  unfold IsAlternatingEdgeCochain
  decide

theorem centralTorusFirstCochain_closed :
    IsClosedEdgeCochain centralInterfaceFacets centralTorusFirstCochain := by
  unfold IsClosedEdgeCochain
  decide

theorem centralTorusSecondCochain_closed :
    IsClosedEdgeCochain centralInterfaceFacets centralTorusSecondCochain := by
  unfold IsClosedEdgeCochain
  decide

theorem centralTorusFirstCochain_zeroFiveMeridianLoop :
    evaluateDirectedEdgeChain centralTorusFirstCochain zeroFiveMeridianLoop = 1 := by decide

theorem centralTorusSecondCochain_zeroFiveMeridianLoop :
    evaluateDirectedEdgeChain centralTorusSecondCochain zeroFiveMeridianLoop = -1 := by decide

theorem centralTorusFirstCochain_fiveFourMeridianLoop :
    evaluateDirectedEdgeChain centralTorusFirstCochain fiveFourMeridianLoop = 0 := by decide

theorem centralTorusSecondCochain_fiveFourMeridianLoop :
    evaluateDirectedEdgeChain centralTorusSecondCochain fiveFourMeridianLoop = 1 := by decide

theorem centralTorusFirstCochain_fourZeroMeridianLoop :
    evaluateDirectedEdgeChain centralTorusFirstCochain fourZeroMeridianLoop = -1 := by decide

theorem centralTorusSecondCochain_fourZeroMeridianLoop :
    evaluateDirectedEdgeChain centralTorusSecondCochain fourZeroMeridianLoop = 0 := by decide

/-- The two cocycles give the three oriented meridians the coordinates
`(1, -1)`, `(0, 1)`, and `(-1, 0)`. -/
theorem centralMeridian_cocycle_coordinates :
    ((evaluateDirectedEdgeChain centralTorusFirstCochain zeroFiveMeridianLoop,
        evaluateDirectedEdgeChain centralTorusSecondCochain zeroFiveMeridianLoop),
      (evaluateDirectedEdgeChain centralTorusFirstCochain fiveFourMeridianLoop,
        evaluateDirectedEdgeChain centralTorusSecondCochain fiveFourMeridianLoop),
      (evaluateDirectedEdgeChain centralTorusFirstCochain fourZeroMeridianLoop,
        evaluateDirectedEdgeChain centralTorusSecondCochain fourZeroMeridianLoop)) =
      (((1 : ℤ), -1), ((0 : ℤ), 1), ((-1 : ℤ), 0)) := by decide

/-- Determinant of the two integral cocycle-coordinate columns of two directed edge chains. -/
def centralTorusCochainCoordinateDeterminant
    (first second : List (TrisectionVertex × TrisectionVertex)) : ℤ :=
  evaluateDirectedEdgeChain centralTorusFirstCochain first *
      evaluateDirectedEdgeChain centralTorusSecondCochain second -
    evaluateDirectedEdgeChain centralTorusFirstCochain second *
      evaluateDirectedEdgeChain centralTorusSecondCochain first

/-- Every cyclic pair of meridian coordinate vectors has determinant one. -/
theorem centralMeridian_cocycle_coordinate_determinants :
    (centralTorusCochainCoordinateDeterminant
        zeroFiveMeridianLoop fiveFourMeridianLoop,
      centralTorusCochainCoordinateDeterminant
        fiveFourMeridianLoop fourZeroMeridianLoop,
      centralTorusCochainCoordinateDeterminant
        fourZeroMeridianLoop zeroFiveMeridianLoop) = (1, 1, 1) := by decide

/-- The three oriented meridians sum to the boundary of the central triangle `(1, 7, 3)`. -/
theorem centralMeridian_sum_bounds_centralTriangle :
    IsIntegralTriangleBoundary centralInterfaceFacets
      (zeroFiveMeridianLoop ++ fiveFourMeridianLoop ++ fourZeroMeridianLoop) := by
  refine ⟨[⟨1, 7, 3⟩], by decide, ?_⟩
  intro cochain halternating
  simp only [zeroFiveMeridianLoop, fiveFourMeridianLoop, fourZeroMeridianLoop,
    orientedBoundaryEdges, List.flatMap_cons, List.flatMap_nil,
    OrientedTriangle.boundary, evaluateDirectedEdgeChain, List.map_append,
    List.map_cons, List.map_nil, List.sum_append, List.sum_cons, List.sum_nil, add_zero]
  rw [halternating 12 1, halternating 12 7, halternating 12 3,
    halternating 3 1]
  ring

/-- The zero-five meridian is essential on the central torus. -/
theorem zeroFiveMeridianLoop_not_boundary_on_centralInterface :
    ¬ IsIntegralTriangleBoundary centralInterfaceFacets zeroFiveMeridianLoop := by
  intro hboundary
  have hzero := evaluate_eq_zero_of_isIntegralTriangleBoundary hboundary
    centralTorusFirstCochain_alternating centralTorusFirstCochain_closed
  rw [centralTorusFirstCochain_zeroFiveMeridianLoop] at hzero
  norm_num at hzero

/-- The five-four meridian is essential on the central torus. -/
theorem fiveFourMeridianLoop_not_boundary_on_centralInterface :
    ¬ IsIntegralTriangleBoundary centralInterfaceFacets fiveFourMeridianLoop := by
  intro hboundary
  have hzero := evaluate_eq_zero_of_isIntegralTriangleBoundary hboundary
    centralTorusSecondCochain_alternating centralTorusSecondCochain_closed
  rw [centralTorusSecondCochain_fiveFourMeridianLoop] at hzero
  norm_num at hzero

/-- The four-zero meridian is essential on the central torus. -/
theorem fourZeroMeridianLoop_not_boundary_on_centralInterface :
    ¬ IsIntegralTriangleBoundary centralInterfaceFacets fourZeroMeridianLoop := by
  intro hboundary
  have hzero := evaluate_eq_zero_of_isIntegralTriangleBoundary hboundary
    centralTorusFirstCochain_alternating centralTorusFirstCochain_closed
  rw [centralTorusFirstCochain_fourZeroMeridianLoop] at hzero
  norm_num at hzero

end ComplexProjectivePlaneTriangulation

end Submission
