/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.ComplexProjectivePlaneTrisectionMeridianKernels

/-!
# Short exact sequences for the trisection interface maps

The unit integer coordinates make the power homomorphisms generated by the three meridians
injective.  The exact kernel descriptions and surjectivity results then package every
central-to-pairwise fundamental-group map into the short exact sequence

`1 → ℤ → π₁(T²) → π₁(S¹) → 1`.
-/

open CategoryTheory Simplicial
open scoped Topology Topology.Homotopy

namespace Submission

/-- A group element with integer coordinate `1` has distinct integral powers. -/
theorem zpowersHom_injective_of_monoidHom_apply_eq_one
    {G : Type*} [Group G]
    (coordinate : G →* Multiplicative ℤ) (g : G)
    (hcoordinate : coordinate g = Multiplicative.ofAdd (1 : ℤ)) :
    Function.Injective (zpowersHom G g) := by
  intro m n hmn
  have h := congrArg coordinate hmn
  rw [zpowersHom_apply, zpowersHom_apply, map_zpow, map_zpow,
    hcoordinate] at h
  change m.toAdd = n.toAdd
  simpa using congrArg Multiplicative.toAdd h

/-- A group element with integer coordinate `-1` has distinct integral powers. -/
theorem zpowersHom_injective_of_monoidHom_apply_eq_neg_one
    {G : Type*} [Group G]
    (coordinate : G →* Multiplicative ℤ) (g : G)
    (hcoordinate : coordinate g = Multiplicative.ofAdd (-1 : ℤ)) :
    Function.Injective (zpowersHom G g) := by
  intro m n hmn
  have h := congrArg coordinate hmn
  rw [zpowersHom_apply, zpowersHom_apply, map_zpow, map_zpow,
    hcoordinate] at h
  have hadd := congrArg Multiplicative.toAdd h
  change m.toAdd = n.toAdd
  apply neg_injective
  simpa using hadd

namespace ComplexProjectivePlaneTriangulation

open FiniteOrderedComplex

/-- The zero-five meridian inclusion and central-to-pairwise map form a short exact
sequence of groups. -/
theorem zeroFiveCentralInterfaceInclPairwise_piOne_shortExact :
    Function.Injective
        (zpowersHom
          (HomotopyGroup.Pi 1
            (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
            zeroFiveCentralRealizationBase)
          zeroFiveCentralRealizationPiOneClass) ∧
      Function.MulExact
        (zpowersHom
          (HomotopyGroup.Pi 1
            (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
            zeroFiveCentralRealizationBase)
          zeroFiveCentralRealizationPiOneClass)
        (HomotopyGroup.mapHom (N := Fin 1)
          (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
          zeroFiveCentralRealizationBase_map_pairwise_eq) ∧
      Function.Surjective
        (HomotopyGroup.mapHom (N := Fin 1)
          (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
          zeroFiveCentralRealizationBase_map_pairwise_eq) := by
  refine ⟨zpowersHom_injective_of_monoidHom_apply_eq_one
    zeroFiveCentralRealizationPiOneFirstCoordinate
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralRealizationPiOneFirstCoordinate_class, ?_,
    zeroFiveCentralInterfaceInclPairwise_piOne_map_surjective⟩
  intro x
  change x ∈ (HomotopyGroup.mapHom (N := Fin 1)
      (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
      zeroFiveCentralRealizationBase_map_pairwise_eq).ker ↔
    x ∈ (zpowersHom
      (HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        zeroFiveCentralRealizationBase)
      zeroFiveCentralRealizationPiOneClass).range
  rw [zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers,
    Subgroup.range_zpowersHom]
  rfl

/-- The five-four meridian inclusion and central-to-pairwise map form a short exact
sequence of groups. -/
theorem fiveFourCentralInterfaceInclPairwise_piOne_shortExact :
    Function.Injective
        (zpowersHom
          (HomotopyGroup.Pi 1
            (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
            fiveFourCentralRealizationBase)
          fiveFourCentralRealizationPiOneClass) ∧
      Function.MulExact
        (zpowersHom
          (HomotopyGroup.Pi 1
            (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
            fiveFourCentralRealizationBase)
          fiveFourCentralRealizationPiOneClass)
        (HomotopyGroup.mapHom (N := Fin 1)
          (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
          fiveFourCentralRealizationBase_map_pairwise_eq) ∧
      Function.Surjective
        (HomotopyGroup.mapHom (N := Fin 1)
          (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
          fiveFourCentralRealizationBase_map_pairwise_eq) := by
  refine ⟨zpowersHom_injective_of_monoidHom_apply_eq_one
    fiveFourCentralRealizationPiOneSecondCoordinate
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralRealizationPiOneSecondCoordinate_class, ?_,
    fiveFourCentralInterfaceInclPairwise_piOne_map_surjective⟩
  intro x
  change x ∈ (HomotopyGroup.mapHom (N := Fin 1)
      (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
      fiveFourCentralRealizationBase_map_pairwise_eq).ker ↔
    x ∈ (zpowersHom
      (HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fiveFourCentralRealizationBase)
      fiveFourCentralRealizationPiOneClass).range
  rw [fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers,
    Subgroup.range_zpowersHom]
  rfl

/-- The four-zero meridian inclusion and central-to-pairwise map form a short exact
sequence of groups. -/
theorem fourZeroCentralInterfaceInclPairwise_piOne_shortExact :
    Function.Injective
        (zpowersHom
          (HomotopyGroup.Pi 1
            (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
            fourZeroCentralRealizationBase)
          fourZeroCentralRealizationPiOneClass) ∧
      Function.MulExact
        (zpowersHom
          (HomotopyGroup.Pi 1
            (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
            fourZeroCentralRealizationBase)
          fourZeroCentralRealizationPiOneClass)
        (HomotopyGroup.mapHom (N := Fin 1)
          (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
          fourZeroCentralRealizationBase_map_pairwise_eq) ∧
      Function.Surjective
        (HomotopyGroup.mapHom (N := Fin 1)
          (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
          fourZeroCentralRealizationBase_map_pairwise_eq) := by
  refine ⟨zpowersHom_injective_of_monoidHom_apply_eq_neg_one
    fourZeroCentralRealizationPiOneFirstCoordinate
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralRealizationPiOneFirstCoordinate_class, ?_,
    fourZeroCentralInterfaceInclPairwise_piOne_map_surjective⟩
  intro x
  change x ∈ (HomotopyGroup.mapHom (N := Fin 1)
      (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
      fourZeroCentralRealizationBase_map_pairwise_eq).ker ↔
    x ∈ (zpowersHom
      (HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fourZeroCentralRealizationBase)
      fourZeroCentralRealizationPiOneClass).range
  rw [fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers,
    Subgroup.range_zpowersHom]
  rfl

end ComplexProjectivePlaneTriangulation

end Submission

