/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Submission.ComplexProjectivePlaneTrisectionMeridianGroupExtensionActions
import Submission.Homotopy.Connected
import Submission.WhiteheadTheorem.Compressible.Disk

/-!
# Relative homotopy groups of the trisection interfaces

The mapping cylinder turns each central-torus inclusion into a literal subspace inclusion, so the
relative long exact sequence applies without changing the homotopy type of the map.  This file
transfers surjectivity and kernel data through that model and proves, for all three pairwise solid
tori, that relative pi-one and every relative group above degree two are trivial.  Consequently,
each mapping-cylinder pair is one-connected but not two-connected.

In degree two, the boundary image is exactly the cyclic subgroup generated by the transported
meridian.  A choice of preimage for every integral meridian power gives an injective integer-indexed
family of relative classes with exact boundary formulas, hence each relative pi-two set is infinite.
-/

open CategoryTheory Simplicial
open scoped Topology Topology.Homotopy

noncomputable section

namespace Submission

universe u

/-! ## Mapping-cylinder transport -/

theorem homotopyGroup_inducedPointedHom_mapCyl_domIncl_surjective
    {X Y : TopCat.{u}} (n : ℕ) (f : X ⟶ Y) (x : X)
    (hf : Function.Surjective (HomotopyGroup.inducedPointedHom' n x f)) :
    Function.Surjective
      (HomotopyGroup.inducedPointedHom' n x (TopCat.MapCyl.domIncl f)) := by
  have hretr : IsIso
      (HomotopyGroup.inducedPointedHom' n
        (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f)) := by
    apply HomotopyGroup.isIso_inducedPointedHom'_of_isHomotopyEquiv
    exact TopCat.MapCyl.isHomotopyEquiv_retr f
  have hretrBijective : Function.Bijective
      (HomotopyGroup.inducedPointedHom' n
        (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f)) :=
    (Pointed.isIso_iff_bijective _).mp hretr
  have htarget : IsIso
      (HomotopyGroup.inducedPointedHom'.isoTarget n x
        (TopCat.MapCyl.domIncl_retr_eq f).symm).hom :=
    Iso.isIso_hom _
  have hleft : Function.Surjective
      (HomotopyGroup.inducedPointedHom' n x f ≫
        (HomotopyGroup.inducedPointedHom'.isoTarget n x
          (TopCat.MapCyl.domIncl_retr_eq f).symm).hom) :=
    ((Pointed.isIso_iff_bijective _).mp htarget).surjective.comp hf
  have hcomp :=
    HomotopyGroup.inducedPointedHom'_comp_isoTarget_eq_comp n x
      (TopCat.MapCyl.domIncl_retr_eq f).symm
  rw [hcomp] at hleft
  exact Function.Surjective.of_comp_left hleft hretrBijective.injective

theorem RelHomotopyGroup.iStar_mapCyl_surjective_of_induced_surjective
    {X Y : TopCat.{u}} (n : ℕ) (f : X ⟶ Y) (x : X)
    (hf : Function.Surjective (HomotopyGroup.inducedPointedHom' n x f)) :
    Function.Surjective
      (RelHomotopyGroup.iStar n (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x)) := by
  have hdom := homotopyGroup_inducedPointedHom_mapCyl_domIncl_surjective n f x hf
  rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom] at hdom
  intro q
  obtain ⟨p, hp⟩ := hdom q
  refine ⟨HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p, ?_⟩
  change HomotopyGroup.map (TopCat.MapCyl.domInclFromTop f) rfl
      (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p) = q
  rw [HomotopyGroup.map_comp_apply]
  change HomotopyGroup.map (TopCat.MapCyl.domIncl f).hom rfl p = q at hp
  exact hp

theorem RelHomotopyGroup.iStar_mapCyl_top_map_eq_default_iff
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (p : HomotopyGroup.Pi 1 X x) :
    RelHomotopyGroup.iStar 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x)
        (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p) = default ↔
      HomotopyGroup.inducedPointedHom' 1 x f p = default := by
  have hretr : IsIso
      (HomotopyGroup.inducedPointedHom' 1
        (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f)) := by
    apply HomotopyGroup.isIso_inducedPointedHom'_of_isHomotopyEquiv
    exact TopCat.MapCyl.isHomotopyEquiv_retr f
  have hretrInjective : Function.Injective
      (HomotopyGroup.inducedPointedHom' 1
        (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f)) :=
    ((Pointed.isIso_iff_bijective _).mp hretr).injective
  have htarget : IsIso
      (HomotopyGroup.inducedPointedHom'.isoTarget 1 x
        (TopCat.MapCyl.domIncl_retr_eq f).symm).hom :=
    Iso.isIso_hom _
  have htargetInjective : Function.Injective
      (HomotopyGroup.inducedPointedHom'.isoTarget 1 x
        (TopCat.MapCyl.domIncl_retr_eq f).symm).hom :=
    ((Pointed.isIso_iff_bijective _).mp htarget).injective
  have hcomp :=
    HomotopyGroup.inducedPointedHom'_comp_isoTarget_eq_comp 1 x
      (TopCat.MapCyl.domIncl_retr_eq f).symm
  have hvalue := ConcreteCategory.congr_hom hcomp p
  change
    (HomotopyGroup.inducedPointedHom'.isoTarget 1 x
      (TopCat.MapCyl.domIncl_retr_eq f).symm).hom
        (HomotopyGroup.inducedPointedHom' 1 x f p) =
      HomotopyGroup.inducedPointedHom' 1
        (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f)
        (HomotopyGroup.inducedPointedHom' 1 x
          (TopCat.MapCyl.domIncl f) p) at hvalue
  have hfactor :
      HomotopyGroup.inducedPointedHom' 1 x (TopCat.MapCyl.domIncl f) p =
        RelHomotopyGroup.iStar 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
          (TopCat.MapCyl.domInclToTop f x)
          (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p) := by
    change HomotopyGroup.map (TopCat.MapCyl.domIncl f).hom rfl p =
      HomotopyGroup.map (TopCat.MapCyl.domInclFromTop f) rfl
        (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p)
    rw [HomotopyGroup.map_comp_apply]
    exact HomotopyGroup.map_congr
      (TopCat.MapCyl.domIncl_hom_eq_domInclFromTop_comp_domInclToTop f)
      rfl rfl p
  have hdefaults :
      HomotopyGroup.inducedPointedHom' 1
          (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f) default =
        (HomotopyGroup.inducedPointedHom'.isoTarget 1 x
          (TopCat.MapCyl.domIncl_retr_eq f).symm).hom default := by
    exact (HomotopyGroup.inducedPointedHom' 1
      (TopCat.MapCyl.domIncl f x) (TopCat.MapCyl.retr f)).map_point.trans
        (HomotopyGroup.inducedPointedHom'.isoTarget 1 x
          (TopCat.MapCyl.domIncl_retr_eq f).symm).hom.map_point.symm
  constructor
  · intro hp
    have hdom :
        HomotopyGroup.inducedPointedHom' 1 x
          (TopCat.MapCyl.domIncl f) p = default :=
      hfactor.trans hp
    apply htargetInjective
    have hv := hvalue
    rw [hdom] at hv
    exact hv.trans hdefaults
  · intro hp
    rw [← hfactor]
    apply hretrInjective
    have hv := hvalue.symm
    rw [hp] at hv
    exact hv.trans hdefaults.symm

theorem MonoidHom.mem_zpowers_map_iff_of_injective
    {G H : Type*} [Group G] [Group H] (f : G →* H)
    (hf : Function.Injective f) (g p : G) :
    f p ∈ Subgroup.zpowers (f g) ↔ p ∈ Subgroup.zpowers g := by
  rw [Subgroup.mem_zpowers_iff, Subgroup.mem_zpowers_iff]
  constructor
  · rintro ⟨z, hz⟩
    refine ⟨z, hf ?_⟩
    simpa only [map_zpow] using hz
  · rintro ⟨z, rfl⟩
    exact ⟨z, (map_zpow f g z).symm⟩

theorem HomotopyGroup.mapHom_ker_eq_of_base_eq
    {N X Y : Type*} [Fintype N] [Nonempty N] [DecidableEq N]
    [TopologicalSpace X] [TopologicalSpace Y]
    (f : C(X, Y)) (x : X) {y : Y} (h : f x = y) :
    (HomotopyGroup.mapHom (N := N) f rfl).ker =
      (HomotopyGroup.mapHom (N := N) f h).ker := by
  subst y
  rfl

theorem RelHomotopyGroup.iStar_mapCyl_ker_eq_zpowers_of_induced_ker_eq_zpowers
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (g : HomotopyGroup.Pi 1 X x)
    (hker :
      (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker =
        Subgroup.zpowers g) :
    (HomotopyGroup.mapHom (N := Fin 1)
        (TopCat.MapCyl.domInclFromTop f) rfl).ker =
      Subgroup.zpowers
        (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g) := by
  have htopIso : IsIso
      (HomotopyGroup.inducedPointedHom 1 x
        (TopCat.MapCyl.domInclToTop f)) := by
    apply HomotopyGroup.isIso_inducedPointedHom_of_isHomeomorph
    exact TopCat.MapCyl.isHomeomorph_domInclToTop f
  have htopBijective : Function.Bijective
      (HomotopyGroup.inducedPointedHom 1 x
        (TopCat.MapCyl.domInclToTop f)) :=
    (Pointed.isIso_iff_bijective _).mp htopIso
  ext q
  obtain ⟨p, rfl⟩ := htopBijective.surjective q
  change
    RelHomotopyGroup.iStar 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x)
        (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p) = 1 ↔
      HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl p ∈
        Subgroup.zpowers
          (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g)
  have hone :
      (1 : HomotopyGroup.Pi 1 (TopCat.MapCyl f)
        (TopCat.MapCyl.domInclToTop f x)) = default :=
    _root_.HomotopyGroup.one_def
  rw [hone,
    RelHomotopyGroup.iStar_mapCyl_top_map_eq_default_iff]
  change p ∈ (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker ↔ _
  rw [hker]
  exact (MonoidHom.mem_zpowers_map_iff_of_injective
    (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclToTop f) rfl)
    htopBijective.injective g p).symm

theorem RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (g : HomotopyGroup.Pi 1 X x)
    (hker :
      (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker =
        Subgroup.zpowers g) :
    Set.range
        (RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
          (TopCat.MapCyl.domInclToTop f x)) =
      (Subgroup.zpowers
        (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g) :
          Set (HomotopyGroup.Pi 1 (TopCat.MapCyl.top f)
            (TopCat.MapCyl.domInclToTop f x))) := by
  rw [← RelHomotopyGroup.isExactAt_bd_iStar 1
    (TopCat.MapCyl f) (TopCat.MapCyl.top f)
    (TopCat.MapCyl.domInclToTop f x)]
  rw [← RelHomotopyGroup.iStar_mapCyl_ker_eq_zpowers_of_induced_ker_eq_zpowers
    f x g hker]
  ext q
  change
    RelHomotopyGroup.iStar 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x) q = default ↔
      HomotopyGroup.map (TopCat.MapCyl.domInclFromTop f) rfl q = 1
  have hone :
      (1 : HomotopyGroup.Pi 1 (TopCat.MapCyl f)
        (TopCat.MapCyl.domInclToTop f x)) = default :=
    _root_.HomotopyGroup.one_def
  constructor
  · intro hq
    change HomotopyGroup.map (TopCat.MapCyl.domInclFromTop f) rfl q =
      default at hq
    exact hq.trans hone.symm
  · intro hq
    change HomotopyGroup.map (TopCat.MapCyl.domInclFromTop f) rfl q =
      default
    exact hq.trans hone

theorem RelHomotopyGroup.exists_ne_default_bd_mapCyl_eq_top_generator
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (g : HomotopyGroup.Pi 1 X x)
    (hker :
      (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker =
        Subgroup.zpowers g)
    (hg : g ≠ 1) :
    ∃ r : RelHomotopyGroup 2 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x),
      r ≠ default ∧
        RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
            (TopCat.MapCyl.domInclToTop f x) r =
          HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g := by
  have hrange :=
    RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
      f x g hker
  have hmem :
      HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g ∈
        Set.range
          (RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
            (TopCat.MapCyl.domInclToTop f x)) := by
    rw [hrange]
    exact Subgroup.mem_zpowers _
  obtain ⟨r, hr⟩ := hmem
  refine ⟨r, ?_, hr⟩
  intro hrdefault
  have hbdDefault :
      RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
          (TopCat.MapCyl.domInclToTop f x) default = default :=
    IsPointedMap.map_default
  have htopDefault :
      HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g = default := by
    rw [hrdefault, hbdDefault] at hr
    exact hr.symm
  have htopIso : IsIso
      (HomotopyGroup.inducedPointedHom 1 x
        (TopCat.MapCyl.domInclToTop f)) := by
    apply HomotopyGroup.isIso_inducedPointedHom_of_isHomeomorph
    exact TopCat.MapCyl.isHomeomorph_domInclToTop f
  have htopInjective : Function.Injective
      (HomotopyGroup.inducedPointedHom 1 x
        (TopCat.MapCyl.domInclToTop f)) :=
    ((Pointed.isIso_iff_bijective _).mp htopIso).injective
  apply hg
  apply htopInjective
  have hone :
      (1 : HomotopyGroup.Pi 1 (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x)) = default :=
    _root_.HomotopyGroup.one_def
  exact htopDefault.trans (hone.symm.trans
    (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclToTop f) rfl).map_one.symm)

noncomputable def RelHomotopyGroup.mapCylMeridianLift
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (g : HomotopyGroup.Pi 1 X x)
    (hker :
      (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker =
        Subgroup.zpowers g)
    (z : Multiplicative ℤ) :
    RelHomotopyGroup 2 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
      (TopCat.MapCyl.domInclToTop f x) := by
  have hrange :=
    RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
      f x g hker
  have hmem :
      (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g) ^ z.toAdd ∈
        Set.range
          (RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
            (TopCat.MapCyl.domInclToTop f x)) := by
    rw [hrange]
    exact Subgroup.zpow_mem_zpowers _ _
  exact Classical.choose hmem

theorem RelHomotopyGroup.bd_mapCylMeridianLift
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (g : HomotopyGroup.Pi 1 X x)
    (hker :
      (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker =
        Subgroup.zpowers g)
    (z : Multiplicative ℤ) :
    RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x)
        (RelHomotopyGroup.mapCylMeridianLift f x g hker z) =
      (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g) ^ z.toAdd := by
  exact Classical.choose_spec (show
    (HomotopyGroup.map (TopCat.MapCyl.domInclToTop f) rfl g) ^ z.toAdd ∈
      Set.range
        (RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
          (TopCat.MapCyl.domInclToTop f x)) by
    rw [RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
      f x g hker]
    exact Subgroup.zpow_mem_zpowers _ _)

theorem RelHomotopyGroup.mapCylMeridianLift_injective
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (g : HomotopyGroup.Pi 1 X x)
    (hker :
      (HomotopyGroup.mapHom (N := Fin 1) f.hom rfl).ker =
        Subgroup.zpowers g)
    (hg : Function.Injective
      (zpowersHom (HomotopyGroup.Pi 1 X x) g)) :
    Function.Injective
      (RelHomotopyGroup.mapCylMeridianLift f x g hker) := by
  have htopIso : IsIso
      (HomotopyGroup.inducedPointedHom 1 x
        (TopCat.MapCyl.domInclToTop f)) := by
    apply HomotopyGroup.isIso_inducedPointedHom_of_isHomeomorph
    exact TopCat.MapCyl.isHomeomorph_domInclToTop f
  have htopInjective : Function.Injective
      (HomotopyGroup.inducedPointedHom 1 x
        (TopCat.MapCyl.domInclToTop f)) :=
    ((Pointed.isIso_iff_bijective _).mp htopIso).injective
  intro m n hmn
  have hboundary := congrArg
    (RelHomotopyGroup.bd 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
      (TopCat.MapCyl.domInclToTop f x)) hmn
  rw [RelHomotopyGroup.bd_mapCylMeridianLift,
    RelHomotopyGroup.bd_mapCylMeridianLift] at hboundary
  apply hg
  change g ^ m.toAdd = g ^ n.toAdd
  apply htopInjective
  change (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclToTop f) rfl) (g ^ m.toAdd) =
    (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclToTop f) rfl) (g ^ n.toAdd)
  rw [map_zpow, map_zpow]
  exact hboundary

theorem RelHomotopyGroup.unique_of_surjective_iStar_succ_of_injective_iStar
    (n : ℕ) (X : Type*) [TopologicalSpace X] (A : Set X) (a : A)
    (hsurjective : Function.Surjective
      (RelHomotopyGroup.iStar (n + 1) X A a))
    (hinjective : Function.Injective
      (RelHomotopyGroup.iStar n X A a)) :
    Nonempty (Unique (RelHomotopyGroup (n + 1) X A a)) :=
  ExactSeq.unique_mid_of_five
    (RelHomotopyGroup.iStar (n + 1) X A a)
    (RelHomotopyGroup.jStar (n + 1) X A a)
    (RelHomotopyGroup.bd n X A a)
    (RelHomotopyGroup.iStar n X A a)
    hsurjective hinjective
    (RelHomotopyGroup.isExactAt_iStar_jStar n X A a)
    (RelHomotopyGroup.isExactAt_jStar_bd n X A a)
    (RelHomotopyGroup.isExactAt_bd_iStar n X A a)

theorem RelHomotopyGroup.unique_one_mapCyl_of_surjective_one_of_bijective_zero
    {X Y : TopCat.{u}} (f : X ⟶ Y) (x : X)
    (hone : Function.Surjective
      (HomotopyGroup.inducedPointedHom' 1 x f))
    (hzero : Function.Bijective
      (HomotopyGroup.inducedPointedHom' 0 x f)) :
    Nonempty (Unique
      (RelHomotopyGroup 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x))) := by
  haveI hzeroIso : IsIso (HomotopyGroup.inducedPointedHom' 0 x f) :=
    (Pointed.isIso_iff_bijective _).mpr hzero
  apply RelHomotopyGroup.unique_of_surjective_iStar_succ_of_injective_iStar
    0 (TopCat.MapCyl f) (TopCat.MapCyl.top f)
    (TopCat.MapCyl.domInclToTop f x)
  · exact RelHomotopyGroup.iStar_mapCyl_surjective_of_induced_surjective
      1 f x hone
  · exact (RelHomotopyGroup.bijective_iStar_mapCyl_of_isIso
      0 f x hzeroIso).injective

theorem RelHomotopyGroup.unique_succ_mapCyl_of_bijective_adjacent
    {X Y : TopCat.{u}} (n : ℕ) (f : X ⟶ Y) (x : X)
    (hsucc : Function.Bijective
      (HomotopyGroup.inducedPointedHom' (n + 1) x f))
    (hn : Function.Bijective
      (HomotopyGroup.inducedPointedHom' n x f)) :
    Nonempty (Unique
      (RelHomotopyGroup (n + 1) (TopCat.MapCyl f) (TopCat.MapCyl.top f)
        (TopCat.MapCyl.domInclToTop f x))) := by
  haveI hsuccIso : IsIso
      (HomotopyGroup.inducedPointedHom' (n + 1) x f) :=
    (Pointed.isIso_iff_bijective _).mpr hsucc
  haveI hnIso : IsIso (HomotopyGroup.inducedPointedHom' n x f) :=
    (Pointed.isIso_iff_bijective _).mpr hn
  apply RelHomotopyGroup.unique_of_surjective_iStar_succ_of_injective_iStar
    n (TopCat.MapCyl f) (TopCat.MapCyl.top f)
    (TopCat.MapCyl.domInclToTop f x)
  · exact (RelHomotopyGroup.bijective_iStar_mapCyl_of_isIso
      (n + 1) f x hsuccIso).surjective
  · exact (RelHomotopyGroup.bijective_iStar_mapCyl_of_isIso
      n f x hnIso).injective

/-- A mapping-cylinder pair is one-connected when the original map is surjective on fundamental
groups and bijective on path components, uniformly in the basepoint. -/
theorem isOneConnectedPair_mapCyl_of_surjective_one_of_bijective_zero
    {X Y : TopCat} (f : X ⟶ Y)
    (hone : ∀ x : X, Function.Surjective
      (HomotopyGroup.inducedPointedHom' 1 x f))
    (hzero : ∀ x : X, Function.Bijective
      (HomotopyGroup.inducedPointedHom' 0 x f)) :
    IsNConnectedPair 1 (TopCat.MapCyl f) (TopCat.MapCyl.top f) where
  surjective_iStar_zero a := by
    obtain ⟨x, rfl⟩ := (TopCat.MapCyl.isHomeomorph_domInclToTop f).surjective a
    exact RelHomotopyGroup.iStar_mapCyl_surjective_of_induced_surjective
      0 f x (hzero x).surjective
  unique_piRel k hk a := by
    have hkzero : k = 0 := by omega
    subst k
    obtain ⟨x, rfl⟩ := (TopCat.MapCyl.isHomeomorph_domInclToTop f).surjective a
    exact RelHomotopyGroup.unique_one_mapCyl_of_surjective_one_of_bijective_zero
      f x (hone x) (hzero x)

/-- An infinite relative second homotopy set obstructs two-connectedness of a pair. -/
theorem not_isTwoConnectedPair_of_infinite_relative_piTwo
    {X : Type} [TopologicalSpace X] {A : Set X} (a : A)
    (hinfinite : Infinite (RelHomotopyGroup 2 X A a)) :
    ¬ IsNConnectedPair 2 X A := by
  intro hconnected
  letI : Unique (RelHomotopyGroup 2 X A a) :=
    (hconnected.unique_piRel 1 (by omega) a).some
  letI : Infinite (RelHomotopyGroup 2 X A a) := hinfinite
  haveI : Finite (RelHomotopyGroup 2 X A a) :=
    Finite.of_injective (fun _ => PUnit.unit) fun _ _ _ => Subsingleton.elim _ _
  exact not_finite (RelHomotopyGroup 2 X A a)

end Submission

namespace Submission.ComplexProjectivePlaneTriangulation

open FiniteOrderedComplex

/-! ## The three trisection interfaces -/

noncomputable abbrev zeroFiveCentralInterfaceInclPairwiseTopCat :
    SSet.toTop.obj (orderedSSet centralInterfaceFacets) ⟶
      SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 0 5)) :=
  SSet.toTop.map zeroFiveCentralInterfaceInclPairwise

noncomputable def zeroFiveMapCylTopMeridianClass :
    HomotopyGroup.Pi 1
      (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
        zeroFiveCentralRealizationBase) :=
  HomotopyGroup.map
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat)
    rfl zeroFiveCentralRealizationPiOneClass

theorem zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl :
    (HomotopyGroup.mapHom (N := Fin 1)
      zeroFiveCentralInterfaceInclPairwiseTopCat.hom rfl).ker =
        Subgroup.zpowers zeroFiveCentralRealizationPiOneClass := by
  exact (HomotopyGroup.mapHom_ker_eq_of_base_eq
      zeroFiveCentralInterfaceInclPairwiseTopCat.hom
      zeroFiveCentralRealizationBase
      zeroFiveCentralRealizationBase_map_pairwise_eq).trans
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers

theorem zeroFiveMapCylTopIncl_piOne_ker_eq_zpowers :
    (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclFromTop
        zeroFiveCentralInterfaceInclPairwiseTopCat) rfl).ker =
      Subgroup.zpowers zeroFiveMapCylTopMeridianClass := by
  exact RelHomotopyGroup.iStar_mapCyl_ker_eq_zpowers_of_induced_ker_eq_zpowers
    zeroFiveCentralInterfaceInclPairwiseTopCat
    zeroFiveCentralRealizationBase
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl

theorem zeroFiveCentralInterfaceInclPairwise_relative_piTwo_boundary_range :
    Set.range
        (RelHomotopyGroup.bd 1
          (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.domInclToTop
            zeroFiveCentralInterfaceInclPairwiseTopCat
            zeroFiveCentralRealizationBase)) =
      (Subgroup.zpowers zeroFiveMapCylTopMeridianClass :
        Set (HomotopyGroup.Pi 1
          (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.domInclToTop
            zeroFiveCentralInterfaceInclPairwiseTopCat
            zeroFiveCentralRealizationBase))) := by
  exact RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
    zeroFiveCentralInterfaceInclPairwiseTopCat
    zeroFiveCentralRealizationBase
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl

theorem zeroFiveCentralInterfaceInclPairwise_relative_piTwo_nontrivial_boundary :
    ∃ r : RelHomotopyGroup 2
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase),
      r ≠ default ∧
        RelHomotopyGroup.bd 1
            (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
            (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
            (TopCat.MapCyl.domInclToTop
              zeroFiveCentralInterfaceInclPairwiseTopCat
              zeroFiveCentralRealizationBase) r =
          zeroFiveMapCylTopMeridianClass := by
  exact RelHomotopyGroup.exists_ne_default_bd_mapCyl_eq_top_generator
    zeroFiveCentralInterfaceInclPairwiseTopCat
    zeroFiveCentralRealizationBase
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl
    zeroFiveCentralRealizationPiOneClass_ne_one

noncomputable def zeroFiveRelativePiTwoMeridianLift
    (z : Multiplicative ℤ) :
    RelHomotopyGroup 2
      (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop
        zeroFiveCentralInterfaceInclPairwiseTopCat
        zeroFiveCentralRealizationBase) :=
  RelHomotopyGroup.mapCylMeridianLift
    zeroFiveCentralInterfaceInclPairwiseTopCat
    zeroFiveCentralRealizationBase
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl z

theorem zeroFiveRelativePiTwoMeridianLift_boundary
    (z : Multiplicative ℤ) :
    RelHomotopyGroup.bd 1
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase)
        (zeroFiveRelativePiTwoMeridianLift z) =
      zeroFiveMapCylTopMeridianClass ^ z.toAdd := by
  exact RelHomotopyGroup.bd_mapCylMeridianLift
    zeroFiveCentralInterfaceInclPairwiseTopCat
    zeroFiveCentralRealizationBase
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl z

theorem zeroFiveRelativePiTwoMeridianLift_injective :
    Function.Injective zeroFiveRelativePiTwoMeridianLift := by
  exact RelHomotopyGroup.mapCylMeridianLift_injective
    zeroFiveCentralInterfaceInclPairwiseTopCat
    zeroFiveCentralRealizationBase
    zeroFiveCentralRealizationPiOneClass
    zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl
    zeroFiveCentralInterfaceInclPairwise_piOne_shortExact.1

theorem zeroFiveCentralInterfaceInclPairwise_relative_piTwo_infinite :
    Infinite
      (RelHomotopyGroup 2
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat
          zeroFiveCentralRealizationBase)) :=
  Infinite.of_injective zeroFiveRelativePiTwoMeridianLift
    zeroFiveRelativePiTwoMeridianLift_injective

theorem zeroFiveCentralInterfaceInclPairwise_piOne_surjective_at
    (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Function.Surjective
      (HomotopyGroup.inducedPointedHom' 1 x
        zeroFiveCentralInterfaceInclPairwiseTopCat) := by
  rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
  letI : PathConnectedSpace
      (SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :=
    pathConnectedSpace_centralInterfaceRealization
  apply homotopyGroup_map_surjective_of_pathConnected
    (x := zeroFiveCentralInterfaceRealizationCoreBase
      standardTriangleBoundaryCarrierBase)
  exact zeroFiveCentralInterfaceInclPairwise_piOne_surjective_at_core
    standardTriangleBoundaryCarrierBase

theorem zeroFiveCentralInterfaceInclPairwise_relative_piOne_unique
    (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Nonempty (Unique
      (RelHomotopyGroup 1
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat x))) := by
  apply RelHomotopyGroup.unique_one_mapCyl_of_surjective_one_of_bijective_zero
  · exact zeroFiveCentralInterfaceInclPairwise_piOne_surjective_at x
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact zeroFiveCentralInterfaceInclPairwise_piZero_bijective x

theorem zeroFiveCentralInterfaceInclPairwise_relative_pi_ge_three_unique
    (k : ℕ) (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Nonempty (Unique
      (RelHomotopyGroup (k + 3)
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          zeroFiveCentralInterfaceInclPairwiseTopCat x))) := by
  apply RelHomotopyGroup.unique_succ_mapCyl_of_bijective_adjacent
    (n := k + 2)
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    convert zeroFiveCentralInterfaceInclPairwise_higher_pi_bijective
      (k + 1) x using 1
    rfl
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact zeroFiveCentralInterfaceInclPairwise_higher_pi_bijective k x

theorem zeroFiveCentralInterfaceInclPairwise_isOneConnectedPair :
    IsNConnectedPair 1
      (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat) := by
  apply isOneConnectedPair_mapCyl_of_surjective_one_of_bijective_zero
  · exact zeroFiveCentralInterfaceInclPairwise_piOne_surjective_at
  · intro x
    rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact zeroFiveCentralInterfaceInclPairwise_piZero_bijective x

theorem zeroFiveCentralInterfaceInclPairwise_not_isTwoConnectedPair :
    ¬ IsNConnectedPair 2
      (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat) := by
  exact not_isTwoConnectedPair_of_infinite_relative_piTwo
    (TopCat.MapCyl.domInclToTop zeroFiveCentralInterfaceInclPairwiseTopCat
      zeroFiveCentralRealizationBase)
    zeroFiveCentralInterfaceInclPairwise_relative_piTwo_infinite

theorem zeroFiveCentralInterfaceInclPairwise_connectivity_exactly_one :
    IsNConnectedPair 1
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat) ∧
      ¬ IsNConnectedPair 2
        (TopCat.MapCyl zeroFiveCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top zeroFiveCentralInterfaceInclPairwiseTopCat) :=
  ⟨zeroFiveCentralInterfaceInclPairwise_isOneConnectedPair,
    zeroFiveCentralInterfaceInclPairwise_not_isTwoConnectedPair⟩

noncomputable abbrev fiveFourCentralInterfaceInclPairwiseTopCat :
    SSet.toTop.obj (orderedSSet centralInterfaceFacets) ⟶
      SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 5 4)) :=
  SSet.toTop.map fiveFourCentralInterfaceInclPairwise

noncomputable def fiveFourMapCylTopMeridianClass :
    HomotopyGroup.Pi 1
      (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
        fiveFourCentralRealizationBase) :=
  HomotopyGroup.map
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat)
    rfl fiveFourCentralRealizationPiOneClass

theorem fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl :
    (HomotopyGroup.mapHom (N := Fin 1)
      fiveFourCentralInterfaceInclPairwiseTopCat.hom rfl).ker =
        Subgroup.zpowers fiveFourCentralRealizationPiOneClass := by
  exact (HomotopyGroup.mapHom_ker_eq_of_base_eq
      fiveFourCentralInterfaceInclPairwiseTopCat.hom
      fiveFourCentralRealizationBase
      fiveFourCentralRealizationBase_map_pairwise_eq).trans
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers

theorem fiveFourMapCylTopIncl_piOne_ker_eq_zpowers :
    (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclFromTop
        fiveFourCentralInterfaceInclPairwiseTopCat) rfl).ker =
      Subgroup.zpowers fiveFourMapCylTopMeridianClass := by
  exact RelHomotopyGroup.iStar_mapCyl_ker_eq_zpowers_of_induced_ker_eq_zpowers
    fiveFourCentralInterfaceInclPairwiseTopCat
    fiveFourCentralRealizationBase
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl

theorem fiveFourCentralInterfaceInclPairwise_relative_piTwo_boundary_range :
    Set.range
        (RelHomotopyGroup.bd 1
          (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.domInclToTop
            fiveFourCentralInterfaceInclPairwiseTopCat
            fiveFourCentralRealizationBase)) =
      (Subgroup.zpowers fiveFourMapCylTopMeridianClass :
        Set (HomotopyGroup.Pi 1
          (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.domInclToTop
            fiveFourCentralInterfaceInclPairwiseTopCat
            fiveFourCentralRealizationBase))) := by
  exact RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
    fiveFourCentralInterfaceInclPairwiseTopCat
    fiveFourCentralRealizationBase
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl

theorem fiveFourCentralInterfaceInclPairwise_relative_piTwo_nontrivial_boundary :
    ∃ r : RelHomotopyGroup 2
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase),
      r ≠ default ∧
        RelHomotopyGroup.bd 1
            (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
            (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
            (TopCat.MapCyl.domInclToTop
              fiveFourCentralInterfaceInclPairwiseTopCat
              fiveFourCentralRealizationBase) r =
          fiveFourMapCylTopMeridianClass := by
  exact RelHomotopyGroup.exists_ne_default_bd_mapCyl_eq_top_generator
    fiveFourCentralInterfaceInclPairwiseTopCat
    fiveFourCentralRealizationBase
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl
    fiveFourCentralRealizationPiOneClass_ne_one

noncomputable def fiveFourRelativePiTwoMeridianLift
    (z : Multiplicative ℤ) :
    RelHomotopyGroup 2
      (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop
        fiveFourCentralInterfaceInclPairwiseTopCat
        fiveFourCentralRealizationBase) :=
  RelHomotopyGroup.mapCylMeridianLift
    fiveFourCentralInterfaceInclPairwiseTopCat
    fiveFourCentralRealizationBase
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl z

theorem fiveFourRelativePiTwoMeridianLift_boundary
    (z : Multiplicative ℤ) :
    RelHomotopyGroup.bd 1
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase)
        (fiveFourRelativePiTwoMeridianLift z) =
      fiveFourMapCylTopMeridianClass ^ z.toAdd := by
  exact RelHomotopyGroup.bd_mapCylMeridianLift
    fiveFourCentralInterfaceInclPairwiseTopCat
    fiveFourCentralRealizationBase
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl z

theorem fiveFourRelativePiTwoMeridianLift_injective :
    Function.Injective fiveFourRelativePiTwoMeridianLift := by
  exact RelHomotopyGroup.mapCylMeridianLift_injective
    fiveFourCentralInterfaceInclPairwiseTopCat
    fiveFourCentralRealizationBase
    fiveFourCentralRealizationPiOneClass
    fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl
    fiveFourCentralInterfaceInclPairwise_piOne_shortExact.1

theorem fiveFourCentralInterfaceInclPairwise_relative_piTwo_infinite :
    Infinite
      (RelHomotopyGroup 2
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat
          fiveFourCentralRealizationBase)) :=
  Infinite.of_injective fiveFourRelativePiTwoMeridianLift
    fiveFourRelativePiTwoMeridianLift_injective

theorem fiveFourCentralInterfaceInclPairwise_piOne_surjective_at
    (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Function.Surjective
      (HomotopyGroup.inducedPointedHom' 1 x
        fiveFourCentralInterfaceInclPairwiseTopCat) := by
  rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
  letI : PathConnectedSpace
      (SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :=
    pathConnectedSpace_centralInterfaceRealization
  apply homotopyGroup_map_surjective_of_pathConnected
    (x := fiveFourCentralInterfaceRealizationCoreBase
      standardTriangleBoundaryCarrierBase)
  exact fiveFourCentralInterfaceInclPairwise_piOne_surjective_at_core
    standardTriangleBoundaryCarrierBase

theorem fiveFourCentralInterfaceInclPairwise_relative_piOne_unique
    (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Nonempty (Unique
      (RelHomotopyGroup 1
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat x))) := by
  apply RelHomotopyGroup.unique_one_mapCyl_of_surjective_one_of_bijective_zero
  · exact fiveFourCentralInterfaceInclPairwise_piOne_surjective_at x
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact fiveFourCentralInterfaceInclPairwise_piZero_bijective x

theorem fiveFourCentralInterfaceInclPairwise_relative_pi_ge_three_unique
    (k : ℕ) (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Nonempty (Unique
      (RelHomotopyGroup (k + 3)
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fiveFourCentralInterfaceInclPairwiseTopCat x))) := by
  apply RelHomotopyGroup.unique_succ_mapCyl_of_bijective_adjacent
    (n := k + 2)
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    convert fiveFourCentralInterfaceInclPairwise_higher_pi_bijective
      (k + 1) x using 1
    rfl
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact fiveFourCentralInterfaceInclPairwise_higher_pi_bijective k x

theorem fiveFourCentralInterfaceInclPairwise_isOneConnectedPair :
    IsNConnectedPair 1
      (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat) := by
  apply isOneConnectedPair_mapCyl_of_surjective_one_of_bijective_zero
  · exact fiveFourCentralInterfaceInclPairwise_piOne_surjective_at
  · intro x
    rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact fiveFourCentralInterfaceInclPairwise_piZero_bijective x

theorem fiveFourCentralInterfaceInclPairwise_not_isTwoConnectedPair :
    ¬ IsNConnectedPair 2
      (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat) := by
  exact not_isTwoConnectedPair_of_infinite_relative_piTwo
    (TopCat.MapCyl.domInclToTop fiveFourCentralInterfaceInclPairwiseTopCat
      fiveFourCentralRealizationBase)
    fiveFourCentralInterfaceInclPairwise_relative_piTwo_infinite

theorem fiveFourCentralInterfaceInclPairwise_connectivity_exactly_one :
    IsNConnectedPair 1
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat) ∧
      ¬ IsNConnectedPair 2
        (TopCat.MapCyl fiveFourCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fiveFourCentralInterfaceInclPairwiseTopCat) :=
  ⟨fiveFourCentralInterfaceInclPairwise_isOneConnectedPair,
    fiveFourCentralInterfaceInclPairwise_not_isTwoConnectedPair⟩

noncomputable abbrev fourZeroCentralInterfaceInclPairwiseTopCat :
    SSet.toTop.obj (orderedSSet centralInterfaceFacets) ⟶
      SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 4 0)) :=
  SSet.toTop.map fourZeroCentralInterfaceInclPairwise

noncomputable def fourZeroMapCylTopMeridianClass :
    HomotopyGroup.Pi 1
      (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
        fourZeroCentralRealizationBase) :=
  HomotopyGroup.map
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat)
    rfl fourZeroCentralRealizationPiOneClass

theorem fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl :
    (HomotopyGroup.mapHom (N := Fin 1)
      fourZeroCentralInterfaceInclPairwiseTopCat.hom rfl).ker =
        Subgroup.zpowers fourZeroCentralRealizationPiOneClass := by
  exact (HomotopyGroup.mapHom_ker_eq_of_base_eq
      fourZeroCentralInterfaceInclPairwiseTopCat.hom
      fourZeroCentralRealizationBase
      fourZeroCentralRealizationBase_map_pairwise_eq).trans
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers

theorem fourZeroMapCylTopIncl_piOne_ker_eq_zpowers :
    (HomotopyGroup.mapHom (N := Fin 1)
      (TopCat.MapCyl.domInclFromTop
        fourZeroCentralInterfaceInclPairwiseTopCat) rfl).ker =
      Subgroup.zpowers fourZeroMapCylTopMeridianClass := by
  exact RelHomotopyGroup.iStar_mapCyl_ker_eq_zpowers_of_induced_ker_eq_zpowers
    fourZeroCentralInterfaceInclPairwiseTopCat
    fourZeroCentralRealizationBase
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl

theorem fourZeroCentralInterfaceInclPairwise_relative_piTwo_boundary_range :
    Set.range
        (RelHomotopyGroup.bd 1
          (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.domInclToTop
            fourZeroCentralInterfaceInclPairwiseTopCat
            fourZeroCentralRealizationBase)) =
      (Subgroup.zpowers fourZeroMapCylTopMeridianClass :
        Set (HomotopyGroup.Pi 1
          (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
          (TopCat.MapCyl.domInclToTop
            fourZeroCentralInterfaceInclPairwiseTopCat
            fourZeroCentralRealizationBase))) := by
  exact RelHomotopyGroup.bd_mapCyl_range_eq_zpowers_of_induced_ker_eq_zpowers
    fourZeroCentralInterfaceInclPairwiseTopCat
    fourZeroCentralRealizationBase
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl

theorem fourZeroCentralInterfaceInclPairwise_relative_piTwo_nontrivial_boundary :
    ∃ r : RelHomotopyGroup 2
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase),
      r ≠ default ∧
        RelHomotopyGroup.bd 1
            (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
            (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
            (TopCat.MapCyl.domInclToTop
              fourZeroCentralInterfaceInclPairwiseTopCat
              fourZeroCentralRealizationBase) r =
          fourZeroMapCylTopMeridianClass := by
  exact RelHomotopyGroup.exists_ne_default_bd_mapCyl_eq_top_generator
    fourZeroCentralInterfaceInclPairwiseTopCat
    fourZeroCentralRealizationBase
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl
    fourZeroCentralRealizationPiOneClass_ne_one

noncomputable def fourZeroRelativePiTwoMeridianLift
    (z : Multiplicative ℤ) :
    RelHomotopyGroup 2
      (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.domInclToTop
        fourZeroCentralInterfaceInclPairwiseTopCat
        fourZeroCentralRealizationBase) :=
  RelHomotopyGroup.mapCylMeridianLift
    fourZeroCentralInterfaceInclPairwiseTopCat
    fourZeroCentralRealizationBase
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl z

theorem fourZeroRelativePiTwoMeridianLift_boundary
    (z : Multiplicative ℤ) :
    RelHomotopyGroup.bd 1
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase)
        (fourZeroRelativePiTwoMeridianLift z) =
      fourZeroMapCylTopMeridianClass ^ z.toAdd := by
  exact RelHomotopyGroup.bd_mapCylMeridianLift
    fourZeroCentralInterfaceInclPairwiseTopCat
    fourZeroCentralRealizationBase
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl z

theorem fourZeroRelativePiTwoMeridianLift_injective :
    Function.Injective fourZeroRelativePiTwoMeridianLift := by
  exact RelHomotopyGroup.mapCylMeridianLift_injective
    fourZeroCentralInterfaceInclPairwiseTopCat
    fourZeroCentralRealizationBase
    fourZeroCentralRealizationPiOneClass
    fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers_rfl
    fourZeroCentralInterfaceInclPairwise_piOne_shortExact.1

theorem fourZeroCentralInterfaceInclPairwise_relative_piTwo_infinite :
    Infinite
      (RelHomotopyGroup 2
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat
          fourZeroCentralRealizationBase)) :=
  Infinite.of_injective fourZeroRelativePiTwoMeridianLift
    fourZeroRelativePiTwoMeridianLift_injective

theorem fourZeroCentralInterfaceInclPairwise_piOne_surjective_at
    (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Function.Surjective
      (HomotopyGroup.inducedPointedHom' 1 x
        fourZeroCentralInterfaceInclPairwiseTopCat) := by
  rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
  letI : PathConnectedSpace
      (SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :=
    pathConnectedSpace_centralInterfaceRealization
  apply homotopyGroup_map_surjective_of_pathConnected
    (x := fourZeroCentralInterfaceRealizationCoreBase
      standardTriangleBoundaryCarrierBase)
  exact fourZeroCentralInterfaceInclPairwise_piOne_surjective_at_core
    standardTriangleBoundaryCarrierBase

theorem fourZeroCentralInterfaceInclPairwise_relative_piOne_unique
    (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Nonempty (Unique
      (RelHomotopyGroup 1
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat x))) := by
  apply RelHomotopyGroup.unique_one_mapCyl_of_surjective_one_of_bijective_zero
  · exact fourZeroCentralInterfaceInclPairwise_piOne_surjective_at x
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact fourZeroCentralInterfaceInclPairwise_piZero_bijective x

theorem fourZeroCentralInterfaceInclPairwise_relative_pi_ge_three_unique
    (k : ℕ) (x : SSet.toTop.obj (orderedSSet centralInterfaceFacets)) :
    Nonempty (Unique
      (RelHomotopyGroup (k + 3)
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.domInclToTop
          fourZeroCentralInterfaceInclPairwiseTopCat x))) := by
  apply RelHomotopyGroup.unique_succ_mapCyl_of_bijective_adjacent
    (n := k + 2)
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    convert fourZeroCentralInterfaceInclPairwise_higher_pi_bijective
      (k + 1) x using 1
    rfl
  · rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact fourZeroCentralInterfaceInclPairwise_higher_pi_bijective k x

theorem fourZeroCentralInterfaceInclPairwise_isOneConnectedPair :
    IsNConnectedPair 1
      (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat) := by
  apply isOneConnectedPair_mapCyl_of_surjective_one_of_bijective_zero
  · exact fourZeroCentralInterfaceInclPairwise_piOne_surjective_at
  · intro x
    rw [HomotopyGroup.inducedPointedHom'_eq_inducedPointedHom]
    exact fourZeroCentralInterfaceInclPairwise_piZero_bijective x

theorem fourZeroCentralInterfaceInclPairwise_not_isTwoConnectedPair :
    ¬ IsNConnectedPair 2
      (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
      (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat) := by
  exact not_isTwoConnectedPair_of_infinite_relative_piTwo
    (TopCat.MapCyl.domInclToTop fourZeroCentralInterfaceInclPairwiseTopCat
      fourZeroCentralRealizationBase)
    fourZeroCentralInterfaceInclPairwise_relative_piTwo_infinite

theorem fourZeroCentralInterfaceInclPairwise_connectivity_exactly_one :
    IsNConnectedPair 1
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat) ∧
      ¬ IsNConnectedPair 2
        (TopCat.MapCyl fourZeroCentralInterfaceInclPairwiseTopCat)
        (TopCat.MapCyl.top fourZeroCentralInterfaceInclPairwiseTopCat) :=
  ⟨fourZeroCentralInterfaceInclPairwise_isOneConnectedPair,
    fourZeroCentralInterfaceInclPairwise_not_isTwoConnectedPair⟩

end Submission.ComplexProjectivePlaneTriangulation
