/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.GroupTheory.QuotientGroup.Basic
import Submission.ComplexProjectivePlaneTrisectionMeridianExactSequences

/-!
# Quotients by the trisection meridians

Noether's first isomorphism theorem turns the three short exact sequences into explicit
multiplicative equivalences.  At each meridian basepoint, quotienting the central-torus
fundamental group by the cyclic subgroup generated by that meridian gives the corresponding
pairwise solid-torus fundamental group.
-/

open CategoryTheory Simplicial
open scoped Topology Topology.Homotopy

namespace Submission.ComplexProjectivePlaneTriangulation

open FiniteOrderedComplex

/-- The cyclic subgroup generated by the zero-five meridian is normal. -/
instance zeroFiveCentralMeridianZPowers_normal :
    (Subgroup.zpowers zeroFiveCentralRealizationPiOneClass).Normal := by
  rw [← zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers]
  exact (HomotopyGroup.mapHom (N := Fin 1)
    (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
    zeroFiveCentralRealizationBase_map_pairwise_eq).normal_ker

/-- Quotienting the central fundamental group by the zero-five meridian gives the
corresponding pairwise fundamental group. -/
noncomputable def zeroFiveCentralInterfacePiOneQuotientMulEquivPairwise :
    (HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        zeroFiveCentralRealizationBase ⧸
      Subgroup.zpowers zeroFiveCentralRealizationPiOneClass) ≃*
    HomotopyGroup.Pi 1
      (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 0 5)))
      ((SSet.toTop.map
        (zeroFiveMeridianBoundaryInclCentral ≫
          zeroFiveCentralInterfaceInclPairwise)).hom
        zeroFiveBoundaryRealizationBase) := by
  exact @MulEquiv.trans _ _ _ _
    (@QuotientGroup.Quotient.group _ _ _
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
        zeroFiveCentralRealizationBase_map_pairwise_eq).normal_ker).toMul _
    (@QuotientGroup.quotientMulEquivOfEq _ _ _ _
      zeroFiveCentralMeridianZPowers_normal
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
        zeroFiveCentralRealizationBase_map_pairwise_eq).normal_ker
      zeroFiveCentralInterfaceInclPairwise_piOne_ker_eq_zpowers.symm)
    (QuotientGroup.quotientKerEquivOfSurjective
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map zeroFiveCentralInterfaceInclPairwise).hom
        zeroFiveCentralRealizationBase_map_pairwise_eq)
      zeroFiveCentralInterfaceInclPairwise_piOne_map_surjective)

/-- The cyclic subgroup generated by the five-four meridian is normal. -/
instance fiveFourCentralMeridianZPowers_normal :
    (Subgroup.zpowers fiveFourCentralRealizationPiOneClass).Normal := by
  rw [← fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers]
  exact (HomotopyGroup.mapHom (N := Fin 1)
    (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
    fiveFourCentralRealizationBase_map_pairwise_eq).normal_ker

/-- Quotienting the central fundamental group by the five-four meridian gives the
corresponding pairwise fundamental group. -/
noncomputable def fiveFourCentralInterfacePiOneQuotientMulEquivPairwise :
    (HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fiveFourCentralRealizationBase ⧸
      Subgroup.zpowers fiveFourCentralRealizationPiOneClass) ≃*
    HomotopyGroup.Pi 1
      (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 5 4)))
      ((SSet.toTop.map
        (fiveFourMeridianBoundaryInclCentral ≫
          fiveFourCentralInterfaceInclPairwise)).hom
        fiveFourBoundaryRealizationBase) := by
  exact @MulEquiv.trans _ _ _ _
    (@QuotientGroup.Quotient.group _ _ _
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
        fiveFourCentralRealizationBase_map_pairwise_eq).normal_ker).toMul _
    (@QuotientGroup.quotientMulEquivOfEq _ _ _ _
      fiveFourCentralMeridianZPowers_normal
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
        fiveFourCentralRealizationBase_map_pairwise_eq).normal_ker
      fiveFourCentralInterfaceInclPairwise_piOne_ker_eq_zpowers.symm)
    (QuotientGroup.quotientKerEquivOfSurjective
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fiveFourCentralInterfaceInclPairwise).hom
        fiveFourCentralRealizationBase_map_pairwise_eq)
      fiveFourCentralInterfaceInclPairwise_piOne_map_surjective)

/-- The cyclic subgroup generated by the four-zero meridian is normal. -/
instance fourZeroCentralMeridianZPowers_normal :
    (Subgroup.zpowers fourZeroCentralRealizationPiOneClass).Normal := by
  rw [← fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers]
  exact (HomotopyGroup.mapHom (N := Fin 1)
    (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
    fourZeroCentralRealizationBase_map_pairwise_eq).normal_ker

/-- Quotienting the central fundamental group by the four-zero meridian gives the
corresponding pairwise fundamental group. -/
noncomputable def fourZeroCentralInterfacePiOneQuotientMulEquivPairwise :
    (HomotopyGroup.Pi 1
        (SSet.toTop.obj (orderedSSet centralInterfaceFacets))
        fourZeroCentralRealizationBase ⧸
      Subgroup.zpowers fourZeroCentralRealizationPiOneClass) ≃*
    HomotopyGroup.Pi 1
      (SSet.toTop.obj (orderedSSet (pairwiseInterfaceFacets 4 0)))
      ((SSet.toTop.map
        (fourZeroMeridianBoundaryInclCentral ≫
          fourZeroCentralInterfaceInclPairwise)).hom
        fourZeroBoundaryRealizationBase) := by
  exact @MulEquiv.trans _ _ _ _
    (@QuotientGroup.Quotient.group _ _ _
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
        fourZeroCentralRealizationBase_map_pairwise_eq).normal_ker).toMul _
    (@QuotientGroup.quotientMulEquivOfEq _ _ _ _
      fourZeroCentralMeridianZPowers_normal
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
        fourZeroCentralRealizationBase_map_pairwise_eq).normal_ker
      fourZeroCentralInterfaceInclPairwise_piOne_ker_eq_zpowers.symm)
    (QuotientGroup.quotientKerEquivOfSurjective
      (HomotopyGroup.mapHom (N := Fin 1)
        (SSet.toTop.map fourZeroCentralInterfaceInclPairwise).hom
        fourZeroCentralRealizationBase_map_pairwise_eq)
      fourZeroCentralInterfaceInclPairwise_piOne_map_surjective)

end Submission.ComplexProjectivePlaneTriangulation

