/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.Cohomology.FiniteOrderedComplexReindex
import Submission.Hurewicz.SimplexBall

/-!
# Realization of a finite ordered simplex

A finite complex with one facet is reindexed from the full standard ordered simplex.  Its
simplicial set is therefore the standard simplicial simplex, and its realization is homeomorphic
to the exact closed disk of the same dimension.

## Main definitions

* `Submission.FiniteOrderedComplex.simplexSSetIso` identifies any one-facet complex with the
  standard simplicial simplex;
* `Submission.FiniteOrderedComplex.simplexRealizationHomeomorphDisk` identifies its geometric
  realization with the exact closed disk.
-/

noncomputable section

namespace Submission

open CategoryTheory Simplicial

namespace FiniteOrderedComplex

variable {V : Type} [LinearOrder V]

/-- The ordered complex generated by the full standard vertex set is the full nerve. -/
theorem orderedSubcomplex_singleton_univ (n : ℕ) :
    orderedSubcomplex ({Finset.univ} : Finset (Finset (Fin (n + 1)))) = ⊤ := by
  ext Δ x
  constructor
  · intro _
    trivial
  · intro _
    exact ⟨Finset.univ, by simp, fun _ ↦ Finset.mem_univ _⟩

/-- A single full facet on the standard vertices is the standard simplicial simplex. -/
noncomputable def standardSimplexOrderedSSetIso (n : ℕ) :
    orderedSSet ({Finset.univ} : Finset (Finset (Fin (n + 1)))) ≅
      (Δ[n] : SSet) :=
  SSet.Subcomplex.eqToIso (orderedSubcomplex_singleton_univ n) ≪≫
    SSet.Subcomplex.topIso _ ≪≫
      (finNerveIso n).symm

/-- Reindexing the standard single-facet simplex gives the prescribed vertex set. -/
theorem mapFacets_singleton_univ (n : ℕ) (vertices : Finset V)
    (hcard : vertices.card = n + 1) :
    mapFacets (vertices.orderEmbOfFin hcard).toEmbedding
        ({Finset.univ} : Finset (Finset (Fin (n + 1)))) =
      {vertices} := by
  simp [mapFacets, Finset.map_orderEmbOfFin_univ vertices hcard]

/-- Any finite simplex with the prescribed number of ordered vertices is the standard simplicial
simplex. -/
noncomputable def simplexSSetIso (n : ℕ) (vertices : Finset V)
    (hcard : vertices.card = n + 1) :
    orderedSSet ({vertices} : Finset (Finset V)) ≅ (Δ[n] : SSet) :=
  (orderedSSetMapFacetsIso (vertices.orderEmbOfFin hcard)
      ({Finset.univ} : Finset (Finset (Fin (n + 1)))) ≪≫
    SSet.Subcomplex.eqToIso
      (congrArg orderedSubcomplex
        (mapFacets_singleton_univ n vertices hcard))).symm ≪≫
    standardSimplexOrderedSSetIso n

/-- The realization of a finite one-facet simplex is the standard realized simplex. -/
noncomputable def simplexRealizationIso (n : ℕ) (vertices : Finset V)
    (hcard : vertices.card = n + 1) :
    SSet.toTop.obj (orderedSSet ({vertices} : Finset (Finset V))) ≅
      SSet.toTop.obj (Δ[n] : SSet) :=
  SSet.toTop.mapIso (simplexSSetIso n vertices hcard)

/-- The realization of a finite one-facet `n`-simplex is homeomorphic to the exact closed
`n`-disk. -/
noncomputable def simplexRealizationHomeomorphDisk (n : ℕ) (vertices : Finset V)
    (hcard : vertices.card = n + 1) :
    SSet.toTop.obj (orderedSSet ({vertices} : Finset (Finset V))) ≃ₜ
      TopCat.disk.{0} n :=
  (TopCat.homeoOfIso (simplexRealizationIso n vertices hcard)).trans
    ((SimplexCategory.toTopHomeo (SimplexCategory.mk n)).trans
      ((simplexHomeoBall n).trans Homeomorph.ulift.symm))

end FiniteOrderedComplex

end Submission
