/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.FiniteOrderedComplexCarrier
import Submission.Cohomology.FiniteOrderedComplexSSet
import Submission.SSetBoundaryRealization

/-!
# Realizing a finite ordered complex in its affine carrier

The geometric realization of the ordered simplicial set generated by a finite facet family has a
canonical map to the corresponding union of affine simplex faces.  This file constructs that map
through the realization--singular adjunction and proves that its restriction to every listed facet
is the usual affine simplex map.

This is the forward half of the comparison between the abstract simplicial realization and the
concrete affine carrier.  Constructing the inverse and proving the gluing compatibility needed for
a homeomorphism are intentionally left to a later comparison layer.

## Main definitions

* `facetFamilyToSingular`: the simplicial map into the singular complex of the affine carrier;
* `orderedRealizationToFacetFamilyCarrier`: its adjoint continuous realization map;
* `orderedRealizationToFacetFamilyCarrier_comp_facetSSetι`: the exact restriction formula on a
  listed facet.
-/

noncomputable section

open CategoryTheory Simplicial Opposite

namespace Submission.FiniteOrderedComplex

variable {V : Type} [Fintype V] [LinearOrder V]

/-- The affine carrier point represented by a simplex of the ordered complex and a barycentric
point of its standard topological simplex. -/
noncomputable def facetFamilyTopologicalSimplexPoint
    (facets : Finset (Finset V)) {D : SimplexCategoryᵒᵖ}
    (s : (orderedSSet facets).obj D)
    (x : stdSimplex ℝ (Fin (D.unop.len + 1))) : facetFamilyCarrier facets :=
  ⟨stdSimplex.map (fun i ↦ s.1.obj i) x, by
    rcases s.2 with ⟨facet, hfacet, hs⟩
    rw [mem_facetFamilyCarrier_iff]
    refine ⟨facet, hfacet, fun v hv ↦ ?_⟩
    change (FunOnFinite.linearMap ℝ ℝ (fun i ↦ s.1.obj i) x) v = 0
    rw [FunOnFinite.linearMap_apply_apply]
    apply Finset.sum_eq_zero
    intro i hi
    rw [Finset.mem_filter] at hi
    exact False.elim (hv (hi.2 ▸ hs i))⟩

/-- The standard topological simplex associated to a simplex of the ordered complex, mapped into
the union of its affine faces. -/
noncomputable def facetFamilyTopologicalSimplexMap
    (facets : Finset (Finset V)) {D : SimplexCategoryᵒᵖ}
    (s : (orderedSSet facets).obj D) :
    C(stdSimplex ℝ (Fin (D.unop.len + 1)), facetFamilyCarrier facets) where
  toFun := facetFamilyTopologicalSimplexPoint facets s
  continuous_toFun := Continuous.subtype_mk
    (stdSimplex.continuous_map (fun i ↦ s.1.obj i)) _

/-- The affine maps assigned to ordered simplices commute with simplicial restriction. -/
theorem facetFamilyTopologicalSimplexMap_naturality
    (facets : Finset (Finset V)) {D E : SimplexCategoryᵒᵖ} (f : D ⟶ E)
    (s : (orderedSSet facets).obj D) :
    facetFamilyTopologicalSimplexMap facets ((orderedSSet facets).map f s) =
      (facetFamilyTopologicalSimplexMap facets s).comp
        ⟨stdSimplex.map f.unop.toOrderHom, stdSimplex.continuous_map _⟩ := by
  apply ContinuousMap.ext
  intro x
  apply Subtype.ext
  change stdSimplex.map _ x = stdSimplex.map _ (stdSimplex.map _ x)
  rw [stdSimplex.map_comp_apply]
  rfl

/-- The degreewise map from ordered simplices to singular simplices of their affine carrier. -/
def facetFamilyToSingularApp (facets : Finset (Finset V))
    (D : SimplexCategoryᵒᵖ) :
    (orderedSSet facets).obj D ⟶
      (TopCat.toSSet.obj (TopCat.of (facetFamilyCarrier facets))).obj D :=
  ↾fun s ↦ (TopCat.toSSetObjEquiv _ _).symm
    (facetFamilyTopologicalSimplexMap facets s)

/-- The degreewise carrier maps are natural in the simplex category. -/
theorem facetFamilyToSingularApp_naturality
    (facets : Finset (Finset V)) {D E : SimplexCategoryᵒᵖ} (f : D ⟶ E) :
    (orderedSSet facets).map f ≫ facetFamilyToSingularApp facets E =
      facetFamilyToSingularApp facets D ≫
        (TopCat.toSSet.obj (TopCat.of (facetFamilyCarrier facets))).map f := by
  ext s
  apply (TopCat.toSSetObjEquiv _ _).injective
  change facetFamilyTopologicalSimplexMap facets ((orderedSSet facets).map f s) =
    (facetFamilyTopologicalSimplexMap facets s).comp
      ⟨stdSimplex.map f.unop.toOrderHom, stdSimplex.continuous_map _⟩
  exact facetFamilyTopologicalSimplexMap_naturality facets f s

/-- The ordered finite complex mapped simplicially into the singular complex of its affine
carrier. -/
def facetFamilyToSingular (facets : Finset (Finset V)) :
    orderedSSet facets ⟶
      TopCat.toSSet.obj (TopCat.of (facetFamilyCarrier facets)) where
  app := facetFamilyToSingularApp facets
  naturality _ _ f := facetFamilyToSingularApp_naturality facets f

/-- The canonical continuous map from the realization of an ordered finite complex to the union
of its affine simplex faces. -/
def orderedRealizationToFacetFamilyCarrier
    (facets : Finset (Finset V)) :
    SSet.toTop.obj (orderedSSet facets) ⟶
      TopCat.of (facetFamilyCarrier facets) :=
  (sSetTopAdj.homEquiv _ _).symm (facetFamilyToSingular facets)

/-- The canonical top-dimensional ordered simplex associated to a listed facet. -/
def facetCanonicalSimplex {d : ℕ} (facets : Finset (Finset V))
    (facet : Finset V) (hfacet : facet ∈ facets)
    (hcard : facet.card = d + 1) : (orderedSSet facets) _⦋d⦌ :=
  canonicalSimplex facet hcard ⟨facet, hfacet, Finset.Subset.rfl⟩

/-- The Yoneda simplex map selecting a listed facet of the ordered complex. -/
def facetSSetι {d : ℕ} (facets : Finset (Finset V))
    (facet : Finset V) (hfacet : facet ∈ facets)
    (hcard : facet.card = d + 1) :
    (Δ[d] : SSet) ⟶ orderedSSet facets :=
  SSet.yonedaEquiv.symm (facetCanonicalSimplex facets facet hfacet hcard)

/-- The usual affine simplex map from the standard `d`-simplex to a listed carrier face. -/
def facetAffineCarrierMap {d : ℕ} (facets : Finset (Finset V))
    (facet : Finset V) (hfacet : facet ∈ facets)
    (hcard : facet.card = d + 1) :
    C(stdSimplex ℝ (Fin (d + 1)), facetFamilyCarrier facets) :=
  facetFamilyTopologicalSimplexMap facets
    (facetCanonicalSimplex facets facet hfacet hcard)

/-- The affine map of a listed facet, with the geometric standard simplex as its source. -/
def facetTopologicalCarrierMap {d : ℕ} (facets : Finset (Finset V))
    (facet : Finset V) (hfacet : facet ∈ facets)
    (hcard : facet.card = d + 1) :
    SSet.toTop.obj (Δ[d] : SSet) ⟶ TopCat.of (facetFamilyCarrier facets) :=
  TopCat.ofHom ((facetAffineCarrierMap facets facet hfacet hcard).comp
    ⟨SimplexCategory.toTopHomeo (SimplexCategory.mk d),
      (SimplexCategory.toTopHomeo (SimplexCategory.mk d)).continuous⟩)

/-- On each listed facet, the canonical realization-to-carrier map is exactly the usual affine
simplex map. -/
theorem orderedRealizationToFacetFamilyCarrier_comp_facetSSetι
    {d : ℕ} (facets : Finset (Finset V))
    (facet : Finset V) (hfacet : facet ∈ facets)
    (hcard : facet.card = d + 1) :
    SSet.toTop.map (facetSSetι facets facet hfacet hcard) ≫
        orderedRealizationToFacetFamilyCarrier facets =
      facetTopologicalCarrierMap facets facet hfacet hcard := by
  apply (sSetTopAdj.homEquiv _ _).injective
  rw [Adjunction.homEquiv_naturality_left]
  rw [show (sSetTopAdj.homEquiv _ _)
      (orderedRealizationToFacetFamilyCarrier facets) =
        facetFamilyToSingular facets by exact Equiv.apply_symm_apply _ _]
  rw [Adjunction.homEquiv_unit]
  apply SSet.yonedaEquiv.injective
  rw [SSet.yonedaEquiv_comp, SSet.yonedaEquiv_comp]
  apply (TopCat.toSSetObjEquiv _ _).injective
  change facetFamilyTopologicalSimplexMap facets
      (SSet.yonedaEquiv (facetSSetι facets facet hfacet hcard)) =
    (facetTopologicalCarrierMap facets facet hfacet hcard).hom.comp
      ((TopCat.toSSetObjEquiv
        (SSet.toTop.obj (Δ[d] : SSet)) (op (SimplexCategory.mk d)))
          (SSet.yonedaEquiv (sSetTopAdj.unit.app (Δ[d] : SSet))))
  rw [toSSetObjEquiv_yonedaEquiv_unit_stdSimplex]
  apply ContinuousMap.ext
  intro x
  apply Subtype.ext
  change stdSimplex.map _ x = stdSimplex.map _
    ((SimplexCategory.toTopHomeo (SimplexCategory.mk d))
      ((SimplexCategory.toTopHomeo (SimplexCategory.mk d)).symm x))
  rw [Homeomorph.apply_symm_apply]
  rfl

end Submission.FiniteOrderedComplex
