/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.Cohomology.FiniteOrderedComplexReindex
import Submission.SelectedFacesRealization

/-!
# Ordered models of selected standard-simplex faces

This file identifies a selected union of standard simplicial faces with the finite ordered complex
whose facets omit precisely the selected vertices.  Combining that simplicial-set isomorphism with
the selected-face realization theorem gives a homeomorphism from the ordered realization to the
exact affine carrier.

## Main results

* `Submission.FiniteOrderedComplex.selectedFacesOrderedSSetIso`;
* `Submission.FiniteOrderedComplex.selectedFacesOrderedRealizationHomeomorphCarrier`.
-/

noncomputable section

namespace Submission.FiniteOrderedComplex

open CategoryTheory Simplicial

/-- Facets obtained by omitting one selected vertex of a full simplex. -/
def selectedFaceFacets {n : ℕ} (I : Finset (Fin (n + 2))) :
    Finset (Finset (Fin (n + 2))) :=
  I.image fun i ↦ Finset.univ.erase i

/-- Under the standard-simplex/finite-nerve isomorphism, a selected union of faces becomes the
ordered complex generated by the corresponding omitted-vertex facets. -/
theorem selectedFaces_image_finNerveIso {n : ℕ} (I : Finset (Fin (n + 2))) :
    (selectedFacesSubcomplex I).image (finNerveIso (n + 1)).hom =
      orderedSubcomplex (selectedFaceFacets I) := by
  ext Δ x
  constructor
  · rintro ⟨s, hs, rfl⟩
    change s ∈ (⨆ i : I, SSet.stdSimplex.face {i.1}ᶜ).obj Δ at hs
    simp only [Subfunctor.iSup_obj, Set.mem_iUnion] at hs
    obtain ⟨i, hi⟩ := hs
    refine ⟨Finset.univ.erase i.1, ?_, ?_⟩
    · exact Finset.mem_image.mpr ⟨i.1, i.2, rfl⟩
    · intro j
      rw [Finset.mem_erase]
      refine ⟨?_, Finset.mem_univ _⟩
      change Finset.image (SSet.stdSimplex.objEquiv s).toOrderHom Finset.univ ≤
        {i.1}ᶜ at hi
      have hmem := hi (Finset.mem_image.mpr ⟨j, Finset.mem_univ _, rfl⟩)
      have hne : (SSet.stdSimplex.objEquiv s).toOrderHom j ≠ i.1 := by
        simpa only [Finset.mem_compl, Finset.mem_singleton] using hmem
      change (SSet.stdSimplex.objEquiv s).toOrderHom j ≠ i.1
      exact hne
  · rintro ⟨facet, hfacet, hx⟩
    rcases Finset.mem_image.mp hfacet with ⟨i, hiI, rfl⟩
    let s := (finNerveIso (n + 1)).inv.app Δ x
    refine ⟨s, ?_, ?_⟩
    · change s ∈ (⨆ i : I, SSet.stdSimplex.face {i.1}ᶜ).obj Δ
      simp only [Subfunctor.iSup_obj, Set.mem_iUnion]
      refine ⟨⟨i, hiI⟩, ?_⟩
      change Finset.image (SSet.stdSimplex.objEquiv s).toOrderHom Finset.univ ≤
        {i}ᶜ
      intro y hy
      rcases Finset.mem_image.mp hy with ⟨j, hj, rfl⟩
      rw [Finset.mem_compl, Finset.mem_singleton]
      have hxj := Finset.mem_erase.mp (hx j)
      change x.obj j ≠ i
      exact hxj.1
    · simp [s]

/-- The selected standard face union is isomorphic to its ordered finite-complex model. -/
def selectedFacesOrderedSSetIso {n : ℕ} (I : Finset (Fin (n + 2))) :
    (selectedFacesSubcomplex I : SSet) ≅ orderedSSet (selectedFaceFacets I) := by
  let f := (selectedFacesSubcomplex I).toImage (finNerveIso (n + 1)).hom
  letI : Mono f := mono_of_mono_fac
    ((selectedFacesSubcomplex I).toImage_ι (finNerveIso (n + 1)).hom)
  letI : IsIso f := isIso_of_mono_of_epi f
  exact (asIso f) ≪≫ SSet.Subcomplex.eqToIso (selectedFaces_image_finNerveIso I)

/-- The realization of an ordered selected-face complex is homeomorphic to its affine carrier. -/
def selectedFacesOrderedRealizationHomeomorphCarrier {n : ℕ}
    (I : Finset (Fin (n + 2))) :
    SSet.toTop.obj (orderedSSet (selectedFaceFacets I)) ≃ₜ selectedFacesCarrier I :=
  (TopCat.homeoOfIso (SSet.toTop.mapIso (selectedFacesOrderedSSetIso I).symm)).trans
    (selectedFacesRealizationHomeomorphCarrier I)

end Submission.FiniteOrderedComplex
