#!/usr/bin/env python3
"""Generate the exact positive-stem 3-primary theorem family and manifest."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV_PATH = (
    ROOT / "research" / "comprehensive-handoff-2026" / "data"
    / "stable_3_primary_groups_0_108.csv"
)
LEAN_PATH = ROOT / "HomotopyGroups" / "StableThreePrimary.lean"
MANIFEST_PATH = ROOT / "manifests" / "problems" / "stable_three_primary_groups_001_108.toml"
SOURCE_URL = "https://www.sas.rochester.edu/mth/sites/doug-ravenel/mybooks/ravenel3rd.pdf"
CSV_SHA256 = "0d825bd35c689278b4b3bd9865f1579d518c0107d2a216f5337573f1b5f355d0"
CSV_HEADERS = [
    "stem",
    "image_J_or_degree_zero",
    "non_J_component",
    "full_3_primary_component",
    "non_J_generators",
    "notes",
    "status",
    "source",
]

GROUP_CODES = {
    "0": "trivial",
    "Z/3": "c3",
    "(Z/3)^2": "c3Squared",
    "(Z/3)^3": "c3Cubed",
    "Z/9": "c9",
    "Z/3 + Z/9": "c3TimesC9",
    "Z/27": "c27",
    "(Z/3)^2 + Z/81": "c3SquaredTimesC81",
}


class RegistryError(ValueError):
    """Raised when the handoff table does not match the formalization schema."""


def load_rows() -> list[dict[str, str]]:
    try:
        payload = CSV_PATH.read_bytes()
        if hashlib.sha256(payload).hexdigest() != CSV_SHA256:
            raise RegistryError("3-primary CSV does not match the received handoff")
        reader = csv.DictReader(io.StringIO(payload.decode("utf-8"), newline=""))
        rows = list(reader)
        if reader.fieldnames != CSV_HEADERS:
            raise RegistryError(f"unexpected 3-primary CSV header: {reader.fieldnames}")
        stems = [int(row["stem"]) for row in rows]
    except (OSError, UnicodeError, csv.Error, KeyError, TypeError, ValueError) as exc:
        raise RegistryError(f"cannot read {CSV_PATH}: {exc}") from exc
    if stems != list(range(109)):
        raise RegistryError("3-primary rows must be contiguous from stem 0 through 108")
    if any(row["status"] != "exact" for row in rows):
        raise RegistryError("every 3-primary row must have exact status")
    if rows[0]["full_3_primary_component"] != "Z_(3)":
        raise RegistryError("stem 0 must remain the excluded 3-local integer row")
    unknown = sorted(
        {row["full_3_primary_component"] for row in rows[1:]} - GROUP_CODES.keys()
    )
    if unknown:
        raise RegistryError(f"unsupported 3-primary group expressions: {unknown}")
    return rows


def render_lean(rows: list[dict[str, str]]) -> str:
    cases = "\n".join(
        f"  | {int(row['stem']) - 1} => .{GROUP_CODES[row['full_3_primary_component']]}"
        for row in rows[1:]
    )
    return f"""/-
This file is generated by `scripts/generate_three_primary_table.py` from the
audited handoff table `stable_3_primary_groups_0_108.csv`.
Do not edit it by hand.
-/

import EvalTools.Markers
import HomotopyGroups.StableStems
import Mathlib.Algebra.Category.Grp.Basic
import Mathlib.GroupTheory.Torsion

open scoped Topology

namespace HomotopyGroups

/-- The eight finite abelian 3-groups occurring in positive stems through 108. -/
inductive StableThreePrimaryGroupCode where
  | trivial
  | c3
  | c3Squared
  | c3Cubed
  | c9
  | c3TimesC9
  | c27
  | c3SquaredTimesC81

namespace StableThreePrimaryGroupCode

/-- Interpret a table code as an actual bundled multiplicative group. -/
noncomputable def asGrp : StableThreePrimaryGroupCode → GrpCat
  | .trivial => GrpCat.of (Multiplicative (ZMod 1))
  | .c3 => GrpCat.of (Multiplicative (ZMod 3))
  | .c3Squared => GrpCat.of (Multiplicative (ZMod 3 × ZMod 3))
  | .c3Cubed => GrpCat.of (Multiplicative (ZMod 3 × (ZMod 3 × ZMod 3)))
  | .c9 => GrpCat.of (Multiplicative (ZMod 9))
  | .c3TimesC9 => GrpCat.of (Multiplicative (ZMod 3 × ZMod 9))
  | .c27 => GrpCat.of (Multiplicative (ZMod 27))
  | .c3SquaredTimesC81 => GrpCat.of (Multiplicative (ZMod 3 × (ZMod 3 × ZMod 81)))

end StableThreePrimaryGroupCode

/-- Table A3.2 plus image J, in positive stems; index zero represents stable stem one. -/
def stableThreePrimaryGroupCode (stemIndex : Fin 108) : StableThreePrimaryGroupCode :=
  match stemIndex.val with
{cases}
  | _ => .trivial

/-- The finite abelian group represented by `stableThreePrimaryGroupCode`. -/
noncomputable def stableThreePrimaryGroup (stemIndex : Fin 108) : GrpCat :=
  (stableThreePrimaryGroupCode stemIndex).asGrp

/--
The exact 3-primary components of the positive stable stems 1 through 108.
The finite index `stemIndex` represents stable stem `stemIndex + 1`; the
chosen homotopy group is the same canonical Freudenthal-range representative
used by `HomotopyGroups.StableStems`.

Stem zero is deliberately excluded: its `Z_(3)` entry is a localization of the
infinite cyclic group, not the primary torsion subgroup defined by Mathlib.

Source: Ravenel, *Complex Cobordism and Stable Homotopy Groups of Spheres*,
digital third edition (2026), Table A3.2 plus the image-of-J formula: {SOURCE_URL}
-/
@[eval_problem]
theorem stable_three_primary_groups_001_108 (stemIndex : Fin 108) :
    Nonempty
      (CommGroup.primaryComponent
          (π_ (2 * (stemIndex.val + 1) + 2)
            (StableStems.StableSphere (stemIndex.val + 3))
            (StableStems.stableSphereBasepoint (stemIndex.val + 3))) 3 ≃*
        stableThreePrimaryGroup stemIndex) := by
  sorry

end HomotopyGroups
"""


def render_manifest() -> str:
    return f"""id = "stable_three_primary_groups_001_108"
title = "Exact 3-primary stable groups in stems 1 through 108"
test = false
module = "HomotopyGroups.StableThreePrimary"
holes = ["stable_three_primary_groups_001_108"]
submitter = "homotopy-groups-lean comprehensive 2026 registry"
source = "Ravenel, Complex Cobordism and Stable Homotopy Groups of Spheres, digital third edition (2026), Table A3.2 plus the image-of-J formula: {SOURCE_URL}"
notes = "knowledge_status=known_result/exact; one finite-indexed theorem family states the exact 3-primary subgroup in every positive stable stem from 1 through 108; generated from the audited handoff CSV; stem 0 is excluded because Z_(3) is localization rather than primary torsion."
"""


def outputs(rows: list[dict[str, str]]) -> dict[pathlib.Path, str]:
    return {LEAN_PATH: render_lean(rows), MANIFEST_PATH: render_manifest()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        desired = outputs(load_rows())
    except RegistryError as exc:
        print(f"3-primary generation failed: {exc}", file=sys.stderr)
        return 2
    stale: list[str] = []
    for path, expected in desired.items():
        if args.check:
            try:
                actual = path.read_text(encoding="utf-8")
            except OSError:
                actual = ""
            if actual != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                path.write_text(expected, encoding="utf-8")
    if stale:
        print("stale generated 3-primary files: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(f"3-primary theorem family {'current' if args.check else 'generated'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
