/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.Homology.Excision
import Mathlib.Algebra.Homology.QuasiIso

/-!
# Small relative singular chains

The small-simplices theorem identifies the singular chain complex of a space with the subcomplex
generated by simplices subordinate to a cover.  This file descends that comparison to a relative
pair `(X, A)` when `A` is contained in one member of the cover.

This is useful when comparing maps of pairs locally.  It is enough to compare their induced chain
maps on subordinate simplices; the relative small-chain inclusion is a homology isomorphism.
-/

open CategoryTheory Limits AlgebraicTopology Simplicial Opposite

attribute [local implicit_reducible] Limits.Cofan.mk Limits.sigmaConst
  AlgebraicTopology.alternatingFaceMapComplex AlgebraicTopology.AlternatingFaceMapComplex.obj
  SSet.chainComplexFunctor AlgebraicTopology.singularChainComplexFunctor

noncomputable section

namespace Submission

variable {X : TopCat.{0}} {ι : Type*} (U : ι → Set X) (A : Set X)
  (i₀ : ι) (hA : A ⊆ U i₀)

/-- The singular simplicial set of `A`, included in the subcomplex of simplices subordinate to
`U`.  The hypothesis that `A` lies in one cover member makes every simplex of `A` subordinate
without subdivision. -/
noncomputable def smallSubspaceMap :
    TopCat.toSSet.obj (TopCat.of A) ⟶ (TopCat.toSSet.subcomplexOfSets U : SSet) :=
  SSet.Subcomplex.lift (TopCat.toSSet.map (subIncl A)) (by
    intro j s hs
    obtain ⟨t, rfl⟩ := hs
    rw [TopCat.toSSet.mem_subcomplexOfSets_iff']
    let f : TopCat.of A ⟶ TopCat.of (U i₀) :=
      TopCat.ofHom ⟨fun a ↦ ⟨a.1, hA a.2⟩, by fun_prop⟩
    exact ⟨i₀, (TopCat.toSSet.map f).app j t, rfl⟩)

@[reassoc (attr := simp)]
theorem smallSubspaceMap_ι :
    smallSubspaceMap U A i₀ hA ≫ (TopCat.toSSet.subcomplexOfSets U).ι =
      TopCat.toSSet.map (subIncl A) :=
  SSet.Subcomplex.lift_ι _ _

/-- The inclusion of `A` into the subordinate singular subcomplex is injective in every
simplicial degree. -/
theorem injective_smallSubspaceMap_app (n : ℕ) :
    Function.Injective ((smallSubspaceMap U A i₀ hA).app (op ⦋n⦌)) := by
  intro s t hst
  apply injective_toSSet_map_app (subIncl A) Subtype.val_injective n
  exact congrArg Subtype.val hst

instance mono_smallSubspaceMap : Mono (smallSubspaceMap U A i₀ hA) := by
  rw [NatTrans.mono_iff_mono_app]
  rintro ⟨⟨n⟩⟩
  rw [CategoryTheory.mono_iff_injective]
  exact injective_smallSubspaceMap_app U A i₀ hA n

/-- On chains, including `A` into the subordinate subcomplex and then into all singular chains
is the ordinary singular-chain inclusion. -/
@[reassoc (attr := simp)]
theorem smallSubspaceMap_smallIncl :
    SSet.chainComplexMap (smallSubspaceMap U A i₀ hA) (AddCommGrpCat.of ℤ) ≫
        SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι (AddCommGrpCat.of ℤ) =
      CsingMap (subIncl A) := by
  rw [← ((SSet.chainComplexFunctor AddCommGrpCat.{0}).obj
    (AddCommGrpCat.of ℤ)).map_comp, smallSubspaceMap_ι]
  rfl

/-- The relative chain complex obtained by quotienting subordinate chains by all chains in
`A`. -/
noncomputable def smallRelativeComplex : ChainComplex AddCommGrpCat.{0} ℕ :=
  cokernel (SSet.chainComplexMap (smallSubspaceMap U A i₀ hA) (AddCommGrpCat.of ℤ))

/-- The defining short complex for subordinate relative chains. -/
noncomputable def smallRelativeShortComplex :
    ShortComplex (ChainComplex AddCommGrpCat.{0} ℕ) :=
  let f := SSet.chainComplexMap (smallSubspaceMap U A i₀ hA) (AddCommGrpCat.of ℤ)
  ShortComplex.mk f (cokernel.π f) (cokernel.condition f)

/-- The defining short complex for subordinate relative chains is short exact. -/
theorem smallRelativeShortComplex_shortExact :
    (smallRelativeShortComplex U A i₀ hA).ShortExact where
  exact := ShortComplex.exact_cokernel _
  mono_f := by
    change Mono (SSet.chainComplexMap (smallSubspaceMap U A i₀ hA)
      (AddCommGrpCat.of ℤ))
    infer_instance
  epi_g := coequalizer.π_epi

/-- Inclusion of subordinate chains into all singular chains, descended to the relative
quotients. -/
noncomputable def smallRelativeInclusion :
    smallRelativeComplex U A i₀ hA ⟶ relComplex (subIncl A) :=
  cokernel.map
    (SSet.chainComplexMap (smallSubspaceMap U A i₀ hA) (AddCommGrpCat.of ℤ))
    (CsingMap (subIncl A)) (𝟙 _)
    (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι (AddCommGrpCat.of ℤ))
    ((smallSubspaceMap_smallIncl U A i₀ hA).trans (Category.id_comp _).symm)

/-- The quotient projection followed by the relative small-chain inclusion is inclusion of
subordinate absolute chains followed by the ordinary relative projection. -/
@[reassoc (attr := simp)]
theorem smallRelative_π_inclusion :
    cokernel.π (SSet.chainComplexMap (smallSubspaceMap U A i₀ hA)
        (AddCommGrpCat.of ℤ)) ≫ smallRelativeInclusion U A i₀ hA =
      SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ) ≫ relProj (subIncl A) :=
  cokernel.π_desc _ _ _

/-- The morphism from the defining subordinate relative short complex to the ordinary relative
short complex. -/
noncomputable def smallRelativeShortComplexMap :
    smallRelativeShortComplex U A i₀ hA ⟶ relShortComplex (subIncl A) where
  τ₁ := 𝟙 _
  τ₂ := SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
    (AddCommGrpCat.of ℤ)
  τ₃ := smallRelativeInclusion U A i₀ hA
  comm₁₂ := by
    change (𝟙 _ : Csing (TopCat.of A) ⟶ Csing (TopCat.of A)) ≫ CsingMap (subIncl A) =
      SSet.chainComplexMap (smallSubspaceMap U A i₀ hA) (AddCommGrpCat.of ℤ) ≫
        SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι (AddCommGrpCat.of ℤ)
    rw [Category.id_comp, smallSubspaceMap_smallIncl]
  comm₂₃ := by
    change SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ) ≫ relProj (subIncl A) =
      cokernel.π (SSet.chainComplexMap (smallSubspaceMap U A i₀ hA)
        (AddCommGrpCat.of ℤ)) ≫ smallRelativeInclusion U A i₀ hA
    symm
    exact cokernel.π_desc _ _ _

/-- **Relative small-simplices theorem.**  If the interiors of `U` cover `X` and `A` is
contained in one member, inclusion of subordinate relative chains induces an isomorphism on
homology in every degree. -/
theorem isIso_homologyMap_smallRelativeInclusion
    (hU : TopCat.SmallSimplicesCondition U) (n : ℕ) :
    IsIso (HomologicalComplex.homologyMap
      (smallRelativeInclusion U A i₀ hA) n) := by
  apply HomologicalComplex.HomologySequence.isIso_homologyMap_τ₃
    (smallRelativeShortComplexMap U A i₀ hA)
    (smallRelativeShortComplex_shortExact U A i₀ hA)
    (relShortComplex_shortExact (subIncl A))
  · change Epi (HomologicalComplex.homologyMap
      (𝟙 (Csing (TopCat.of A))) n)
    rw [HomologicalComplex.homologyMap_id]
    infer_instance
  · change IsIso (HomologicalComplex.homologyMap
      (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ)) n)
    rw [← quasiIsoAt_iff_isIso_homologyMap]
    letI : QuasiIso (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ)) :=
      homotopyEquivalences_le_quasiIso AddCommGrpCat.{0} (ComplexShape.down ℕ) _
        (hU.homotopyEquivalences (AddCommGrpCat.of ℤ))
    exact QuasiIso.quasiIsoAt n
  · intro j _
    change IsIso (HomologicalComplex.homologyMap
      (𝟙 (Csing (TopCat.of A))) j)
    rw [HomologicalComplex.homologyMap_id]
    infer_instance
  · intro j _
    change Mono (HomologicalComplex.homologyMap
      (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ)) j)
    haveI : IsIso (HomologicalComplex.homologyMap
        (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
          (AddCommGrpCat.of ℤ)) j) := by
      rw [← quasiIsoAt_iff_isIso_homologyMap]
      letI : QuasiIso (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
          (AddCommGrpCat.of ℤ)) :=
        homotopyEquivalences_le_quasiIso AddCommGrpCat.{0} (ComplexShape.down ℕ) _
          (hU.homotopyEquivalences (AddCommGrpCat.of ℤ))
      exact QuasiIso.quasiIsoAt j
    infer_instance

/-! ### The relative theorem for the induced cover of the subspace -/

/-- Restrict a family of subsets of `X` to the subspace `A`. -/
def restrictedCover : ι → Set (TopCat.of A) :=
  fun i ↦ {a | (a.1 : X) ∈ U i}

/-- An interior cover restricts to an interior cover of every subspace. -/
theorem restrictedCover_condition
    (hU : TopCat.SmallSimplicesCondition (X := X) U) :
    TopCat.SmallSimplicesCondition (X := TopCat.of A) (restrictedCover U A) := by
  constructor
  apply Set.eq_univ_of_forall
  intro a
  have ha : (a.1 : X) ∈ ⋃ i, interior (U i) := by
    rw [hU.iUnion_interior]
    trivial
  rw [Set.mem_iUnion] at ha ⊢
  obtain ⟨i, hai⟩ := ha
  refine ⟨i, ?_⟩
  let V : Set (TopCat.of A) := {b | (b.1 : X) ∈ interior (U i)}
  have hopen : IsOpen V := isOpen_interior.preimage continuous_subtype_val
  have hsub : V ⊆ restrictedCover U A i := by
    intro b hb
    exact @interior_subset X _ (U i) b hb
  exact interior_maximal hsub hopen hai

/-- Inclusion of the subordinate singular subcomplex of `A` into the subordinate singular
subcomplex of `X`. -/
noncomputable def coveredSubspaceMap :
    (TopCat.toSSet.subcomplexOfSets (restrictedCover U A) : SSet) ⟶
      (TopCat.toSSet.subcomplexOfSets U : SSet) :=
  SSet.Subcomplex.lift
    ((TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι ≫
      TopCat.toSSet.map (subIncl A)) (by
        intro j s hs
        obtain ⟨t, rfl⟩ := hs
        have ht := (TopCat.toSSet.mem_subcomplexOfSets_iff
          (U := restrictedCover U A) t.1).1 t.2
        rw [TopCat.toSSet.mem_subcomplexOfSets_iff]
        obtain ⟨i, hi⟩ := ht
        refine ⟨i, ?_⟩
        rintro _ ⟨z, rfl⟩
        exact hi ⟨z, rfl⟩)

@[reassoc (attr := simp)]
theorem coveredSubspaceMap_ι :
    coveredSubspaceMap U A ≫ (TopCat.toSSet.subcomplexOfSets U).ι =
      (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι ≫
        TopCat.toSSet.map (subIncl A) :=
  SSet.Subcomplex.lift_ι _ _

/-- Inclusion of subordinate simplices of `A` is injective in every degree. -/
theorem injective_coveredSubspaceMap_app (n : ℕ) :
    Function.Injective ((coveredSubspaceMap U A).app (op ⦋n⦌)) := by
  intro s t hst
  apply Subtype.ext
  apply injective_toSSet_map_app (subIncl A) Subtype.val_injective n
  exact congrArg Subtype.val hst

instance mono_coveredSubspaceMap : Mono (coveredSubspaceMap U A) := by
  rw [NatTrans.mono_iff_mono_app]
  rintro ⟨⟨n⟩⟩
  rw [CategoryTheory.mono_iff_injective]
  exact injective_coveredSubspaceMap_app U A n

/-- The square formed by the two subordinate inclusions and the ordinary inclusion `A ↪ X`
commutes on singular chains. -/
@[reassoc (attr := simp)]
theorem coveredSubspaceMap_smallIncl :
    SSet.chainComplexMap (coveredSubspaceMap U A) (AddCommGrpCat.of ℤ) ≫
        SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
          (AddCommGrpCat.of ℤ) =
      SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι
          (AddCommGrpCat.of ℤ) ≫ CsingMap (subIncl A) := by
  calc
    _ = SSet.chainComplexMap
        (coveredSubspaceMap U A ≫ (TopCat.toSSet.subcomplexOfSets U).ι)
        (AddCommGrpCat.of ℤ) :=
      (((SSet.chainComplexFunctor AddCommGrpCat.{0}).obj
        (AddCommGrpCat.of ℤ)).map_comp _ _).symm
    _ = SSet.chainComplexMap
        ((TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι ≫
          TopCat.toSSet.map (subIncl A)) (AddCommGrpCat.of ℤ) := by
      rw [coveredSubspaceMap_ι]
    _ = _ := ((SSet.chainComplexFunctor AddCommGrpCat.{0}).obj
      (AddCommGrpCat.of ℤ)).map_comp _ _

/-- Relative chains subordinate to `U`, quotienting by chains of `A` subordinate to the
restricted cover. -/
noncomputable def coveredRelativeComplex : ChainComplex AddCommGrpCat.{0} ℕ :=
  cokernel (SSet.chainComplexMap (coveredSubspaceMap U A) (AddCommGrpCat.of ℤ))

/-- The defining short complex for relative chains subordinate to `U`. -/
noncomputable def coveredRelativeShortComplex :
    ShortComplex (ChainComplex AddCommGrpCat.{0} ℕ) :=
  let f := SSet.chainComplexMap (coveredSubspaceMap U A) (AddCommGrpCat.of ℤ)
  ShortComplex.mk f (cokernel.π f) (cokernel.condition f)

theorem coveredRelativeShortComplex_shortExact :
    (coveredRelativeShortComplex U A).ShortExact where
  exact := ShortComplex.exact_cokernel _
  mono_f := by
    change Mono (SSet.chainComplexMap (coveredSubspaceMap U A) (AddCommGrpCat.of ℤ))
    infer_instance
  epi_g := coequalizer.π_epi

/-- Inclusion of subordinate relative chains into all relative singular chains. -/
noncomputable def coveredRelativeInclusion :
    coveredRelativeComplex U A ⟶ relComplex (subIncl A) :=
  cokernel.map
    (SSet.chainComplexMap (coveredSubspaceMap U A) (AddCommGrpCat.of ℤ))
    (CsingMap (subIncl A))
    (SSet.chainComplexMap
      (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι (AddCommGrpCat.of ℤ))
    (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι (AddCommGrpCat.of ℤ))
    (coveredSubspaceMap_smallIncl U A)

@[reassoc (attr := simp)]
theorem coveredRelative_π_inclusion :
    cokernel.π (SSet.chainComplexMap (coveredSubspaceMap U A)
        (AddCommGrpCat.of ℤ)) ≫ coveredRelativeInclusion U A =
      SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ) ≫ relProj (subIncl A) :=
  cokernel.π_desc _ _ _

/-- The defining map from subordinate to ordinary relative short complexes. -/
noncomputable def coveredRelativeShortComplexMap :
    coveredRelativeShortComplex U A ⟶ relShortComplex (subIncl A) where
  τ₁ := SSet.chainComplexMap
    (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι (AddCommGrpCat.of ℤ)
  τ₂ := SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
    (AddCommGrpCat.of ℤ)
  τ₃ := coveredRelativeInclusion U A
  comm₁₂ := by
    change SSet.chainComplexMap
        (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι
          (AddCommGrpCat.of ℤ) ≫ CsingMap (subIncl A) =
      SSet.chainComplexMap (coveredSubspaceMap U A) (AddCommGrpCat.of ℤ) ≫
        SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
          (AddCommGrpCat.of ℤ)
    exact (coveredSubspaceMap_smallIncl U A).symm
  comm₂₃ := by
    change SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ) ≫ relProj (subIncl A) =
      cokernel.π (SSet.chainComplexMap (coveredSubspaceMap U A)
        (AddCommGrpCat.of ℤ)) ≫ coveredRelativeInclusion U A
    symm
    exact cokernel.π_desc _ _ _

/-- **Relative small-simplices theorem for an induced subspace cover.** Inclusion of subordinate
relative chains is a homology isomorphism whenever the interiors of `U` cover `X`. -/
theorem isIso_homologyMap_coveredRelativeInclusion
    (hU : TopCat.SmallSimplicesCondition (X := X) U) (n : ℕ) :
    IsIso (HomologicalComplex.homologyMap (coveredRelativeInclusion U A) n) := by
  let hUA := restrictedCover_condition U A hU
  letI : QuasiIso (SSet.chainComplexMap
      (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι
      (AddCommGrpCat.of ℤ)) :=
    homotopyEquivalences_le_quasiIso AddCommGrpCat.{0} (ComplexShape.down ℕ) _
      (hUA.homotopyEquivalences (AddCommGrpCat.of ℤ))
  letI : QuasiIso (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
      (AddCommGrpCat.of ℤ)) :=
    homotopyEquivalences_le_quasiIso AddCommGrpCat.{0} (ComplexShape.down ℕ) _
      (hU.homotopyEquivalences (AddCommGrpCat.of ℤ))
  apply HomologicalComplex.HomologySequence.isIso_homologyMap_τ₃
    (coveredRelativeShortComplexMap U A)
    (coveredRelativeShortComplex_shortExact U A)
    (relShortComplex_shortExact (subIncl A))
  · change Epi (HomologicalComplex.homologyMap
      (SSet.chainComplexMap
        (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι
          (AddCommGrpCat.of ℤ)) n)
    haveI : IsIso (HomologicalComplex.homologyMap
        (SSet.chainComplexMap
          (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι
            (AddCommGrpCat.of ℤ)) n) := by
      rw [← quasiIsoAt_iff_isIso_homologyMap]
      exact QuasiIso.quasiIsoAt n
    infer_instance
  · change IsIso (HomologicalComplex.homologyMap
      (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ)) n)
    rw [← quasiIsoAt_iff_isIso_homologyMap]
    exact QuasiIso.quasiIsoAt n
  · intro j _
    change IsIso (HomologicalComplex.homologyMap
      (SSet.chainComplexMap
        (TopCat.toSSet.subcomplexOfSets (restrictedCover U A)).ι
          (AddCommGrpCat.of ℤ)) j)
    rw [← quasiIsoAt_iff_isIso_homologyMap]
    exact QuasiIso.quasiIsoAt j
  · intro j _
    change Mono (HomologicalComplex.homologyMap
      (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
        (AddCommGrpCat.of ℤ)) j)
    haveI : IsIso (HomologicalComplex.homologyMap
        (SSet.chainComplexMap (TopCat.toSSet.subcomplexOfSets U).ι
          (AddCommGrpCat.of ℤ)) j) := by
      rw [← quasiIsoAt_iff_isIso_homologyMap]
      exact QuasiIso.quasiIsoAt j
    infer_instance

end Submission
