/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.Data.Finset.Powerset
import Mathlib.Algebra.BigOperators.Group.Finset.Sigma
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Ring.BooleanRing
import Mathlib.Data.ZMod.Basic

/-!
# Finite ordered simplicial cochains over `F₂`

This file provides a small computational layer for finite simplicial complexes presented by a
finite set of facets.  Coefficients use the Boolean-ring model of `F₂`: addition is xor and
multiplication is conjunction.  A simplex is a finite set of vertices.  Its mod-two boundary is
the sum of its codimension-one faces, so signs disappear.  The vertex order supplies the front and
back faces used by the Alexander--Whitney cup product.

The definitions deliberately stay at the finite-chain level.  They make concrete triangulations
kernel-checkable while keeping the later comparison with singular cohomology as an explicit
separate theorem.

## Main definitions

* `Submission.FiniteOrderedComplex.facesOfCard`: faces of a specified cardinality;
* `Submission.FiniteOrderedComplex.coboundary`: the mod-two simplicial coboundary;
* `Submission.FiniteOrderedComplex.cup`: the ordered Alexander--Whitney cup product;
* `Submission.FiniteOrderedComplex.IsCycle`: the mod-two cycle condition for a finite chain;
* `Submission.FiniteOrderedComplex.IsCoboundaryOn`: coboundaries on the faces of a complex.

## Main result

* `Submission.FiniteOrderedComplex.not_isCoboundaryOn_of_cycle_evaluation_ne_zero`: a cycle with
  nonzero evaluation detects that a cochain is not a coboundary.
-/

namespace Submission

namespace FiniteOrderedComplex

variable {V : Type} [DecidableEq V]

/-- The Boolean-ring coefficient model used for finite computation is exactly `ZMod 2`. -/
def boolEquivZModTwo : Bool ≃+* ZMod 2 where
  toFun b := if b then 1 else 0
  invFun z := decide (z = 1)
  left_inv b := by cases b <;> decide
  right_inv z := by fin_cases z <;> decide
  map_add' b c := by cases b <;> cases c <;> decide
  map_mul' b c := by cases b <;> cases c <;> decide

/-- A mod-two cochain on finite vertex sets.  Only its values on faces of the required cardinality
are relevant. -/
abbrev Cochain (V : Type) [DecidableEq V] := Finset V → Bool

/-- All faces of cardinality `k` generated by a finite collection of facets. -/
def facesOfCard (facets : Finset (Finset V)) (k : ℕ) : Finset (Finset V) :=
  facets.biUnion fun σ ↦ σ.powersetCard k

/-- The mod-two coboundary evaluated on a simplex.  The parameter `k` is the cardinality of the
faces on which the input cochain is evaluated. -/
def coboundary (k : ℕ) (c : Cochain V) : Cochain V :=
  fun σ ↦ ∑ τ ∈ σ.powersetCard k, c τ

/-- A degree-`n` cochain is a cocycle on `facets` when its coboundary vanishes on every generated
face of cardinality `n + 2`. -/
def IsCocycle (facets : Finset (Finset V)) (n : ℕ) (c : Cochain V) : Prop :=
  (facesOfCard facets (n + 2)).filter
      (fun σ ↦ coboundary (n + 1) c σ ≠ 0) = ∅

/-- Pointwise characterization of the executable cocycle check. -/
theorem isCocycle_iff {facets : Finset (Finset V)} {n : ℕ} {c : Cochain V} :
    IsCocycle facets n c ↔
      ∀ σ ∈ facesOfCard facets (n + 2), coboundary (n + 1) c σ = 0 := by
  simp [IsCocycle]

/-- Evaluation of a cochain on a finite mod-two chain. -/
def evaluate (chain : Finset (Finset V)) (c : Cochain V) : Bool :=
  ∑ σ ∈ chain, c σ

/-- The coefficient of a face `τ` in the boundary of `chain`. -/
def boundaryCoefficient (k : ℕ) (chain : Finset (Finset V)) (τ : Finset V) : Bool :=
  ∑ σ ∈ chain, if τ ∈ σ.powersetCard k then 1 else 0

/-- A finite chain is a mod-two cycle when every generated boundary face has coefficient zero.
The parameter `k` is the cardinality of those boundary faces. -/
def IsCycle (k : ℕ) (chain : Finset (Finset V)) : Prop :=
  (facesOfCard chain k).filter
      (fun τ ↦ boundaryCoefficient k chain τ ≠ 0) = ∅

/-- Pointwise characterization of the executable cycle check. -/
theorem isCycle_iff {k : ℕ} {chain : Finset (Finset V)} :
    IsCycle k chain ↔
      ∀ τ ∈ facesOfCard chain k, boundaryCoefficient k chain τ = 0 := by
  simp [IsCycle]

/-- A cochain is a coboundary on the degree-`n` faces generated by `facets`. -/
def IsCoboundaryOn (facets : Finset (Finset V)) (n : ℕ) (c : Cochain V) : Prop :=
  ∃ b : Cochain V,
    ∀ σ ∈ facesOfCard facets (n + 1), c σ = coboundary n b σ

section Stokes

/-- Finite mod-two Stokes theorem: a coboundary evaluates to zero on a cycle. -/
theorem evaluate_coboundary_eq_zero {k : ℕ} {chain : Finset (Finset V)}
    (hcycle : IsCycle k chain) (b : Cochain V) :
    evaluate chain (coboundary k b) = 0 := by
  classical
  rw [evaluate]
  change (∑ σ ∈ chain, ∑ τ ∈ σ.powersetCard k, b τ) = 0
  calc
    (∑ σ ∈ chain, ∑ τ ∈ σ.powersetCard k, b τ) =
        ∑ σ ∈ chain, ∑ τ ∈ facesOfCard chain k,
          if τ ∈ σ.powersetCard k then b τ else 0 := by
      apply Finset.sum_congr rfl
      intro σ hσ
      have hsubset : σ.powersetCard k ⊆ facesOfCard chain k := by
        intro τ hτ
        exact Finset.mem_biUnion.2 ⟨σ, hσ, hτ⟩
      symm
      simp only [Finset.sum_ite, Finset.sum_const_zero, add_zero,
        Finset.filter_mem_eq_inter, Finset.inter_eq_right.2 hsubset]
    _ = ∑ τ ∈ facesOfCard chain k, ∑ σ ∈ chain,
          if τ ∈ σ.powersetCard k then b τ else 0 := by
      rw [Finset.sum_comm]
    _ = ∑ τ ∈ facesOfCard chain k, boundaryCoefficient k chain τ * b τ := by
      apply Finset.sum_congr rfl
      intro τ _
      rw [boundaryCoefficient, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro σ _
      split <;> simp_all
    _ = 0 := by
      apply Finset.sum_eq_zero
      intro τ hτ
      rw [(isCycle_iff.mp hcycle) τ hτ, zero_mul]

/-- A cycle on which `c` evaluates nontrivially proves that `c` is not a coboundary on any
complex containing that cycle. -/
theorem not_isCoboundaryOn_of_cycle_evaluation_ne_zero
    {facets chain : Finset (Finset V)} {n : ℕ} {c : Cochain V}
    (hfaces : chain ⊆ facesOfCard facets (n + 1))
    (hcycle : IsCycle n chain)
    (heval : evaluate chain c ≠ 0) :
    ¬ IsCoboundaryOn facets n c := by
  rintro ⟨b, hb⟩
  apply heval
  calc
    evaluate chain c = evaluate chain (coboundary n b) := by
      rw [evaluate, evaluate]
      apply Finset.sum_congr rfl
      intro σ hσ
      exact hb σ (hfaces hσ)
    _ = 0 := evaluate_coboundary_eq_zero hcycle b

end Stokes

section Cup

variable [LinearOrder V]

/-- The first `p + 1` vertices of a simplex in the chosen vertex order.  Membership is expressed
by counting strictly smaller vertices, which keeps concrete finite computations reducible. -/
def frontFace (p : ℕ) (σ : Finset V) : Finset V :=
  σ.filter fun v ↦ (σ.filter fun w ↦ w < v).card ≤ p

/-- The vertices starting at position `p` in the chosen vertex order. -/
def backFace (p : ℕ) (σ : Finset V) : Finset V :=
  σ.filter fun v ↦ p ≤ (σ.filter fun w ↦ w < v).card

/-- The Alexander--Whitney cup product on ordered finite simplicial cochains.  On a simplex of
cardinality `p + q + 1`, `frontFace p` has cardinality `p + 1` and `backFace p` has cardinality
`q + 1`. -/
def cup (p : ℕ) (c d : Cochain V) : Cochain V :=
  fun σ ↦ c (frontFace p σ) * d (backFace p σ)

end Cup

end FiniteOrderedComplex

end Submission
