/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.AlgebraicTopology.SimplicialSet.NerveNondegenerate
import Mathlib.AlgebraicTopology.SimplicialSet.Subcomplex
import Mathlib.Data.Finset.Sort
import Submission.Cohomology.Cup
import Submission.Cohomology.FiniteOrderedComplex

/-!
# A simplicial-set model of a finite ordered simplicial complex

A finite ordered simplicial complex, presented by its facets, embeds naturally in the nerve of
the linearly ordered vertex set.  Its simplices are weakly increasing strings of vertices whose
images lie in one facet.  Degenerate strings are retained, as required for a simplicial set.

This file constructs that simplicial set and compares its canonical nondegenerate simplices with
the finite-set representation used in `Submission.Cohomology.FiniteOrderedComplex`.  It is the
first comparison layer between the kernel-computable finite certificate and the general
simplicial cochain/cup-product theory.

## Main definitions

* `Submission.FiniteOrderedComplex.orderedSubcomplex`: the subcomplex of the nerve generated by
  the listed facets;
* `Submission.FiniteOrderedComplex.orderedSSet`: its underlying simplicial set;
* `Submission.FiniteOrderedComplex.simplexVertices`: the vertex image of a simplex;
* `Submission.FiniteOrderedComplex.canonicalSimplex`: the increasing simplex associated to a
  finite face;
* `Submission.FiniteOrderedComplex.toSSetCochain`: transport of a finite Boolean cochain to a
  simplicial `ZMod 2` cochain by taking vertex images.
-/

namespace Submission

open CategoryTheory Simplicial

namespace FiniteOrderedComplex

variable {V : Type} [LinearOrder V]

/-- A finite set of vertices is contained in one of the listed facets. -/
def IsFace (facets : Finset (Finset V)) (σ : Finset V) : Prop :=
  ∃ facet ∈ facets, σ ⊆ facet

/-- Every generated finite face is contained in one of the listed facets. -/
theorem isFace_of_mem_facesOfCard {facets : Finset (Finset V)} {σ : Finset V} {k : ℕ}
    (hσ : σ ∈ facesOfCard facets k) : IsFace facets σ := by
  rcases Finset.mem_biUnion.mp hσ with ⟨facet, hfacet, hσ⟩
  exact ⟨facet, hfacet, (Finset.mem_powersetCard.mp hσ).1⟩

/-- A face generated in cardinality `k` has cardinality `k`. -/
theorem card_eq_of_mem_facesOfCard {facets : Finset (Finset V)} {σ : Finset V} {k : ℕ}
    (hσ : σ ∈ facesOfCard facets k) : σ.card = k := by
  rcases Finset.mem_biUnion.mp hσ with ⟨_, _, hσ⟩
  exact (Finset.mem_powersetCard.mp hσ).2

/-- A contained finite set of the prescribed cardinality is one of the generated faces. -/
theorem mem_facesOfCard_of_isFace {facets : Finset (Finset V)} {σ : Finset V} {k : ℕ}
    (hface : IsFace facets σ) (hcard : σ.card = k) : σ ∈ facesOfCard facets k := by
  rcases hface with ⟨facet, hfacet, hsubset⟩
  exact Finset.mem_biUnion.mpr
    ⟨facet, hfacet, Finset.mem_powersetCard.mpr ⟨hsubset, hcard⟩⟩

/-- The ordered simplicial complex generated by `facets`, as a subcomplex of the nerve of `V`.
An `n`-simplex is a weakly increasing string of `n + 1` vertices contained in one facet. -/
def orderedSubcomplex (facets : Finset (Finset V)) : (CategoryTheory.nerve V).Subcomplex where
  obj _ := {x | ∃ facet ∈ facets, ∀ i, x.obj i ∈ facet}
  map _ x hx := by
    rcases hx with ⟨facet, hfacet, hx⟩
    exact ⟨facet, hfacet, fun i ↦ hx _⟩

/-- The increasing nerve simplex associated to a finite set of `d + 1` vertices. -/
def ambientCanonicalSimplex {d : ℕ} (σ : Finset V) (hcard : σ.card = d + 1) :
    (CategoryTheory.nerve V) _⦋d⦌ :=
  (σ.orderEmbOfFin hcard).monotone.functor

/-- A monotone simplex whose vertices lie in `σ` factors through the canonical simplex of `σ`.
This is the index map of that factorization. -/
def simplexIndexHom {n d : ℕ} (σ : Finset V) (hcard : σ.card = d + 1)
    (x : (CategoryTheory.nerve V) _⦋n⦌) (hx : ∀ i, x.obj i ∈ σ) :
    (⦋n⦌ : SimplexCategory) ⟶ ⦋d⦌ :=
  SimplexCategory.mkHom
    ⟨fun i ↦ (σ.orderIsoOfFin hcard).symm ⟨x.obj i, hx i⟩,
      fun _ _ hij ↦ (σ.orderIsoOfFin hcard).symm.monotone (x.monotone hij)⟩

/-- Restricting the canonical simplex along its index map recovers the original contained
simplex. -/
@[simp]
theorem nerve_map_simplexIndexHom_ambientCanonicalSimplex {n d : ℕ}
    (σ : Finset V) (hcard : σ.card = d + 1)
    (x : (CategoryTheory.nerve V) _⦋n⦌) (hx : ∀ i, x.obj i ∈ σ) :
    (CategoryTheory.nerve V).map (simplexIndexHom σ hcard x hx).op
        (ambientCanonicalSimplex σ hcard) = x := by
  apply CategoryTheory.nerve.ext_of_isThin
  funext i
  change σ.orderEmbOfFin hcard
      ((σ.orderIsoOfFin hcard).symm ⟨x.obj i, hx i⟩) = x.obj i
  exact congrArg Subtype.val ((σ.orderIsoOfFin hcard).apply_symm_apply ⟨x.obj i, hx i⟩)

/-- The ambient nerve subcomplex generated by canonical simplices of a pure family of facets. -/
def facetsSubcomplex (facets : Finset (Finset V)) (d : ℕ)
    (hpure : ∀ σ ∈ facets, σ.card = d + 1) : (CategoryTheory.nerve V).Subcomplex :=
  ⨆ facet : ↥facets,
    SSet.Subcomplex.ofSimplex (ambientCanonicalSimplex facet.1 (hpure facet.1 facet.2))

/-- For a pure finite complex, the vertex-containment definition is exactly the subcomplex
generated by its canonical facet simplices.  Consequently its future geometric realization is
assembled from precisely the listed top-dimensional simplices and their faces. -/
theorem orderedSubcomplex_eq_facetsSubcomplex (facets : Finset (Finset V)) (d : ℕ)
    (hpure : ∀ σ ∈ facets, σ.card = d + 1) :
    orderedSubcomplex facets = facetsSubcomplex facets d hpure := by
  ext ⟨⟨n⟩⟩ x
  constructor
  · rintro ⟨facet, hfacet, hx⟩
    simp only [facetsSubcomplex, Subfunctor.iSup_obj, Set.mem_iUnion]
    refine ⟨⟨facet, hfacet⟩, ?_⟩
    rw [SSet.Subcomplex.mem_ofSimplex_obj_iff]
    exact ⟨simplexIndexHom facet (hpure facet hfacet) x hx,
      nerve_map_simplexIndexHom_ambientCanonicalSimplex facet (hpure facet hfacet) x hx⟩
  · intro hx
    simp only [facetsSubcomplex, Subfunctor.iSup_obj, Set.mem_iUnion] at hx
    rcases hx with ⟨⟨facet, hfacet⟩, hx⟩
    have hle : SSet.Subcomplex.ofSimplex
        (ambientCanonicalSimplex facet (hpure facet hfacet)) ≤ orderedSubcomplex facets := by
      rw [SSet.Subcomplex.ofSimplex_le_iff]
      exact ⟨facet, hfacet,
        fun i ↦ Finset.orderEmbOfFin_mem facet (hpure facet hfacet) i⟩
    exact hle _ hx

/-- The simplicial set underlying `orderedSubcomplex`. -/
abbrev orderedSSet (facets : Finset (Finset V)) : SSet := orderedSubcomplex facets

/-- The finite image of the vertices of an ordered simplex.  Degenerate vertices are counted
only once. -/
def simplexVertices {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) : Finset V :=
  Finset.univ.image fun i : Fin (n + 1) ↦ x.1.obj i

/-- The vertex image of every simplex is a face of the finite complex. -/
theorem simplexVertices_isFace {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) : IsFace facets (simplexVertices x) := by
  rcases x.2 with ⟨facet, hfacet, hx⟩
  refine ⟨facet, hfacet, ?_⟩
  intro v hv
  rcases Finset.mem_image.mp hv with ⟨i, _, rfl⟩
  exact hx i

/-- The rank of the `i`th vertex in the increasing enumeration of a finite set is `i`. -/
theorem card_filter_lt_orderEmbOfFin {n : ℕ} (σ : Finset V) (hcard : σ.card = n + 1)
    (i : Fin (n + 1)) :
    (σ.filter fun w ↦ w < σ.orderEmbOfFin hcard i).card = i := by
  let e := σ.orderEmbOfFin hcard
  have hfilter : σ.filter (fun w ↦ w < e i) =
      (Finset.univ.filter fun j : Fin (n + 1) ↦ j < i).image e := by
    ext v
    constructor
    · intro hv
      rw [Finset.mem_filter] at hv
      have hvimage : v ∈ Finset.univ.image e := by
        rw [Finset.image_orderEmbOfFin_univ σ hcard]
        exact hv.1
      rcases Finset.mem_image.mp hvimage with ⟨j, _, rfl⟩
      exact Finset.mem_image.mpr ⟨j, by simp [e.lt_iff_lt.mp hv.2], rfl⟩
    · intro hv
      rcases Finset.mem_image.mp hv with ⟨j, hj, rfl⟩
      rw [Finset.mem_filter]
      exact ⟨Finset.orderEmbOfFin_mem σ hcard j,
        e.lt_iff_lt.mpr (by simpa using (Finset.mem_filter.mp hj).2)⟩
  rw [hfilter, Finset.card_image_of_injective _ e.injective]
  change (Finset.univ.filter fun j : Fin (n + 1) ↦ (j : ℕ) < (i : ℕ)).card = (i : ℕ)
  rw [Fin.card_filter_val_lt, Nat.min_eq_right (Nat.le_of_lt i.isLt)]

/-- The finite front face is the image of the initial segment of the increasing enumeration. -/
theorem frontFace_eq_image_orderEmbOfFin {p q : ℕ} (σ : Finset V)
    (hcard : σ.card = p + q + 1) :
    frontFace p σ = Finset.univ.image fun i : Fin (p + 1) ↦
      σ.orderEmbOfFin hcard ⟨i, by omega⟩ := by
  ext v
  constructor
  · intro hv
    rw [frontFace, Finset.mem_filter] at hv
    have hvimage : v ∈ Finset.univ.image (σ.orderEmbOfFin hcard) := by
      rw [Finset.image_orderEmbOfFin_univ σ hcard]
      exact hv.1
    rcases Finset.mem_image.mp hvimage with ⟨i, _, rfl⟩
    rw [card_filter_lt_orderEmbOfFin σ hcard] at hv
    refine Finset.mem_image.mpr ⟨⟨i, by omega⟩, Finset.mem_univ _, ?_⟩
    congr
  · intro hv
    rcases Finset.mem_image.mp hv with ⟨i, _, rfl⟩
    rw [frontFace, Finset.mem_filter, card_filter_lt_orderEmbOfFin σ hcard]
    constructor
    · exact Finset.orderEmbOfFin_mem σ hcard _
    · change (i : ℕ) ≤ p
      omega

/-- The finite back face is the image of the final segment of the increasing enumeration. -/
theorem backFace_eq_image_orderEmbOfFin {p q : ℕ} (σ : Finset V)
    (hcard : σ.card = p + q + 1) :
    backFace p σ = Finset.univ.image fun i : Fin (q + 1) ↦
      σ.orderEmbOfFin hcard ⟨p + i, by omega⟩ := by
  ext v
  constructor
  · intro hv
    rw [backFace, Finset.mem_filter] at hv
    have hvimage : v ∈ Finset.univ.image (σ.orderEmbOfFin hcard) := by
      rw [Finset.image_orderEmbOfFin_univ σ hcard]
      exact hv.1
    rcases Finset.mem_image.mp hvimage with ⟨i, _, rfl⟩
    rw [card_filter_lt_orderEmbOfFin σ hcard] at hv
    refine Finset.mem_image.mpr ⟨⟨i - p, by omega⟩, Finset.mem_univ _, ?_⟩
    congr
    change p + ((i : ℕ) - p) = (i : ℕ)
    omega
  · intro hv
    rcases Finset.mem_image.mp hv with ⟨i, _, rfl⟩
    rw [backFace, Finset.mem_filter, card_filter_lt_orderEmbOfFin σ hcard]
    constructor
    · exact Finset.orderEmbOfFin_mem σ hcard _
    · change p ≤ p + (i : ℕ)
      omega

/-- The increasing `n`-simplex whose vertex set is a face of cardinality `n + 1`. -/
def canonicalSimplex {facets : Finset (Finset V)} {n : ℕ} (σ : Finset V)
    (hcard : σ.card = n + 1) (hface : IsFace facets σ) : orderedSSet facets _⦋n⦌ := by
  refine ⟨(σ.orderEmbOfFin hcard).monotone.functor, ?_⟩
  rcases hface with ⟨facet, hfacet, hsubset⟩
  exact ⟨facet, hfacet, fun i ↦ hsubset (Finset.orderEmbOfFin_mem σ hcard i)⟩

/-- A generated face, supplied in its native finite representation, determines a canonical
simplex without any additional containment or cardinality evidence. -/
def canonicalFaceSimplex {facets : Finset (Finset V)} {n : ℕ} (σ : Finset V)
    (hσ : σ ∈ facesOfCard facets (n + 1)) : orderedSSet facets _⦋n⦌ :=
  canonicalSimplex σ (card_eq_of_mem_facesOfCard hσ) (isFace_of_mem_facesOfCard hσ)

/-- Canonical increasing simplices are nondegenerate. -/
theorem canonicalSimplex_mem_nonDegenerate {facets : Finset (Finset V)} {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    canonicalSimplex σ hcard hface ∈ (orderedSSet facets).nonDegenerate n := by
  refine (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets)
    (canonicalSimplex σ hcard hface)).2 ?_
  rw [PartialOrder.mem_nerve_nonDegenerate_iff_strictMono]
  exact (σ.orderEmbOfFin hcard).strictMono

/-- A nondegenerate `n`-simplex has exactly `n + 1` distinct vertices. -/
theorem simplexVertices_card_of_mem_nonDegenerate {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) (hx : x ∈ (orderedSSet facets).nonDegenerate n) :
    (simplexVertices x).card = n + 1 := by
  have hx' : x.1 ∈ (CategoryTheory.nerve V).nonDegenerate n :=
    (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets) x).1 hx
  have hstrict : StrictMono x.1.obj :=
    (PartialOrder.mem_nerve_nonDegenerate_iff_strictMono x.1).1 hx'
  rw [simplexVertices, Finset.card_image_of_injective _ hstrict.injective,
    Finset.card_univ, Fintype.card_fin]

/-- An ordered simplex is nondegenerate exactly when all `n + 1` entries are distinct. -/
theorem mem_nonDegenerate_iff_simplexVertices_card_eq {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) :
    x ∈ (orderedSSet facets).nonDegenerate n ↔ (simplexVertices x).card = n + 1 := by
  constructor
  · exact simplexVertices_card_of_mem_nonDegenerate x
  · intro hcard
    refine (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets) x).2 ?_
    rw [PartialOrder.mem_nerve_nonDegenerate_iff_injective]
    intro i j hij
    have himage : ((Finset.univ : Finset (Fin (n + 1))).image x.1.obj).card =
        (Finset.univ : Finset (Fin (n + 1))).card := by
      simpa [simplexVertices] using hcard
    exact (Finset.card_image_iff.mp himage) (Finset.mem_univ i) (Finset.mem_univ j) hij

/-- Re-enumerating the vertex set of a nondegenerate ordered simplex returns that simplex. -/
theorem canonicalSimplex_simplexVertices {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) (hx : x ∈ (orderedSSet facets).nonDegenerate n) :
    canonicalSimplex (simplexVertices x)
      (simplexVertices_card_of_mem_nonDegenerate x hx) (simplexVertices_isFace x) = x := by
  have hx' : x.1 ∈ (CategoryTheory.nerve V).nonDegenerate n :=
    (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets) x).1 hx
  have hstrict : StrictMono x.1.obj :=
    (PartialOrder.mem_nerve_nonDegenerate_iff_strictMono x.1).1 hx'
  apply Subtype.ext
  apply CategoryTheory.nerve.ext_of_isThin
  funext i
  change (simplexVertices x).orderEmbOfFin
      (simplexVertices_card_of_mem_nonDegenerate x hx) i = x.1.obj i
  exact congrFun (Finset.orderEmbOfFin_unique
    (simplexVertices_card_of_mem_nonDegenerate x hx)
    (fun j ↦ Finset.mem_image.mpr ⟨j, Finset.mem_univ _, rfl⟩) hstrict) i |>.symm

/-- Finite faces of cardinality `n + 1` are exactly the nondegenerate `n`-simplices of the
ordered simplicial set. -/
def faceEquivNonDegenerate (facets : Finset (Finset V)) (n : ℕ) :
    {σ : Finset V // IsFace facets σ ∧ σ.card = n + 1} ≃
      (orderedSSet facets).nonDegenerate n where
  toFun σ := ⟨canonicalSimplex σ.1 σ.2.2 σ.2.1,
    canonicalSimplex_mem_nonDegenerate σ.1 σ.2.2 σ.2.1⟩
  invFun x := ⟨simplexVertices x.1, simplexVertices_isFace x.1,
    simplexVertices_card_of_mem_nonDegenerate x.1 x.2⟩
  left_inv σ := by
    apply Subtype.ext
    exact Finset.image_orderEmbOfFin_univ σ.1 σ.2.2
  right_inv x := by
    apply Subtype.ext
    exact canonicalSimplex_simplexVertices x.1 x.2

/-- The canonical increasing simplex recovers its original finite vertex set. -/
@[simp]
theorem simplexVertices_canonicalSimplex {facets : Finset (Finset V)} {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    simplexVertices (canonicalSimplex σ hcard hface) = σ := by
  exact Finset.image_orderEmbOfFin_univ σ hcard

/-- Taking a simplicial front face of a canonical simplex agrees with the finite front face. -/
@[simp]
theorem simplexVertices_front_canonicalSimplex {facets : Finset (Finset V)} {p q : ℕ}
    (σ : Finset V) (hcard : σ.card = p + q + 1) (hface : IsFace facets σ) :
    simplexVertices
        (SSet.front (orderedSSet facets) (by omega : p ≤ p + q)
          (canonicalSimplex σ hcard hface)) = frontFace p σ := by
  rw [frontFace_eq_image_orderEmbOfFin σ hcard]
  rfl

/-- Taking a simplicial back face of a canonical simplex agrees with the finite back face. -/
@[simp]
theorem simplexVertices_back_canonicalSimplex {facets : Finset (Finset V)} {p q : ℕ}
    (σ : Finset V) (hcard : σ.card = p + q + 1) (hface : IsFace facets σ) :
    simplexVertices
        (SSet.back (orderedSSet facets) (by omega : q ≤ p + q)
          (canonicalSimplex σ hcard hface)) = backFace p σ := by
  rw [backFace_eq_image_orderEmbOfFin σ hcard]
  change Finset.univ.image (fun i : Fin (q + 1) ↦
      σ.orderEmbOfFin hcard ⟨p + q - q + i, by omega⟩) =
    Finset.univ.image (fun i : Fin (q + 1) ↦
      σ.orderEmbOfFin hcard ⟨p + i, by omega⟩)
  apply Finset.image_congr
  intro i _
  apply congrArg (σ.orderEmbOfFin hcard)
  apply Fin.ext
  dsimp
  omega

/-- The codimension-one subsets of an ordered simplex are exactly the sets obtained by erasing
one vertex from its increasing enumeration. -/
theorem powersetCard_eq_image_erase_orderEmbOfFin {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 2) :
    σ.powersetCard (n + 1) = Finset.univ.image fun i : Fin (n + 2) ↦
      σ.erase (σ.orderEmbOfFin hcard i) := by
  ext τ
  constructor
  · intro hτ
    rcases Finset.mem_powersetCard.mp hτ with ⟨hsubset, hτcard⟩
    obtain ⟨v, hvσ, hvτ⟩ := Finset.exists_mem_notMem_of_card_lt_card (s := τ) (t := σ)
      (by omega)
    have hτerase : τ = σ.erase v := by
      apply Finset.eq_of_subset_of_card_le
      · intro w hw
        exact Finset.mem_erase.mpr ⟨fun hwv ↦ hvτ (hwv ▸ hw), hsubset hw⟩
      · rw [hτcard, Finset.card_erase_of_mem hvσ, hcard]
        omega
    have hvimage : v ∈ Finset.univ.image (σ.orderEmbOfFin hcard) := by
      rw [Finset.image_orderEmbOfFin_univ σ hcard]
      exact hvσ
    rcases Finset.mem_image.mp hvimage with ⟨i, _, rfl⟩
    exact Finset.mem_image.mpr ⟨i, Finset.mem_univ _, hτerase.symm⟩
  · intro hτ
    rcases Finset.mem_image.mp hτ with ⟨i, _, rfl⟩
    rw [Finset.mem_powersetCard]
    exact ⟨Finset.erase_subset _ _, by
      rw [Finset.card_erase_of_mem (Finset.orderEmbOfFin_mem σ hcard i), hcard]
      omega⟩

/-- Erasing distinct positions from the increasing enumeration gives distinct codimension-one
faces. -/
theorem erase_orderEmbOfFin_injective {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 2) :
    Function.Injective (fun i : Fin (n + 2) ↦ σ.erase (σ.orderEmbOfFin hcard i)) := by
  intro i j hij
  apply (σ.orderEmbOfFin hcard).injective
  by_contra hne
  have hmem : σ.orderEmbOfFin hcard i ∈ σ.erase (σ.orderEmbOfFin hcard j) :=
    Finset.mem_erase.mpr ⟨hne, Finset.orderEmbOfFin_mem σ hcard i⟩
  change σ.erase (σ.orderEmbOfFin hcard i) =
    σ.erase (σ.orderEmbOfFin hcard j) at hij
  rw [← hij] at hmem
  exact (Finset.notMem_erase _ _) hmem

/-- A simplicial face of a canonical simplex has the vertex set obtained by erasing the
corresponding ordered vertex. -/
@[simp]
theorem simplexVertices_face_canonicalSimplex {facets : Finset (Finset V)} {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 2) (hface : IsFace facets σ)
    (i : Fin (n + 2)) :
    simplexVertices
        (SSet.face (orderedSSet facets) i (canonicalSimplex σ hcard hface)) =
      σ.erase (σ.orderEmbOfFin hcard i) := by
  change Finset.univ.image
      ((σ.orderEmbOfFin hcard : Fin (n + 2) → V) ∘ i.succAbove) =
    σ.erase (σ.orderEmbOfFin hcard i)
  rw [← Finset.image_image, Fin.image_succAbove_univ,
    show ({i}ᶜ : Finset (Fin (n + 2))) = Finset.univ.erase i by ext; simp,
    Finset.image_erase (σ.orderEmbOfFin hcard).injective,
    Finset.image_orderEmbOfFin_univ σ hcard]

/-- Transport a finite Boolean cochain to a simplicial `ZMod 2` cochain by evaluating it on the
vertex image of each simplex. -/
def toSSetCochain (facets : Finset (Finset V)) (n : ℕ) (c : Cochain V) :
    Submission.Cochain (orderedSSet facets) (ZMod 2) n :=
  fun x ↦ boolEquivZModTwo (c (simplexVertices x))

/-- Restrict a simplicial `ZMod 2` cochain to canonical finite faces.  Values away from faces of
the prescribed cardinality are set to zero because they play no role in the finite complex. -/
noncomputable def fromSSetCochain (facets : Finset (Finset V)) (n : ℕ)
    (f : Submission.Cochain (orderedSSet facets) (ZMod 2) n) : Cochain V :=
  by
    classical
    exact fun σ ↦
      if hcard : σ.card = n + 1 then
        if hface : IsFace facets σ then
          boolEquivZModTwo.symm (f (canonicalSimplex σ hcard hface))
        else 0
      else 0

/-- Restriction to a canonical finite face recovers the value of the simplicial cochain. -/
@[simp]
theorem fromSSetCochain_apply_of_card_isFace {facets : Finset (Finset V)} {n : ℕ}
    (f : Submission.Cochain (orderedSSet facets) (ZMod 2) n)
    (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    fromSSetCochain facets n f σ =
      boolEquivZModTwo.symm (f (canonicalSimplex σ hcard hface)) := by
  simp only [fromSSetCochain, hcard, hface, dite_true]

/-- Transported cochains have the expected value on canonical increasing simplices. -/
@[simp]
theorem toSSetCochain_canonicalSimplex {facets : Finset (Finset V)} {n : ℕ}
    (c : Cochain V) (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    toSSetCochain facets n c (canonicalSimplex σ hcard hface) = boolEquivZModTwo (c σ) := by
  simp [toSSetCochain]

/-- If a finite degree-`n` cochain vanishes away from sets of cardinality `n + 1`, then its
transport vanishes on all degenerate simplices. -/
theorem toSSetCochain_eq_zero_of_degenerate {facets : Finset (Finset V)} {n : ℕ}
    (c : Cochain V) (hc : ∀ σ, σ.card ≠ n + 1 → c σ = 0)
    (x : orderedSSet facets _⦋n⦌) (hx : x ∈ (orderedSSet facets).degenerate n) :
    toSSetCochain facets n c x = 0 := by
  have hcard : (simplexVertices x).card ≠ n + 1 := by
    intro hcard
    exact (SSet.mem_degenerate_iff_notMem_nonDegenerate (orderedSSet facets) x).1 hx
      ((mem_nonDegenerate_iff_simplexVertices_card_eq x).2 hcard)
  simp [toSSetCochain, hc _ hcard]

/-- On canonical simplices, the general simplicial coboundary agrees with the executable finite
coboundary after identifying `Bool` with `ZMod 2`. -/
theorem coboundary_toSSetCochain_canonicalSimplex
    {facets : Finset (Finset V)} {n : ℕ} (c : Cochain V)
    (σ : Finset V) (hcard : σ.card = n + 2) (hface : IsFace facets σ) :
    Submission.coboundary (orderedSSet facets) (ZMod 2) n
        (toSSetCochain facets n c) (canonicalSimplex σ hcard hface) =
      boolEquivZModTwo (FiniteOrderedComplex.coboundary (n + 1) c σ) := by
  rw [Submission.coboundary_apply]
  simp_rw [show (-1 : ZMod 2) = 1 by decide, one_pow, one_mul, toSSetCochain,
    simplexVertices_face_canonicalSimplex]
  change (∑ i : Fin (n + 2), boolEquivZModTwo
      (c (σ.erase (σ.orderEmbOfFin hcard i)))) =
    boolEquivZModTwo (∑ τ ∈ σ.powersetCard (n + 1), c τ)
  rw [map_sum, powersetCard_eq_image_erase_orderEmbOfFin σ hcard,
    Finset.sum_image (erase_orderEmbOfFin_injective σ hcard).injOn]

/-- On a face of a canonical simplex, restricting an arbitrary simplicial cochain and then
identifying `Bool` with `ZMod 2` recovers the original simplicial value. -/
theorem boolEquivZModTwo_fromSSetCochain_erase {facets : Finset (Finset V)} {n : ℕ}
    (f : Submission.Cochain (orderedSSet facets) (ZMod 2) n)
    (σ : Finset V) (hcard : σ.card = n + 2) (hface : IsFace facets σ)
    (i : Fin (n + 2)) :
    boolEquivZModTwo
        (fromSSetCochain facets n f (σ.erase (σ.orderEmbOfFin hcard i))) =
      f (SSet.face (orderedSSet facets) i (canonicalSimplex σ hcard hface)) := by
  have hmem : σ.orderEmbOfFin hcard i ∈ σ :=
    Finset.orderEmbOfFin_mem σ hcard i
  have herasecard : (σ.erase (σ.orderEmbOfFin hcard i)).card = n + 1 := by
    rw [Finset.card_erase_of_mem hmem, hcard]
    omega
  have hfaceErase : IsFace facets (σ.erase (σ.orderEmbOfFin hcard i)) := by
    rcases hface with ⟨facet, hfacet, hsubset⟩
    exact ⟨facet, hfacet, (Finset.erase_subset _ σ).trans hsubset⟩
  rw [fromSSetCochain_apply_of_card_isFace f _ herasecard hfaceErase,
    RingEquiv.apply_symm_apply]
  let x := SSet.face (orderedSSet facets) i (canonicalSimplex σ hcard hface)
  have hxvertices : simplexVertices x = σ.erase (σ.orderEmbOfFin hcard i) := by
    exact simplexVertices_face_canonicalSimplex σ hcard hface i
  have hxnondegenerate : x ∈ (orderedSSet facets).nonDegenerate n :=
    (mem_nonDegenerate_iff_simplexVertices_card_eq x).2 (by
      rw [hxvertices]
      exact herasecard)
  have hxcanonical := canonicalSimplex_simplexVertices x hxnondegenerate
  simpa only [hxvertices] using congrArg f hxcanonical

/-- Restriction of an arbitrary simplicial cochain commutes with coboundary on canonical
simplices, after identifying the Boolean finite coefficient ring with `ZMod 2`. -/
theorem boolEquivZModTwo_coboundary_fromSSetCochain
    {facets : Finset (Finset V)} {n : ℕ}
    (f : Submission.Cochain (orderedSSet facets) (ZMod 2) n)
    (σ : Finset V) (hcard : σ.card = n + 2) (hface : IsFace facets σ) :
    boolEquivZModTwo
        (FiniteOrderedComplex.coboundary (n + 1) (fromSSetCochain facets n f) σ) =
      Submission.coboundary (orderedSSet facets) (ZMod 2) n f
        (canonicalSimplex σ hcard hface) := by
  rw [Submission.coboundary_apply]
  simp_rw [show (-1 : ZMod 2) = 1 by decide, one_pow, one_mul]
  change boolEquivZModTwo
      (∑ τ ∈ σ.powersetCard (n + 1), fromSSetCochain facets n f τ) =
    ∑ i : Fin (n + 2),
      f (SSet.face (orderedSSet facets) i (canonicalSimplex σ hcard hface))
  rw [map_sum, powersetCard_eq_image_erase_orderEmbOfFin σ hcard,
    Finset.sum_image (erase_orderEmbOfFin_injective σ hcard).injOn]
  simp_rw [boolEquivZModTwo_fromSSetCochain_erase f σ hcard hface]

/-- If a simplicial cochain agreeing with a finite cochain on canonical faces is a simplicial
coboundary, then the finite cochain is a coboundary on the finite complex. -/
theorem isCoboundaryOn_of_eq_sSet_coboundary
    {facets : Finset (Finset V)} {n : ℕ} (c : Cochain V)
    (f : Submission.Cochain (orderedSSet facets) (ZMod 2) (n + 1))
    (b : Submission.Cochain (orderedSSet facets) (ZMod 2) n)
    (hfb : f = Submission.coboundary (orderedSSet facets) (ZMod 2) n b)
    (hagree : ∀ σ (hσ : σ ∈ facesOfCard facets (n + 2)),
      f (canonicalSimplex σ (card_eq_of_mem_facesOfCard hσ)
        (isFace_of_mem_facesOfCard hσ)) = boolEquivZModTwo (c σ)) :
    IsCoboundaryOn facets (n + 1) c := by
  refine ⟨fromSSetCochain facets n b, ?_⟩
  intro σ hσ
  apply boolEquivZModTwo.injective
  rw [← hagree σ hσ, hfb]
  exact (boolEquivZModTwo_coboundary_fromSSetCochain b σ
    (card_eq_of_mem_facesOfCard hσ) (isFace_of_mem_facesOfCard hσ)).symm

/-- On canonical simplices, the genuine simplicial Alexander--Whitney cup product agrees with
the finite executable cup product after identifying `Bool` with `ZMod 2`. -/
theorem cup_toSSetCochain_canonicalSimplex {facets : Finset (Finset V)} {p q : ℕ}
    (c d : Cochain V) (σ : Finset V) (hcard : σ.card = p + q + 1)
    (hface : IsFace facets σ) :
    Submission.cup (toSSetCochain facets p c) (toSSetCochain facets q d)
        (canonicalSimplex σ hcard hface) =
      boolEquivZModTwo (FiniteOrderedComplex.cup p c d σ) := by
  change boolEquivZModTwo
      (c (simplexVertices
        (SSet.front (orderedSSet facets) (by omega : p ≤ p + q)
          (canonicalSimplex σ hcard hface)))) *
      boolEquivZModTwo
        (d (simplexVertices
          (SSet.back (orderedSSet facets) (by omega : q ≤ p + q)
            (canonicalSimplex σ hcard hface)))) =
    boolEquivZModTwo (c (frontFace p σ) * d (backFace p σ))
  rw [simplexVertices_front_canonicalSimplex, simplexVertices_back_canonicalSimplex,
    map_mul]

/-- In degree two over `ZMod 2`, the coboundary of a normalized cochain vanishes on every
degenerate three-simplex.  The two faces which undo the degeneracy cancel, while all remaining
faces are themselves degenerate. -/
theorem coboundary_two_apply_eq_zero_of_degenerate {S : SSet.{0}}
    (f : Submission.Cochain S (ZMod 2) 2)
    (hzero : ∀ y : S _⦋2⦌, y ∈ S.degenerate 2 → f y = 0)
    (x : S _⦋3⦌) (hx : x ∈ S.degenerate 3) :
    Submission.coboundary S (ZMod 2) 2 f x = 0 := by
  rw [SSet.degenerate_eq_iUnion_range_σ] at hx
  simp only [Set.mem_iUnion, Set.mem_range] at hx
  rcases hx with ⟨i, y, rfl⟩
  have hσ (z : S _⦋1⦌) (j : Fin 2) : f (S.σ j z) = 0 :=
    hzero _ (SSet.σ_mem_degenerate S j z)
  fin_cases i
  · have h0 : S.δ (0 : Fin 4) (S.σ (0 : Fin 3) y) = y := by
      simpa using SSet.δ_comp_σ_self_apply (S := S) (0 : Fin 3) y
    have h1 : S.δ (1 : Fin 4) (S.σ (0 : Fin 3) y) = y := by
      simpa using SSet.δ_comp_σ_succ_apply (S := S) (0 : Fin 3) y
    have h2 : f (S.δ (2 : Fin 4) (S.σ (0 : Fin 3) y)) = 0 := by
      rw [SSet.δ_comp_σ_of_gt'_apply (S := S) (i := (2 : Fin 4)) (j := (0 : Fin 3))
        (by decide) y]
      apply hσ
    have h3 : f (S.δ (3 : Fin 4) (S.σ (0 : Fin 3) y)) = 0 := by
      rw [SSet.δ_comp_σ_of_gt'_apply (S := S) (i := (3 : Fin 4)) (j := (0 : Fin 3))
        (by decide) y]
      apply hσ
    change (∑ j : Fin 4, (-1 : ZMod 2) ^ (j : ℕ) *
        f (S.δ j (S.σ (0 : Fin 3) y))) = 0
    rw [Fin.sum_univ_four]
    rw [h0, h1, h2, h3]
    simpa using (CharTwo.add_self_eq_zero (f y))
  · have h0 : f (S.δ (0 : Fin 4) (S.σ (1 : Fin 3) y)) = 0 := by
      have heq : S.δ (0 : Fin 4) (S.σ (1 : Fin 3) y) =
          S.σ (0 : Fin 2) (S.δ (0 : Fin 3) y) := by
        simpa using SSet.δ_comp_σ_of_le_apply (S := S)
          (i := (0 : Fin 3)) (j := (0 : Fin 2)) (by decide) y
      rw [heq]
      apply hσ
    have h1 : S.δ (1 : Fin 4) (S.σ (1 : Fin 3) y) = y := by
      simpa using SSet.δ_comp_σ_self_apply (S := S) (1 : Fin 3) y
    have h2 : S.δ (2 : Fin 4) (S.σ (1 : Fin 3) y) = y := by
      simpa using SSet.δ_comp_σ_succ_apply (S := S) (1 : Fin 3) y
    have h3 : f (S.δ (3 : Fin 4) (S.σ (1 : Fin 3) y)) = 0 := by
      rw [SSet.δ_comp_σ_of_gt'_apply (S := S) (i := (3 : Fin 4)) (j := (1 : Fin 3))
        (by decide) y]
      apply hσ
    change (∑ j : Fin 4, (-1 : ZMod 2) ^ (j : ℕ) *
        f (S.δ j (S.σ (1 : Fin 3) y))) = 0
    rw [Fin.sum_univ_four]
    rw [h0, h1, h2, h3]
    simpa using (CharTwo.add_self_eq_zero (f y))
  · have h0 : f (S.δ (0 : Fin 4) (S.σ (2 : Fin 3) y)) = 0 := by
      have heq : S.δ (0 : Fin 4) (S.σ (2 : Fin 3) y) =
          S.σ (1 : Fin 2) (S.δ (0 : Fin 3) y) := by
        simpa using SSet.δ_comp_σ_of_le_apply (S := S)
          (i := (0 : Fin 3)) (j := (1 : Fin 2)) (by decide) y
      rw [heq]
      apply hσ
    have h1 : f (S.δ (1 : Fin 4) (S.σ (2 : Fin 3) y)) = 0 := by
      have heq : S.δ (1 : Fin 4) (S.σ (2 : Fin 3) y) =
          S.σ (1 : Fin 2) (S.δ (1 : Fin 3) y) := by
        simpa using SSet.δ_comp_σ_of_le_apply (S := S)
          (i := (1 : Fin 3)) (j := (1 : Fin 2)) (by decide) y
      rw [heq]
      apply hσ
    have h2 : S.δ (2 : Fin 4) (S.σ (2 : Fin 3) y) = y := by
      simpa using SSet.δ_comp_σ_self_apply (S := S) (2 : Fin 3) y
    have h3 : S.δ (3 : Fin 4) (S.σ (2 : Fin 3) y) = y := by
      simpa using SSet.δ_comp_σ_succ_apply (S := S) (2 : Fin 3) y
    change (∑ j : Fin 4, (-1 : ZMod 2) ^ (j : ℕ) *
        f (S.δ j (S.σ (2 : Fin 3) y))) = 0
    rw [Fin.sum_univ_four]
    rw [h0, h1, h2, h3]
    simpa using (CharTwo.add_self_eq_zero (f y))

/-- A normalized finite degree-two cocycle transports to a genuine cocycle on the ordered
simplicial set.  Nondegenerate three-simplices are handled by the finite coboundary comparison;
degenerate three-simplices vanish by the simplicial identities. -/
theorem toSSetCochain_two_isCocycle {facets : Finset (Finset V)} (c : Cochain V)
    (hcocycle : IsCocycle facets 2 c)
    (hnormalized : ∀ σ, σ.card ≠ 3 → c σ = 0) :
    Submission.coboundary (orderedSSet facets) (ZMod 2) 2
        (toSSetCochain facets 2 c) = 0 := by
  ext x
  rw [Cochain.zero_apply]
  by_cases hx : x ∈ (orderedSSet facets).nonDegenerate 3
  · have heq := canonicalSimplex_simplexVertices x hx
    rw [← heq, coboundary_toSSetCochain_canonicalSimplex]
    have hface : simplexVertices x ∈ facesOfCard facets 4 :=
      mem_facesOfCard_of_isFace (simplexVertices_isFace x)
        (simplexVertices_card_of_mem_nonDegenerate x hx)
    rw [(isCocycle_iff.mp hcocycle) _ hface]
    rfl
  · apply coboundary_two_apply_eq_zero_of_degenerate
      (toSSetCochain facets 2 c)
      (fun y hy ↦ toSSetCochain_eq_zero_of_degenerate c hnormalized y hy)
      x
    exact (SSet.mem_degenerate_iff_notMem_nonDegenerate (orderedSSet facets) x).2 hx

end FiniteOrderedComplex

end Submission
