/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.Cohomology.FiniteOrderedComplex

/-!
# Executable certificates for finite triangulated surfaces

This file adds finite graph, vertex-link, Euler-characteristic, and coherent-orientation checks to
the facet-family model in `FiniteOrderedComplex`.  The final genus predicate is deliberately a
combinatorial certificate: turning it into a homeomorphism with a topological surface requires a
separate realization and surface-classification theorem.
-/

namespace Submission

namespace FiniteOrderedComplex

variable {V : Type} [Fintype V] [DecidableEq V]

/-- The vertices occurring in a finite family of simplices. -/
def facetVertices (facets : Finset (Finset V)) : Finset V :=
  facets.biUnion fun σ ↦ σ

/-- One graph-expansion step from a set of vertices. -/
def graphReachStep (edges : Finset (Finset V)) (reached : Finset V) : Finset V :=
  reached ∪ (edges.filter fun e ↦ (e ∩ reached).Nonempty).biUnion fun e ↦ e

/-- Vertices reached from `root` after at most `steps` graph-expansion steps. -/
def graphReach (edges : Finset (Finset V)) (root : V) : ℕ → Finset V
  | 0 => {root}
  | steps + 1 => graphReachStep edges (graphReach edges root steps)

/-- Executable connectedness for the graph presented by a finite edge family. -/
def IsConnectedGraph (edges : Finset (Finset V)) : Prop :=
  (facetVertices edges).filter (fun root ↦
    graphReach edges root (facetVertices edges).card ≠ facetVertices edges) = ∅

instance (edges : Finset (Finset V)) : Decidable (IsConnectedGraph edges) := by
  unfold IsConnectedGraph
  infer_instance

/-- The link facets of a vertex in a finite facet family. -/
def vertexLinkFacets (facets : Finset (Finset V)) (v : V) : Finset (Finset V) :=
  (facets.filter fun σ ↦ v ∈ σ).image fun σ ↦ σ.erase v

/-- A finite edge family is a connected cycle graph: every edge has two vertices and every
occurring vertex has degree two. -/
def IsCycleGraph (edges : Finset (Finset V)) : Prop :=
  edges.filter (fun e ↦ e.card ≠ 2) = ∅ ∧
    IsConnectedGraph edges ∧
    (facetVertices edges).filter
      (fun v ↦ (edges.filter fun e ↦ v ∈ e).card ≠ 2) = ∅

instance (edges : Finset (Finset V)) : Decidable (IsCycleGraph edges) := by
  unfold IsCycleGraph
  infer_instance

/-- A local finite certificate for a connected closed triangulated surface.  Besides purity and
global connectedness, it checks two-triangle edge incidence and that every vertex link is a
connected cycle. -/
def IsClosedCombinatorialSurface (facets : Finset (Finset V)) : Prop :=
  facets.filter (fun σ ↦ σ.card ≠ 3) = ∅ ∧
    IsConnectedGraph (facesOfCard facets 2) ∧
    (facesOfCard facets 2).filter (fun e ↦
      (facets.filter fun σ ↦ e ∈ σ.powersetCard 2).card ≠ 2) = ∅ ∧
    (facetVertices facets).filter (fun v ↦
      ¬ IsCycleGraph (vertexLinkFacets facets v)) = ∅

instance (facets : Finset (Finset V)) : Decidable (IsClosedCombinatorialSurface facets) := by
  unfold IsClosedCombinatorialSurface
  infer_instance

/-- Euler characteristic computed directly from the vertices, edges, and triangles generated by
a finite triangle family. -/
def surfaceEulerCharacteristic (facets : Finset (Finset V)) : ℤ :=
  (facesOfCard facets 1).card - (facesOfCard facets 2).card +
    (facesOfCard facets 3).card

/-- An oriented triangle, written in its positive cyclic order. -/
structure OrientedTriangle (V : Type) where
  first : V
  second : V
  third : V
deriving DecidableEq, Repr

namespace OrientedTriangle

/-- The underlying unoriented vertex set of an oriented triangle. -/
def vertices (triangle : OrientedTriangle V) : Finset V :=
  {triangle.first, triangle.second, triangle.third}

/-- The three directed edges in the oriented boundary. -/
def boundary (triangle : OrientedTriangle V) : List (V × V) :=
  [(triangle.first, triangle.second), (triangle.second, triangle.third),
    (triangle.third, triangle.first)]

end OrientedTriangle

/-- The unoriented triangle family underlying a list of oriented triangles. -/
def orientedTriangleFacets (orientation : List (OrientedTriangle V)) :
    Finset (Finset V) :=
  orientation.toFinset.image OrientedTriangle.vertices

/-- All directed boundary edges, with multiplicity, of an oriented triangle list. -/
def orientedBoundaryEdges (orientation : List (OrientedTriangle V)) : List (V × V) :=
  orientation.flatMap OrientedTriangle.boundary

/-- Multiplicity of a directed edge in an oriented triangle list. -/
def directedEdgeMultiplicity (orientation : List (OrientedTriangle V)) (edge : V × V) : ℕ :=
  (orientedBoundaryEdges orientation).countP fun candidate ↦ decide (candidate = edge)

/-- A triangle list coherently orients a facet family when it lists every facet exactly once and
every unoriented edge occurs once in each direction among the oriented boundaries. -/
def IsCoherentOrientation [LinearOrder V] (facets : Finset (Finset V))
    (orientation : List (OrientedTriangle V)) : Prop :=
  orientation.length = facets.card ∧
    orientedTriangleFacets orientation = facets ∧
    ∀ u v, u < v → {u, v} ∈ facesOfCard facets 2 →
      directedEdgeMultiplicity orientation (u, v) = 1 ∧
        directedEdgeMultiplicity orientation (v, u) = 1

instance [LinearOrder V] (facets : Finset (Finset V))
    (orientation : List (OrientedTriangle V)) :
    Decidable (IsCoherentOrientation facets orientation) := by
  unfold IsCoherentOrientation
  infer_instance

/-- A fully executable orientable-genus certificate.  Its final equation is the usual
`χ = 2 - 2g`; interpreting this certificate as a topological genus still requires a separate
realization and classification theorem. -/
def HasCombinatorialOrientableGenus [LinearOrder V]
    (facets : Finset (Finset V)) (genus : ℕ) : Prop :=
  IsClosedCombinatorialSurface facets ∧
    ∃ orientation : List (OrientedTriangle V),
      IsCoherentOrientation facets orientation ∧
        surfaceEulerCharacteristic facets = 2 - 2 * (genus : ℤ)

/-- An executable local certificate for a finite tetrahedral complex: it is pure and connected,
every triangle has incidence two, and each vertex link has a supplied closed, coherently oriented
Euler-characteristic-two surface certificate.  Interpreting those links as topological two-spheres
still requires the separate surface-classification bridge. -/
def HasCombinatorialGenusZeroVertexLinks [LinearOrder V]
    (tetrahedra : Finset (Finset V))
    (linkOrientations : V → List (OrientedTriangle V)) : Prop :=
  tetrahedra.filter (fun σ ↦ σ.card ≠ 4) = ∅ ∧
    IsConnectedGraph (facesOfCard tetrahedra 2) ∧
    (facesOfCard tetrahedra 3).filter (fun τ ↦
      (tetrahedra.filter fun σ ↦ τ ∈ σ.powersetCard 3).card ≠ 2) = ∅ ∧
    (facetVertices tetrahedra).filter (fun v ↦
      let link := vertexLinkFacets tetrahedra v
      ¬ (IsClosedCombinatorialSurface link ∧
        IsCoherentOrientation link (linkOrientations v) ∧
        surfaceEulerCharacteristic link = 2)) = ∅

end FiniteOrderedComplex

end Submission
