/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.AlgebraicTopology.SimplicialSet.NerveNondegenerate
import Mathlib.AlgebraicTopology.SimplicialSet.Subcomplex
import Mathlib.Data.Finset.Sort
import Submission.Cohomology.Cup
import Submission.Cohomology.FiniteOrderedComplex

/-!
# A simplicial-set model of a finite ordered simplicial complex

A finite ordered simplicial complex, presented by its facets, embeds naturally in the nerve of
the linearly ordered vertex set.  Its simplices are weakly increasing strings of vertices whose
images lie in one facet.  Degenerate strings are retained, as required for a simplicial set.

This file constructs that simplicial set and compares its canonical nondegenerate simplices with
the finite-set representation used in `Submission.Cohomology.FiniteOrderedComplex`.  It is the
first comparison layer between the kernel-computable finite certificate and the general
simplicial cochain/cup-product theory.

## Main definitions

* `Submission.FiniteOrderedComplex.orderedSubcomplex`: the subcomplex of the nerve generated by
  the listed facets;
* `Submission.FiniteOrderedComplex.orderedSSet`: its underlying simplicial set;
* `Submission.FiniteOrderedComplex.simplexVertices`: the vertex image of a simplex;
* `Submission.FiniteOrderedComplex.canonicalSimplex`: the increasing simplex associated to a
  finite face;
* `Submission.FiniteOrderedComplex.toSSetCochain`: transport of a finite Boolean cochain to a
  simplicial `ZMod 2` cochain by taking vertex images.
-/

namespace Submission

open CategoryTheory Simplicial

namespace FiniteOrderedComplex

variable {V : Type} [LinearOrder V]

/-- A finite set of vertices is contained in one of the listed facets. -/
def IsFace (facets : Finset (Finset V)) (σ : Finset V) : Prop :=
  ∃ facet ∈ facets, σ ⊆ facet

/-- Every generated finite face is contained in one of the listed facets. -/
theorem isFace_of_mem_facesOfCard {facets : Finset (Finset V)} {σ : Finset V} {k : ℕ}
    (hσ : σ ∈ facesOfCard facets k) : IsFace facets σ := by
  rcases Finset.mem_biUnion.mp hσ with ⟨facet, hfacet, hσ⟩
  exact ⟨facet, hfacet, (Finset.mem_powersetCard.mp hσ).1⟩

/-- A face generated in cardinality `k` has cardinality `k`. -/
theorem card_eq_of_mem_facesOfCard {facets : Finset (Finset V)} {σ : Finset V} {k : ℕ}
    (hσ : σ ∈ facesOfCard facets k) : σ.card = k := by
  rcases Finset.mem_biUnion.mp hσ with ⟨_, _, hσ⟩
  exact (Finset.mem_powersetCard.mp hσ).2

/-- The ordered simplicial complex generated by `facets`, as a subcomplex of the nerve of `V`.
An `n`-simplex is a weakly increasing string of `n + 1` vertices contained in one facet. -/
def orderedSubcomplex (facets : Finset (Finset V)) : (CategoryTheory.nerve V).Subcomplex where
  obj _ := {x | ∃ facet ∈ facets, ∀ i, x.obj i ∈ facet}
  map _ x hx := by
    rcases hx with ⟨facet, hfacet, hx⟩
    exact ⟨facet, hfacet, fun i ↦ hx _⟩

/-- The simplicial set underlying `orderedSubcomplex`. -/
abbrev orderedSSet (facets : Finset (Finset V)) : SSet := orderedSubcomplex facets

/-- The finite image of the vertices of an ordered simplex.  Degenerate vertices are counted
only once. -/
def simplexVertices {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) : Finset V :=
  Finset.univ.image fun i : Fin (n + 1) ↦ x.1.obj i

/-- The vertex image of every simplex is a face of the finite complex. -/
theorem simplexVertices_isFace {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) : IsFace facets (simplexVertices x) := by
  rcases x.2 with ⟨facet, hfacet, hx⟩
  refine ⟨facet, hfacet, ?_⟩
  intro v hv
  rcases Finset.mem_image.mp hv with ⟨i, _, rfl⟩
  exact hx i

/-- The rank of the `i`th vertex in the increasing enumeration of a finite set is `i`. -/
theorem card_filter_lt_orderEmbOfFin {n : ℕ} (σ : Finset V) (hcard : σ.card = n + 1)
    (i : Fin (n + 1)) :
    (σ.filter fun w ↦ w < σ.orderEmbOfFin hcard i).card = i := by
  let e := σ.orderEmbOfFin hcard
  have hfilter : σ.filter (fun w ↦ w < e i) =
      (Finset.univ.filter fun j : Fin (n + 1) ↦ j < i).image e := by
    ext v
    constructor
    · intro hv
      rw [Finset.mem_filter] at hv
      have hvimage : v ∈ Finset.univ.image e := by
        rw [Finset.image_orderEmbOfFin_univ σ hcard]
        exact hv.1
      rcases Finset.mem_image.mp hvimage with ⟨j, _, rfl⟩
      exact Finset.mem_image.mpr ⟨j, by simp [e.lt_iff_lt.mp hv.2], rfl⟩
    · intro hv
      rcases Finset.mem_image.mp hv with ⟨j, hj, rfl⟩
      rw [Finset.mem_filter]
      exact ⟨Finset.orderEmbOfFin_mem σ hcard j,
        e.lt_iff_lt.mpr (by simpa using (Finset.mem_filter.mp hj).2)⟩
  rw [hfilter, Finset.card_image_of_injective _ e.injective]
  change (Finset.univ.filter fun j : Fin (n + 1) ↦ (j : ℕ) < (i : ℕ)).card = (i : ℕ)
  rw [Fin.card_filter_val_lt, Nat.min_eq_right (Nat.le_of_lt i.isLt)]

/-- The finite front face is the image of the initial segment of the increasing enumeration. -/
theorem frontFace_eq_image_orderEmbOfFin {p q : ℕ} (σ : Finset V)
    (hcard : σ.card = p + q + 1) :
    frontFace p σ = Finset.univ.image fun i : Fin (p + 1) ↦
      σ.orderEmbOfFin hcard ⟨i, by omega⟩ := by
  ext v
  constructor
  · intro hv
    rw [frontFace, Finset.mem_filter] at hv
    have hvimage : v ∈ Finset.univ.image (σ.orderEmbOfFin hcard) := by
      rw [Finset.image_orderEmbOfFin_univ σ hcard]
      exact hv.1
    rcases Finset.mem_image.mp hvimage with ⟨i, _, rfl⟩
    rw [card_filter_lt_orderEmbOfFin σ hcard] at hv
    refine Finset.mem_image.mpr ⟨⟨i, by omega⟩, Finset.mem_univ _, ?_⟩
    congr
  · intro hv
    rcases Finset.mem_image.mp hv with ⟨i, _, rfl⟩
    rw [frontFace, Finset.mem_filter, card_filter_lt_orderEmbOfFin σ hcard]
    constructor
    · exact Finset.orderEmbOfFin_mem σ hcard _
    · change (i : ℕ) ≤ p
      omega

/-- The finite back face is the image of the final segment of the increasing enumeration. -/
theorem backFace_eq_image_orderEmbOfFin {p q : ℕ} (σ : Finset V)
    (hcard : σ.card = p + q + 1) :
    backFace p σ = Finset.univ.image fun i : Fin (q + 1) ↦
      σ.orderEmbOfFin hcard ⟨p + i, by omega⟩ := by
  ext v
  constructor
  · intro hv
    rw [backFace, Finset.mem_filter] at hv
    have hvimage : v ∈ Finset.univ.image (σ.orderEmbOfFin hcard) := by
      rw [Finset.image_orderEmbOfFin_univ σ hcard]
      exact hv.1
    rcases Finset.mem_image.mp hvimage with ⟨i, _, rfl⟩
    rw [card_filter_lt_orderEmbOfFin σ hcard] at hv
    refine Finset.mem_image.mpr ⟨⟨i - p, by omega⟩, Finset.mem_univ _, ?_⟩
    congr
    change p + ((i : ℕ) - p) = (i : ℕ)
    omega
  · intro hv
    rcases Finset.mem_image.mp hv with ⟨i, _, rfl⟩
    rw [backFace, Finset.mem_filter, card_filter_lt_orderEmbOfFin σ hcard]
    constructor
    · exact Finset.orderEmbOfFin_mem σ hcard _
    · change p ≤ p + (i : ℕ)
      omega

/-- The increasing `n`-simplex whose vertex set is a face of cardinality `n + 1`. -/
def canonicalSimplex {facets : Finset (Finset V)} {n : ℕ} (σ : Finset V)
    (hcard : σ.card = n + 1) (hface : IsFace facets σ) : orderedSSet facets _⦋n⦌ := by
  refine ⟨(σ.orderEmbOfFin hcard).monotone.functor, ?_⟩
  rcases hface with ⟨facet, hfacet, hsubset⟩
  exact ⟨facet, hfacet, fun i ↦ hsubset (Finset.orderEmbOfFin_mem σ hcard i)⟩

/-- A generated face, supplied in its native finite representation, determines a canonical
simplex without any additional containment or cardinality evidence. -/
def canonicalFaceSimplex {facets : Finset (Finset V)} {n : ℕ} (σ : Finset V)
    (hσ : σ ∈ facesOfCard facets (n + 1)) : orderedSSet facets _⦋n⦌ :=
  canonicalSimplex σ (card_eq_of_mem_facesOfCard hσ) (isFace_of_mem_facesOfCard hσ)

/-- Canonical increasing simplices are nondegenerate. -/
theorem canonicalSimplex_mem_nonDegenerate {facets : Finset (Finset V)} {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    canonicalSimplex σ hcard hface ∈ (orderedSSet facets).nonDegenerate n := by
  refine (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets)
    (canonicalSimplex σ hcard hface)).2 ?_
  rw [PartialOrder.mem_nerve_nonDegenerate_iff_strictMono]
  exact (σ.orderEmbOfFin hcard).strictMono

/-- A nondegenerate `n`-simplex has exactly `n + 1` distinct vertices. -/
theorem simplexVertices_card_of_mem_nonDegenerate {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) (hx : x ∈ (orderedSSet facets).nonDegenerate n) :
    (simplexVertices x).card = n + 1 := by
  have hx' : x.1 ∈ (CategoryTheory.nerve V).nonDegenerate n :=
    (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets) x).1 hx
  have hstrict : StrictMono x.1.obj :=
    (PartialOrder.mem_nerve_nonDegenerate_iff_strictMono x.1).1 hx'
  rw [simplexVertices, Finset.card_image_of_injective _ hstrict.injective,
    Finset.card_univ, Fintype.card_fin]

/-- Re-enumerating the vertex set of a nondegenerate ordered simplex returns that simplex. -/
theorem canonicalSimplex_simplexVertices {facets : Finset (Finset V)} {n : ℕ}
    (x : orderedSSet facets _⦋n⦌) (hx : x ∈ (orderedSSet facets).nonDegenerate n) :
    canonicalSimplex (simplexVertices x)
      (simplexVertices_card_of_mem_nonDegenerate x hx) (simplexVertices_isFace x) = x := by
  have hx' : x.1 ∈ (CategoryTheory.nerve V).nonDegenerate n :=
    (SSet.Subcomplex.mem_nonDegenerate_iff (orderedSubcomplex facets) x).1 hx
  have hstrict : StrictMono x.1.obj :=
    (PartialOrder.mem_nerve_nonDegenerate_iff_strictMono x.1).1 hx'
  apply Subtype.ext
  apply CategoryTheory.nerve.ext_of_isThin
  funext i
  change (simplexVertices x).orderEmbOfFin
      (simplexVertices_card_of_mem_nonDegenerate x hx) i = x.1.obj i
  exact congrFun (Finset.orderEmbOfFin_unique
    (simplexVertices_card_of_mem_nonDegenerate x hx)
    (fun j ↦ Finset.mem_image.mpr ⟨j, Finset.mem_univ _, rfl⟩) hstrict) i |>.symm

/-- Finite faces of cardinality `n + 1` are exactly the nondegenerate `n`-simplices of the
ordered simplicial set. -/
def faceEquivNonDegenerate (facets : Finset (Finset V)) (n : ℕ) :
    {σ : Finset V // IsFace facets σ ∧ σ.card = n + 1} ≃
      (orderedSSet facets).nonDegenerate n where
  toFun σ := ⟨canonicalSimplex σ.1 σ.2.2 σ.2.1,
    canonicalSimplex_mem_nonDegenerate σ.1 σ.2.2 σ.2.1⟩
  invFun x := ⟨simplexVertices x.1, simplexVertices_isFace x.1,
    simplexVertices_card_of_mem_nonDegenerate x.1 x.2⟩
  left_inv σ := by
    apply Subtype.ext
    exact Finset.image_orderEmbOfFin_univ σ.1 σ.2.2
  right_inv x := by
    apply Subtype.ext
    exact canonicalSimplex_simplexVertices x.1 x.2

/-- The canonical increasing simplex recovers its original finite vertex set. -/
@[simp]
theorem simplexVertices_canonicalSimplex {facets : Finset (Finset V)} {n : ℕ}
    (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    simplexVertices (canonicalSimplex σ hcard hface) = σ := by
  exact Finset.image_orderEmbOfFin_univ σ hcard

/-- Taking a simplicial front face of a canonical simplex agrees with the finite front face. -/
@[simp]
theorem simplexVertices_front_canonicalSimplex {facets : Finset (Finset V)} {p q : ℕ}
    (σ : Finset V) (hcard : σ.card = p + q + 1) (hface : IsFace facets σ) :
    simplexVertices
        (SSet.front (orderedSSet facets) (by omega : p ≤ p + q)
          (canonicalSimplex σ hcard hface)) = frontFace p σ := by
  rw [frontFace_eq_image_orderEmbOfFin σ hcard]
  rfl

/-- Taking a simplicial back face of a canonical simplex agrees with the finite back face. -/
@[simp]
theorem simplexVertices_back_canonicalSimplex {facets : Finset (Finset V)} {p q : ℕ}
    (σ : Finset V) (hcard : σ.card = p + q + 1) (hface : IsFace facets σ) :
    simplexVertices
        (SSet.back (orderedSSet facets) (by omega : q ≤ p + q)
          (canonicalSimplex σ hcard hface)) = backFace p σ := by
  rw [backFace_eq_image_orderEmbOfFin σ hcard]
  change Finset.univ.image (fun i : Fin (q + 1) ↦
      σ.orderEmbOfFin hcard ⟨p + q - q + i, by omega⟩) =
    Finset.univ.image (fun i : Fin (q + 1) ↦
      σ.orderEmbOfFin hcard ⟨p + i, by omega⟩)
  apply Finset.image_congr
  intro i _
  apply congrArg (σ.orderEmbOfFin hcard)
  apply Fin.ext
  dsimp
  omega

/-- Transport a finite Boolean cochain to a simplicial `ZMod 2` cochain by evaluating it on the
vertex image of each simplex. -/
def toSSetCochain (facets : Finset (Finset V)) (n : ℕ) (c : Cochain V) :
    Submission.Cochain (orderedSSet facets) (ZMod 2) n :=
  fun x ↦ boolEquivZModTwo (c (simplexVertices x))

/-- Transported cochains have the expected value on canonical increasing simplices. -/
@[simp]
theorem toSSetCochain_canonicalSimplex {facets : Finset (Finset V)} {n : ℕ}
    (c : Cochain V) (σ : Finset V) (hcard : σ.card = n + 1) (hface : IsFace facets σ) :
    toSSetCochain facets n c (canonicalSimplex σ hcard hface) = boolEquivZModTwo (c σ) := by
  simp [toSSetCochain]

/-- On canonical simplices, the genuine simplicial Alexander--Whitney cup product agrees with
the finite executable cup product after identifying `Bool` with `ZMod 2`. -/
theorem cup_toSSetCochain_canonicalSimplex {facets : Finset (Finset V)} {p q : ℕ}
    (c d : Cochain V) (σ : Finset V) (hcard : σ.card = p + q + 1)
    (hface : IsFace facets σ) :
    Submission.cup (toSSetCochain facets p c) (toSSetCochain facets q d)
        (canonicalSimplex σ hcard hface) =
      boolEquivZModTwo (FiniteOrderedComplex.cup p c d σ) := by
  change boolEquivZModTwo
      (c (simplexVertices
        (SSet.front (orderedSSet facets) (by omega : p ≤ p + q)
          (canonicalSimplex σ hcard hface)))) *
      boolEquivZModTwo
        (d (simplexVertices
          (SSet.back (orderedSSet facets) (by omega : q ≤ p + q)
            (canonicalSimplex σ hcard hface)))) =
    boolEquivZModTwo (c (frontFace p σ) * d (backFace p σ))
  rw [simplexVertices_front_canonicalSimplex, simplexVertices_back_canonicalSimplex,
    map_mul]

end FiniteOrderedComplex

end Submission
