/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Mathlib.AlgebraicTopology.SimplicialSet.Boundary
import Submission.Cohomology.FiniteOrderedComplexBistellar
import Submission.Cohomology.FiniteOrderedComplexRealization

/-!
# Reindexing finite ordered complexes

An order embedding of vertex types maps a finite ordered complex isomorphically onto the ordered
complex generated by the mapped facets.  This file proves that statement at the simplicial-set
level and specializes it to the boundary of a simplex.

The boundary specialization identifies the finite facet presentation of a simplex boundary with
Mathlib's standard simplicial boundary `SSet.boundary`.  Applying geometric realization to these
isomorphisms is then immediate.

## Main definitions

* `Submission.FiniteOrderedComplex.orderedSSetMapFacetsIso`: reindexing along an order embedding;
* `Submission.FiniteOrderedComplex.boundaryOrderedSSetIso`: the standard finite boundary model is
  isomorphic to `SSet.boundary`;
* `Submission.FiniteOrderedComplex.boundaryMappedOrderedSSetIso`: the same identification after
  embedding the standard vertices into another ordered type.
-/

noncomputable section

namespace Submission

open CategoryTheory Simplicial

namespace FiniteOrderedComplex

variable {V W : Type} [LinearOrder V] [LinearOrder W]

/-- Map every facet along an embedding of vertex types. -/
def mapFacets (e : V ↪ W) (facets : Finset (Finset V)) : Finset (Finset W) :=
  facets.map (Finset.mapEmbedding e).toEmbedding

/-- Mapping a simplex boundary facet family maps its vertex set. -/
theorem mapFacets_simplexBoundaryFacets (e : V ↪ W) (vertices : Finset V) :
    mapFacets e (simplexBoundaryFacets vertices) =
      simplexBoundaryFacets (vertices.map e) := by
  ext facet
  simp [mapFacets, simplexBoundaryFacets, Finset.map_erase]

/-- An order embedding induces a map between the nerves of the associated thin categories. -/
def nerveOrderEmb (e : V ↪o W) : CategoryTheory.nerve V ⟶ CategoryTheory.nerve W :=
  CategoryTheory.nerveMap e.monotone.functor

instance nerveOrderEmb_mono (e : V ↪o W) : Mono (nerveOrderEmb e) := by
  rw [NatTrans.mono_iff_mono_app]
  intro Δ
  rw [mono_iff_injective]
  intro x y hxy
  apply CategoryTheory.nerve.ext_of_isThin
  funext i
  apply e.injective
  exact congrArg (fun z ↦ z.obj i) hxy

/-- The image of an ordered complex under an order embedding is exactly the complex generated by
the mapped facets. -/
theorem orderedSubcomplex_image_nerveOrderEmb (e : V ↪o W)
    (facets : Finset (Finset V)) :
    (orderedSubcomplex facets).image (nerveOrderEmb e) =
      orderedSubcomplex (mapFacets e.toEmbedding facets) := by
  ext Δ x
  constructor
  · rintro ⟨y, ⟨facet, hfacet, hy⟩, rfl⟩
    refine ⟨facet.map e.toEmbedding, ?_, ?_⟩
    · exact Finset.mem_map.mpr ⟨facet, hfacet, rfl⟩
    · intro i
      exact Finset.mem_map.mpr ⟨y.obj i, hy i, rfl⟩
  · rintro ⟨mappedFacet, hmappedFacet, hx⟩
    rcases Finset.mem_map.mp hmappedFacet with ⟨facet, hfacet, rfl⟩
    have hxRange : ∀ i, ∃ v ∈ facet, e v = x.obj i := by
      intro i
      have hxi : x.obj i ∈ facet.map e.toEmbedding := by
        simpa [Finset.mapEmbedding] using hx i
      exact Finset.mem_map.mp hxi
    let vertex : Fin (Δ.unop.len + 1) → V := fun i ↦ Classical.choose (hxRange i)
    have vertex_mem (i) : vertex i ∈ facet := (Classical.choose_spec (hxRange i)).1
    have vertex_spec (i) : e (vertex i) = x.obj i := (Classical.choose_spec (hxRange i)).2
    let y : Fin (Δ.unop.len + 1) ⥤ V :=
      { obj := vertex
        map := fun {i j} hij ↦ homOfLE (e.le_iff_le.mp (by
          rw [vertex_spec i, vertex_spec j]
          exact x.monotone (leOfHom hij))) }
    refine ⟨y, ⟨facet, hfacet, vertex_mem⟩, ?_⟩
    apply CategoryTheory.nerve.ext_of_isThin
    funext i
    exact vertex_spec i

instance orderedSubcomplex_toImage_mono (e : V ↪o W)
    (facets : Finset (Finset V)) :
    Mono ((orderedSubcomplex facets).toImage (nerveOrderEmb e)) :=
  mono_of_mono_fac ((orderedSubcomplex facets).toImage_ι (nerveOrderEmb e))

/-- Reindexing a finite ordered complex along an order embedding identifies it with the complex
generated by the mapped facets. -/
noncomputable def orderedSSetMapFacetsIso (e : V ↪o W)
    (facets : Finset (Finset V)) :
    orderedSSet facets ≅ orderedSSet (mapFacets e.toEmbedding facets) := by
  let f := (orderedSubcomplex facets).toImage (nerveOrderEmb e)
  letI : Mono f := orderedSubcomplex_toImage_mono e facets
  letI : IsIso f := isIso_of_mono_of_epi f
  exact (asIso f) ≪≫
    SSet.Subcomplex.eqToIso (orderedSubcomplex_image_nerveOrderEmb e facets)

/-- Mapping the vertices of a simplex boundary along an order embedding does not change its
simplicial-set model. -/
noncomputable def orderedSSetMapSimplexBoundaryIso (e : V ↪o W)
    (vertices : Finset V) :
    orderedSSet (simplexBoundaryFacets vertices) ≅
      orderedSSet (simplexBoundaryFacets (vertices.map e.toEmbedding)) :=
  orderedSSetMapFacetsIso e _ ≪≫
    SSet.Subcomplex.eqToIso
      (congrArg orderedSubcomplex
        (mapFacets_simplexBoundaryFacets e.toEmbedding vertices))

/-- Evaluation of the standard-simplex/finite-nerve isomorphism on vertices. -/
@[simp]
theorem finNerveIso_hom_app_apply {n d : ℕ}
    (s : (Δ[n] : SSet).obj (Opposite.op (SimplexCategory.mk d))) (i : Fin (d + 1)) :
    ((finNerveIso n).hom.app _ s).obj i = s i := rfl

/-- Evaluation of the inverse standard-simplex/finite-nerve isomorphism on vertices. -/
@[simp]
theorem finNerveIso_inv_app_apply {n d : ℕ}
    (x : (CategoryTheory.nerve (Fin (n + 1))).obj
      (Opposite.op (SimplexCategory.mk d)))
    (i : Fin (d + 1)) :
    (finNerveIso n).inv.app _ x i = x.obj i := rfl

/-- Under the standard simplex/nerve isomorphism, the boundary subcomplex is the ordered complex
generated by the codimension-one faces of the full vertex set. -/
theorem boundary_image_finNerveIso (n : ℕ) :
    (SSet.boundary n).image (finNerveIso n).hom =
      orderedSubcomplex
        (simplexBoundaryFacets (Finset.univ : Finset (Fin (n + 1)))) := by
  ext ⟨⟨d⟩⟩ x
  constructor
  · rintro ⟨s, hs, rfl⟩
    rw [SSet.mem_boundary_iff_notMem_range] at hs
    rcases hs with ⟨j, hj⟩
    refine ⟨Finset.univ.erase j, ?_, ?_⟩
    · exact Finset.mem_image.mpr ⟨j, Finset.mem_univ j, rfl⟩
    · intro i
      rw [Finset.mem_erase]
      refine ⟨?_, Finset.mem_univ _⟩
      intro heq
      change s i = j at heq
      apply hj
      exact ⟨i, heq⟩
  · rintro ⟨facet, hfacet, hx⟩
    rcases Finset.mem_image.mp hfacet with ⟨j, _, rfl⟩
    let s := (finNerveIso n).inv.app _ x
    refine ⟨s, ?_, ?_⟩
    · rw [SSet.mem_boundary_iff_notMem_range]
      refine ⟨j, ?_⟩
      rintro ⟨i, hi⟩
      change x.obj i = j at hi
      exact (Finset.mem_erase.mp (hx i)).1 hi
    · simp [s]

/-- The standard simplicial boundary and its finite ordered facet model are isomorphic simplicial
sets. -/
noncomputable def boundaryOrderedSSetIso (n : ℕ) :
    (SSet.boundary n : SSet) ≅
      orderedSSet
        (simplexBoundaryFacets (Finset.univ : Finset (Fin (n + 1)))) := by
  let f := (SSet.boundary n).toImage (finNerveIso n).hom
  letI : Mono f := mono_of_mono_fac ((SSet.boundary n).toImage_ι (finNerveIso n).hom)
  letI : IsIso f := isIso_of_mono_of_epi f
  exact (asIso f) ≪≫ SSet.Subcomplex.eqToIso (boundary_image_finNerveIso n)

/-- Any increasing embedding of the vertices of the standard simplex gives an ordered facet model
of its boundary isomorphic to the standard simplicial boundary. -/
noncomputable def boundaryMappedOrderedSSetIso {W : Type} [LinearOrder W]
    (n : ℕ) (e : Fin (n + 1) ↪o W) :
    (SSet.boundary n : SSet) ≅
      orderedSSet
        (simplexBoundaryFacets
          ((Finset.univ : Finset (Fin (n + 1))).map e.toEmbedding)) :=
  boundaryOrderedSSetIso n ≪≫
    orderedSSetMapSimplexBoundaryIso e Finset.univ

/-- A finite simplex boundary of the prescribed cardinality is the standard simplicial boundary. -/
noncomputable def simplexBoundarySSetIso (n : ℕ) (vertices : Finset V)
    (hcard : vertices.card = n + 1) :
    orderedSSet (simplexBoundaryFacets vertices) ≅ (SSet.boundary n : SSet) :=
  (boundaryMappedOrderedSSetIso n (vertices.orderEmbOfFin hcard) ≪≫
    SSet.Subcomplex.eqToIso
      (congrArg orderedSubcomplex
        (congrArg simplexBoundaryFacets
          (Finset.map_orderEmbOfFin_univ vertices hcard)))).symm

/-- A combinatorial bistellar-sphere certificate includes a valid move sequence whose endpoint is
isomorphic to the standard simplicial boundary. -/
theorem IsBistellarSphere.exists_endpointSSetIso {facets : Finset (Finset V)}
    {dimension : ℕ} (h : IsBistellarSphere facets dimension) :
    ∃ moves : List (BistellarMoveData V),
      IsValidBistellarMoveSequence facets dimension moves ∧
        Nonempty
          (orderedSSet (applyBistellarMoves facets moves) ≅
            (SSet.boundary (dimension + 1) : SSet)) := by
  rcases h with ⟨moves, vertices, hcard, hvalid, hresult⟩
  have hcard' : vertices.card = (dimension + 1) + 1 := by omega
  refine ⟨moves, hvalid, ⟨?_⟩⟩
  exact SSet.Subcomplex.eqToIso (congrArg orderedSubcomplex hresult) ≪≫
    simplexBoundarySSetIso (dimension + 1) vertices hcard'

/-- Geometric realization sends the certified endpoint comparison to an isomorphism of
topological spaces. -/
theorem IsBistellarSphere.exists_endpointRealizationIso {facets : Finset (Finset V)}
    {dimension : ℕ} (h : IsBistellarSphere facets dimension) :
    ∃ moves : List (BistellarMoveData V),
      IsValidBistellarMoveSequence facets dimension moves ∧
        Nonempty
          (SSet.toTop.obj (orderedSSet (applyBistellarMoves facets moves)) ≅
            SSet.toTop.obj (SSet.boundary (dimension + 1) : SSet)) := by
  rcases h.exists_endpointSSetIso with ⟨moves, hvalid, ⟨e⟩⟩
  exact ⟨moves, hvalid, ⟨SSet.toTop.mapIso e⟩⟩

end FiniteOrderedComplex

end Submission
