/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license.
-/
import Submission.Approximation.BasedPairwiseGeneralPosition
import Submission.SphereApproximation

/-!
# Pairwise general position for based maps into a sphere

This file upgrades boundary-preserving PL general position in a vector space to radial general
position in a sphere.  A collision after radial projection means that the two ambient vectors
lie on the same ray.  For each pair of grid simplices, the translations causing such a collision
lie in an affine subspace generated by the first simplex and the cone over the second.  These
subspaces are Haar-null in the stable range.

The cubical collar from `Submission.Approximation.BasedPairwiseGeneralPosition` introduces one
additional radial obstruction.  Adjoining the sphere basepoint to every coned simplex controls
that obstruction, and the positive-dimensional hypothesis supplies the extra dimension needed
to keep this second finite union Haar-null.  Choosing the translation in a small ball also keeps
the perturbed ambient map nonzero.  Radial projection then gives a homotopy relative to the cube
boundary.

## Main results

* `Submission.addHaar_collisionTranslations_cubeGridAffineApprox_range_gridConeSpan`
* `Submission.radialProj_basedInteriorTranslate_inter_subset_singleton`
* `Submission.spherePLApproximation_homotopic_radialBasedInteriorTranslate`
* `Submission.exists_homotopic_sphere_genLoops_range_inter_subset_singleton`
-/

open MeasureTheory Module Set
open scoped unitInterval Topology Topology.Homotopy

namespace Submission

variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F] [MeasurableSpace F]
  [BorelSpace F] [FiniteDimensional ℝ F] (μ : Measure F) [μ.IsAddHaarMeasure]

variable {n m N M : ℕ}

/-! ### The linear spans controlling the radial collar -/

/-- Add a distinguished basepoint to the points spanning one piece of `gridConeSpan`. -/
noncomputable def gridBaseConePoints (M : ℕ) (h : C(I^ Fin m, F)) (b : F)
    (T : Finset (Fin m → ℕ)) : Option (Option {v // v ∈ T}) → F
  | none => b
  | some q => gridConePoints M h T q

/-- The finite union of linear subspaces spanned by the basepoint and one coned grid simplex. -/
noncomputable def gridBaseConeSpan (m M : ℕ) (h : C(I^ Fin m, F)) (b : F) : Set F :=
  ⋃ T ∈ gridSimplices m M,
    (affineSpan ℝ (Set.range (gridBaseConePoints M h b T)) : Set F)

omit [NormedSpace ℝ F] [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem base_mem_gridBaseConePoints_range (h : C(I^ Fin m, F)) (b : F)
    (T : Finset (Fin m → ℕ)) :
    b ∈ Set.range (gridBaseConePoints M h b T) :=
  ⟨none, rfl⟩

omit [NormedSpace ℝ F] [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem zero_mem_gridBaseConePoints_range (h : C(I^ Fin m, F)) (b : F)
    (T : Finset (Fin m → ℕ)) :
    (0 : F) ∈ Set.range (gridBaseConePoints M h b T) :=
  ⟨some none, rfl⟩

omit [NormedSpace ℝ F] [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem gridConePoints_range_subset_gridBaseConePoints_range
    (h : C(I^ Fin m, F)) (b : F) (T : Finset (Fin m → ℕ)) :
    Set.range (gridConePoints M h T) ⊆ Set.range (gridBaseConePoints M h b T) := by
  rintro x ⟨q, rfl⟩
  exact ⟨some q, rfl⟩

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem gridConeSpan_subset_gridBaseConeSpan (h : C(I^ Fin m, F)) (b : F) :
    gridConeSpan m M h ⊆ gridBaseConeSpan m M h b := by
  rintro x hx
  obtain ⟨T, hT, hxT⟩ := Set.mem_iUnion₂.mp hx
  exact Set.mem_iUnion₂.mpr ⟨T, hT,
    affineSpan_mono ℝ (gridConePoints_range_subset_gridBaseConePoints_range h b T) hxT⟩

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
/-- Every scalar multiple of `x - b`, for `x` in the grid cone, lies in the base-augmented
cone. -/
theorem smul_sub_mem_gridBaseConeSpan {h : C(I^ Fin m, F)} {b x : F}
    (hx : x ∈ gridConeSpan m M h) (c : ℝ) :
    c • (x - b) ∈ gridBaseConeSpan m M h b := by
  obtain ⟨T, hT, hxT⟩ := Set.mem_iUnion₂.mp hx
  refine Set.mem_iUnion₂.mpr ⟨T, hT, ?_⟩
  let P := affineSpan ℝ (Set.range (gridBaseConePoints M h b T))
  have hxP : x ∈ P := affineSpan_mono ℝ
    (gridConePoints_range_subset_gridBaseConePoints_range h b T) hxT
  have hbP : b ∈ P := subset_affineSpan ℝ _ (base_mem_gridBaseConePoints_range h b T)
  have h0P : (0 : F) ∈ P :=
    subset_affineSpan ℝ _ (zero_mem_gridBaseConePoints_range h b T)
  simpa [P] using P.smul_vsub_vadd_mem c hxP hbP h0P

include μ in
/-- The base-augmented grid cone is Haar-null when its at most `m + 3` generators cannot span
the ambient vector space. -/
theorem addHaar_gridBaseConeSpan (hdim : m + 3 ≤ finrank ℝ F)
    (h : C(I^ Fin m, F)) (b : F) : μ (gridBaseConeSpan m M h b) = 0 := by
  have hsum : ∑ T ∈ gridSimplices m M,
      μ (affineSpan ℝ (Set.range (gridBaseConePoints M h b T)) : Set F) = 0 := by
    refine Finset.sum_eq_zero fun T hT => ?_
    refine addHaar_of_card_le μ (p := gridBaseConePoints M h b T) Set.Subset.rfl ?_
    rw [Fintype.card_option, Fintype.card_option, Fintype.card_coe]
    have := card_le_of_mem_gridSimplices hT
    omega
  exact nonpos_iff_eq_zero.mp (hsum ▸ measure_biUnion_finset_le _ _)

/-! ### Translating one PL image away from all rays through another -/

include μ in
/-- The translations making a grid approximation meet the cone over a second grid approximation
form a Haar-null set. -/
theorem addHaar_collisionTranslations_cubeGridAffineApprox_range_gridConeSpan
    (hN : 1 ≤ N) (hdim : n + m + 2 ≤ finrank ℝ F)
    (g : C(I^ Fin n, F)) (h : C(I^ Fin m, F)) :
    μ (collisionTranslations (Set.range (cubeGridAffineApprox n N g))
      (gridConeSpan m M h)) = 0 := by
  classical
  let D := (gridSimplices n N).filter Finset.Nonempty
  let E := gridSimplices m M
  let C : Finset (Fin n → ℕ) → Finset (Fin m → ℕ) → Set F := fun S T =>
    collisionTranslations (gridSimplexHull N g S)
      (affineSpan ℝ (Set.range (gridConePoints M h T)) : Set F)
  have hnull : ∀ S ∈ D, ∀ T ∈ E, μ (C S T) = 0 := by
    intro S hS T hT
    letI : Nonempty (gridSimplexValues N g S) :=
      (gridSimplexValues_nonempty g (Finset.mem_filter.mp hS).2).to_subtype
    apply addHaar_collisionTranslations_of_card_le μ
      (p := fun x : gridSimplexValues N g S => (x : F))
      (q := gridConePoints M h T)
    · simpa [Subtype.range_coe_subtype, Finset.setOf_mem] using
        (gridSimplexHull_subset_affineSpan_values (N := N) g S)
    · exact Set.Subset.rfl
    · rw [Fintype.card_coe, Fintype.card_option, Fintype.card_coe]
      have hScard := card_le_of_mem_gridSimplices (Finset.mem_filter.mp hS).1
      have hSvalues := card_gridSimplexValues_le (N := N) g S
      have hTcard := card_le_of_mem_gridSimplices hT
      omega
  have hUnionNull : μ (⋃ S ∈ D, ⋃ T ∈ E, C S T) = 0 := by
    have hInner : ∀ S ∈ D, μ (⋃ T ∈ E, C S T) = 0 := by
      intro S hS
      have hsum : ∑ T ∈ E, μ (C S T) = 0 := Finset.sum_eq_zero (hnull S hS)
      exact nonpos_iff_eq_zero.mp (hsum ▸ measure_biUnion_finset_le E (C S))
    have hsum : ∑ S ∈ D, μ (⋃ T ∈ E, C S T) = 0 := Finset.sum_eq_zero hInner
    exact nonpos_iff_eq_zero.mp
      (hsum ▸ measure_biUnion_finset_le D fun S => ⋃ T ∈ E, C S T)
  refine measure_mono_null ?_ hUnionNull
  rintro t ⟨a, ha, x, hx, hatx⟩
  have ha' := range_cubeGridAffineApprox_subset_nonempty_hulls hN g ha
  obtain ⟨S, hS, haS⟩ := Set.mem_iUnion₂.mp ha'
  obtain ⟨T, hT, hxT⟩ := Set.mem_iUnion₂.mp hx
  exact Set.mem_iUnion₂.mpr ⟨S, hS,
    Set.mem_iUnion₂.mpr ⟨T, hT, ⟨a, haS, x, hxT, hatx⟩⟩⟩

include μ in
/-- An arbitrarily small translation moves the first PL image away from every ray through the
second PL image and simultaneously avoids all radial collisions along the based collar. -/
theorem exists_translation_disjoint_range_gridConeSpan_and_notMem_gridBaseConeSpan
    (hN : 1 ≤ N) (hn : 1 ≤ n) (hdim : n + m + 2 ≤ finrank ℝ F)
    (g : C(I^ Fin n, F)) (h : C(I^ Fin m, F)) (b : F)
    {U : Set F} (hU : IsOpen U) (hUne : U.Nonempty) :
    ∃ t ∈ U,
      Disjoint ((fun x => x + t) '' Set.range (cubeGridAffineApprox n N g))
        (gridConeSpan m M h) ∧
      t ∉ gridBaseConeSpan m M h b := by
  let Z := collisionTranslations (Set.range (cubeGridAffineApprox n N g))
      (gridConeSpan m M h) ∪ gridBaseConeSpan m M h b
  have hcollision : μ (collisionTranslations (Set.range (cubeGridAffineApprox n N g))
      (gridConeSpan m M h)) = 0 :=
    addHaar_collisionTranslations_cubeGridAffineApprox_range_gridConeSpan μ hN hdim g h
  have hbase : μ (gridBaseConeSpan m M h b) = 0 :=
    addHaar_gridBaseConeSpan μ (by omega) h b
  have hZ : μ Z = 0 := measure_union_null hcollision hbase
  obtain ⟨t, htU, ht⟩ := exists_notMem_of_measure_zero μ ({()} : Finset Unit)
    (fun _ => Z) (fun _ _ => hZ) hU hUne
  have htZ : t ∉ Z := ht () (Finset.mem_singleton_self ())
  have htCollision : t ∉ collisionTranslations
      (Set.range (cubeGridAffineApprox n N g)) (gridConeSpan m M h) :=
    fun htmem => htZ (Or.inl htmem)
  exact ⟨t, htU, not_mem_collisionTranslations_iff_disjoint.mp htCollision,
    fun htmem => htZ (Or.inr htmem)⟩

/-! ### Radial separation of the boundary-preserving translation trace -/

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem mem_gridConeSpan_of_radialProj_eq_cubeGridAffineApprox
    (hM : 1 ≤ M) (h : C(I^ Fin m, F)) {x : F} (hx : x ≠ 0) (z : I^ Fin m)
    (heq : radialProj x = radialProj (cubeGridAffineApprox m M h z)) :
    x ∈ gridConeSpan m M h := by
  have hr : radialProj x ∈ gridConeSpan m M h := by
    rw [heq]
    exact radialProj_cubeGridAffineApprox_mem_gridConeSpan hM h z
  have hs := smul_mem_gridConeSpan hr ‖x‖
  rwa [smul_norm_radialProj hx] at hs

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
/-- If the translated core misses every ray through the second PL image and the translation
avoids the base-augmented cone, radial projection of the complete based translation trace can
meet the second radial image only at the basepoint. -/
theorem radialProj_basedTranslationTrace_inter_subset_singleton
    (hM : 1 ≤ M) (h : C(I^ Fin m, F)) {A : Set F} {b t : F}
    (hb : ‖b‖ = 1)
    (hne : ∀ x ∈ basedTranslationTrace A b t, x ≠ 0)
    (hcore : Disjoint ((fun x => x + t) '' A) (gridConeSpan m M h))
    (hcollar : t ∉ gridBaseConeSpan m M h b) :
    radialProj '' basedTranslationTrace A b t ∩
      Set.range (fun z => radialProj (cubeGridAffineApprox m M h z)) ⊆ {b} := by
  rintro q ⟨hqtrace, hqsecond⟩
  obtain ⟨x, hxtrace, rfl⟩ := hqtrace
  obtain ⟨z, hz⟩ := hqsecond
  have hxcone : x ∈ gridConeSpan m M h :=
    mem_gridConeSpan_of_radialProj_eq_cubeGridAffineApprox hM h (hne x hxtrace) z hz.symm
  rcases hxtrace with hxcore | hxsegment
  · exact (Set.disjoint_left.mp hcore hxcore hxcone).elim
  · by_cases hxb : x = b
    · simp [hxb, radialProj_of_norm_eq_one hb]
    · exfalso
      apply hcollar
      rw [segment_vadd_eq] at hxsegment
      obtain ⟨c, hc, hxc⟩ := hxsegment
      change b + c • t = x at hxc
      have hc0 : c ≠ 0 := by
        intro hc0
        apply hxb
        calc
          x = b + c • t := hxc.symm
          _ = b := by simp [hc0]
      have htmem := smul_sub_mem_gridBaseConeSpan (M := M) (b := b) hxcone c⁻¹
      have heq : c⁻¹ • (x - b) = t := by
        rw [← hxc]
        simp [hc0, smul_smul]
      rwa [heq] at htmem

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem radialProj_basedInteriorTranslate_inter_subset_singleton
    (hN : 1 ≤ N) (hM : 1 ≤ M)
    (g : C(I^ Fin n, F)) (h : C(I^ Fin m, F)) {b t : F}
    (hg : ∀ z ∈ Cube.boundary (Fin n), g z = b) (hb : ‖b‖ = 1)
    (hne : ∀ y, basedInteriorTranslate N g t y ≠ 0)
    (hcore : Disjoint
      ((fun x => x + t) '' Set.range (cubeGridAffineApprox n N g))
      (gridConeSpan m M h))
    (hcollar : t ∉ gridBaseConeSpan m M h b) :
    Set.range (fun y => radialProj (basedInteriorTranslate N g t y)) ∩
      Set.range (fun z => radialProj (cubeGridAffineApprox m M h z)) ⊆ {b} := by
  rintro q ⟨hqfirst, hqsecond⟩
  obtain ⟨y, hy⟩ := hqfirst
  obtain ⟨z, hz⟩ := hqsecond
  have heq : radialProj (basedInteriorTranslate N g t y) =
      radialProj (cubeGridAffineApprox m M h z) := hy.trans hz.symm
  have hxcone : basedInteriorTranslate N g t y ∈ gridConeSpan m M h :=
    mem_gridConeSpan_of_radialProj_eq_cubeGridAffineApprox hM h (hne y) z heq
  have hxtrace : basedInteriorTranslate N g t y ∈
      basedTranslationTrace (Set.range (cubeGridAffineApprox n N g)) b t :=
    range_basedInteriorTranslate_subset_trace (t := t) hN g hg (Set.mem_range_self y)
  rcases hxtrace with hxcore | hxsegment
  · exact (Set.disjoint_left.mp hcore hxcore hxcone).elim
  · by_cases hxb : basedInteriorTranslate N g t y = b
    · apply Set.mem_singleton_iff.mpr
      calc
        q = radialProj (basedInteriorTranslate N g t y) := hy.symm
        _ = b := by rw [hxb, radialProj_of_norm_eq_one hb]
    · exfalso
      apply hcollar
      rw [segment_vadd_eq] at hxsegment
      obtain ⟨c, hc, hxc⟩ := hxsegment
      change b + c • t = basedInteriorTranslate N g t y at hxc
      have hc0 : c ≠ 0 := by
        intro hc0
        apply hxb
        calc
          basedInteriorTranslate N g t y = b + c • t := hxc.symm
          _ = b := by simp [hc0]
      have htmem := smul_sub_mem_gridBaseConeSpan (M := M) (b := b) hxcone c⁻¹
      have heq' : c⁻¹ • (basedInteriorTranslate N g t y - b) = t := by
        rw [← hxc]
        simp [hc0, smul_smul]
      rwa [heq'] at htmem

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
/-- A translation of norm less than `1/2` preserves nonvanishing when the PL approximation is
within distance `1/2` of a unit-vector map.  On the collar the comparison unit vector is the
basepoint; on the core it is the original map at the retracted point. -/
theorem basedInteriorTranslate_ne_zero_of_dist_le_half
    (hN : 1 ≤ N) (g : C(I^ Fin n, F)) {b t : F}
    (hg : ∀ z ∈ Cube.boundary (Fin n), g z = b)
    (hgnorm : ∀ y, ‖g y‖ = 1)
    (hdist : ∀ y, dist (cubeGridAffineApprox n N g y) (g y) ≤ 1 / 2)
    (hb : ‖b‖ = 1) (ht : ‖t‖ < 1 / 2) :
    ∀ y, basedInteriorTranslate N g t y ≠ 0 := by
  intro y hyzero
  by_cases hw : cubeCollarWeight y = 1
  · have hclose : dist (basedInteriorTranslate N g t y)
        (g (cubeCollarRetraction y)) < 1 := by
      calc
        dist (basedInteriorTranslate N g t y) (g (cubeCollarRetraction y))
            ≤ dist (basedInteriorTranslate N g t y)
                (cubeGridAffineApprox n N g (cubeCollarRetraction y)) +
              dist (cubeGridAffineApprox n N g (cubeCollarRetraction y))
                (g (cubeCollarRetraction y)) := dist_triangle _ _ _
        _ = ‖t‖ + dist (cubeGridAffineApprox n N g (cubeCollarRetraction y))
                (g (cubeCollarRetraction y)) := by
              rw [basedInteriorTranslate_apply, hw, one_smul, dist_eq_norm]
              simp
        _ < 1 := by linarith [hdist (cubeCollarRetraction y)]
    rw [hyzero, dist_zero_left, hgnorm] at hclose
    exact (lt_irrefl 1 hclose)
  · have hboundary := cubeCollarRetraction_mem_boundary_of_weight_ne_one hw
    have hclose : dist (basedInteriorTranslate N g t y) b < 1 := by
      have hwI := cubeCollarWeight_mem_Icc y
      have hwabs : |cubeCollarWeight y| ≤ 1 := by
        rw [abs_of_nonneg hwI.1]
        exact hwI.2
      calc
        dist (basedInteriorTranslate N g t y) b = ‖cubeCollarWeight y • t‖ := by
          rw [basedInteriorTranslate_apply,
            cubeGridAffineApprox_eq_of_mem_boundary hN g hg hboundary, dist_eq_norm]
          simp
        _ = |cubeCollarWeight y| * ‖t‖ := norm_smul _ _
        _ ≤ 1 * ‖t‖ := mul_le_mul_of_nonneg_right hwabs (norm_nonneg t)
        _ < 1 := by linarith
    rw [hyzero, dist_zero_left, hb] at hclose
    exact (lt_irrefl 1 hclose)

/-! ### Sphere-valued representatives and their relative homotopies -/

/-- Straight-line interpolation from the identity of the cube to the collar retraction. -/
noncomputable def cubeCollarRetractionHomotopyPoint (p : I × I^ Fin n) : I^ Fin n :=
  fun j => Set.Icc.convexComb (p.2 j) (cubeCollarRetraction p.2 j) p.1

theorem continuous_cubeCollarRetractionHomotopyPoint :
    Continuous (cubeCollarRetractionHomotopyPoint :
      (I × I^ Fin n) → (I^ Fin n)) := by
  apply continuous_pi
  intro j
  change Continuous fun p : I × I^ Fin n =>
    Set.Icc.convexComb (p.2 j) (collarCoord (p.2 j)) p.1
  have hj : Continuous fun p : I × I^ Fin n => p.2 j :=
    (continuous_apply j).comp continuous_snd
  exact Set.Icc.continuous_convexComb_prod.comp
    (hj.prodMk ((continuous_collarCoord.comp hj).prodMk continuous_fst))

@[simp] theorem cubeCollarRetractionHomotopyPoint_zero (y : I^ Fin n) :
    cubeCollarRetractionHomotopyPoint (0, y) = y := by
  funext j
  simp [cubeCollarRetractionHomotopyPoint]

@[simp] theorem cubeCollarRetractionHomotopyPoint_one (y : I^ Fin n) :
    cubeCollarRetractionHomotopyPoint (1, y) = cubeCollarRetraction y := by
  funext j
  simp [cubeCollarRetractionHomotopyPoint, cubeCollarRetraction]

theorem cubeCollarRetractionHomotopyPoint_mem_boundary (s : I) {y : I^ Fin n}
    (hy : y ∈ Cube.boundary (Fin n)) :
    cubeCollarRetractionHomotopyPoint (s, y) ∈ Cube.boundary (Fin n) := by
  obtain ⟨j, hj⟩ := hy
  refine ⟨j, ?_⟩
  rcases hj with hj | hj
  · left
    change Set.Icc.convexComb (y j) (collarCoord (y j)) s = 0
    rw [hj, collarCoord_zero, Set.Icc.convexComb_eq]
  · right
    change Set.Icc.convexComb (y j) (collarCoord (y j)) s = 1
    rw [hj, collarCoord_one, Set.Icc.convexComb_eq]

/-- The ambient homotopy from a grid approximation to its boundary-preserving interior
translation.  The cube retraction and the tapered translation are switched on together. -/
noncomputable def basedInteriorTranslateRadialHomotopyAmbient
    (N : ℕ) (g : C(I^ Fin n, F)) (t : F) : C(I × I^ Fin n, F) where
  toFun p := cubeGridAffineApprox n N g (cubeCollarRetractionHomotopyPoint p) +
    ((p.1 : ℝ) * cubeCollarWeight p.2) • t
  continuous_toFun :=
    ((cubeGridAffineApprox n N g).continuous.comp
      continuous_cubeCollarRetractionHomotopyPoint).add
      (((continuous_subtype_val.comp continuous_fst).mul
        (continuous_cubeCollarWeight.comp continuous_snd)).smul continuous_const)

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
@[simp] theorem basedInteriorTranslateRadialHomotopyAmbient_zero
    (g : C(I^ Fin n, F)) (t : F) (y : I^ Fin n) :
    basedInteriorTranslateRadialHomotopyAmbient N g t (0, y) =
      cubeGridAffineApprox n N g y := by
  simp [basedInteriorTranslateRadialHomotopyAmbient]

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
@[simp] theorem basedInteriorTranslateRadialHomotopyAmbient_one
    (g : C(I^ Fin n, F)) (t : F) (y : I^ Fin n) :
    basedInteriorTranslateRadialHomotopyAmbient N g t (1, y) =
      basedInteriorTranslate N g t y := by
  simp [basedInteriorTranslateRadialHomotopyAmbient, basedInteriorTranslate_apply]

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem basedInteriorTranslateRadialHomotopyAmbient_eq_of_mem_boundary
    (hN : 1 ≤ N) (g : C(I^ Fin n, F)) {b t : F}
    (hg : ∀ z ∈ Cube.boundary (Fin n), g z = b)
    (s : I) {y : I^ Fin n} (hy : y ∈ Cube.boundary (Fin n)) :
    basedInteriorTranslateRadialHomotopyAmbient N g t (s, y) = b := by
  change cubeGridAffineApprox n N g (cubeCollarRetractionHomotopyPoint (s, y)) +
    ((s : ℝ) * cubeCollarWeight y) • t = b
  rw [cubeGridAffineApprox_eq_of_mem_boundary hN g hg
      (cubeCollarRetractionHomotopyPoint_mem_boundary s hy),
    cubeCollarWeight_eq_zero_of_mem_boundary hy]
  simp

omit [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F] in
theorem basedInteriorTranslateRadialHomotopyAmbient_ne_zero_of_dist_le_half
    (g : C(I^ Fin n, F))
    (hgnorm : ∀ y, ‖g y‖ = 1)
    (hdist : ∀ y, dist (cubeGridAffineApprox n N g y) (g y) ≤ 1 / 2)
    {t : F} (ht : ‖t‖ < 1 / 2) :
    ∀ p, basedInteriorTranslateRadialHomotopyAmbient N g t p ≠ 0 := by
  rintro ⟨s, y⟩ hzero
  let z := cubeCollarRetractionHomotopyPoint (s, y)
  have hwI := cubeCollarWeight_mem_Icc y
  have hsI : (s : ℝ) ∈ Set.Icc 0 1 := s.2
  have hcoef_nonneg : 0 ≤ (s : ℝ) * cubeCollarWeight y :=
    mul_nonneg hsI.1 hwI.1
  have hcoef_le : (s : ℝ) * cubeCollarWeight y ≤ 1 := by
    calc
      (s : ℝ) * cubeCollarWeight y ≤ 1 * cubeCollarWeight y :=
        mul_le_mul_of_nonneg_right hsI.2 hwI.1
      _ ≤ 1 := by simpa using hwI.2
  have hclose : dist (basedInteriorTranslateRadialHomotopyAmbient N g t (s, y))
      (g z) < 1 := by
    calc
      dist (basedInteriorTranslateRadialHomotopyAmbient N g t (s, y)) (g z)
          ≤ dist (basedInteriorTranslateRadialHomotopyAmbient N g t (s, y))
              (cubeGridAffineApprox n N g z) +
            dist (cubeGridAffineApprox n N g z) (g z) := dist_triangle _ _ _
      _ = ‖((s : ℝ) * cubeCollarWeight y) • t‖ +
            dist (cubeGridAffineApprox n N g z) (g z) := by
          rw [basedInteriorTranslateRadialHomotopyAmbient, dist_eq_norm]
          simp [z]
      _ ≤ ‖t‖ + dist (cubeGridAffineApprox n N g z) (g z) := by
          gcongr
          rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg hcoef_nonneg]
          exact mul_le_of_le_one_left (norm_nonneg t) hcoef_le
      _ < 1 := by linarith [hdist z]
  rw [hzero, dist_zero_left, hgnorm] at hclose
  exact (lt_irrefl 1 hclose)

section SphereRepresentatives

variable {d : ℕ} {x : Sph d}

/-- Radial projection of a boundary-preserving interior translation, bundled as a based map to
the sphere. -/
noncomputable def radialBasedInteriorTranslateGenLoop
    (N : ℕ) (hN : 1 ≤ N) (f : Ω^ (Fin n) (Sph d) x)
    (t : EuclideanSpace ℝ (Fin (d + 1)))
    (hne : ∀ y, basedInteriorTranslate N (genLoopToEuclidean f) t y ≠ 0) :
    Ω^ (Fin n) (Sph d) x :=
  ⟨⟨fun y =>
      ⟨radialProj (basedInteriorTranslate N (genLoopToEuclidean f) t y),
        mem_sphere_zero_iff_norm.mpr (norm_radialProj (hne y))⟩,
    Continuous.subtype_mk
      (continuous_radialProj
        (basedInteriorTranslate N (genLoopToEuclidean f) t).continuous hne) _⟩,
    fun y hy => Subtype.ext (by
      change radialProj (basedInteriorTranslate N (genLoopToEuclidean f) t y) =
        ((x : Sph d) : EuclideanSpace ℝ (Fin (d + 1)))
      rw [basedInteriorTranslate_eq_of_mem_boundary hN (genLoopToEuclidean f)
        (fun z hz => congrArg Subtype.val (_root_.GenLoop.boundary f z hz)) hy]
      exact radialProj_of_norm_eq_one (norm_coe_sph x))⟩

@[simp] theorem coe_radialBasedInteriorTranslateGenLoop
    (N : ℕ) (hN : 1 ≤ N) (f : Ω^ (Fin n) (Sph d) x)
    (t : EuclideanSpace ℝ (Fin (d + 1)))
    (hne : ∀ y, basedInteriorTranslate N (genLoopToEuclidean f) t y ≠ 0)
    (y : I^ Fin n) :
    (((radialBasedInteriorTranslateGenLoop N hN f t hne) y : Sph d) :
      EuclideanSpace ℝ (Fin (d + 1))) =
      radialProj (basedInteriorTranslate N (genLoopToEuclidean f) t y) :=
  rfl

/-- The radial boundary-preserving perturbation associated to a sphere PL approximation remains
in the original based homotopy class. -/
theorem spherePLApproximation_homotopic_radialBasedInteriorTranslate
    (f : Ω^ (Fin n) (Sph d) x) (A : SpherePLApproximation f)
    {t : EuclideanSpace ℝ (Fin (d + 1))} (ht : ‖t‖ < 1 / 2) :
    let hne : ∀ y,
        basedInteriorTranslate A.mesh (genLoopToEuclidean f) t y ≠ 0 :=
      basedInteriorTranslate_ne_zero_of_dist_le_half A.mesh_pos
        (genLoopToEuclidean f)
        (fun z hz => congrArg Subtype.val (_root_.GenLoop.boundary f z hz))
        (fun y => norm_coe_sph (f y)) A.dist_le_half (norm_coe_sph x) ht
    _root_.GenLoop.Homotopic f
      (radialBasedInteriorTranslateGenLoop A.mesh A.mesh_pos f t hne) := by
  dsimp only
  let hne : ∀ y, basedInteriorTranslate A.mesh (genLoopToEuclidean f) t y ≠ 0 :=
    basedInteriorTranslate_ne_zero_of_dist_le_half A.mesh_pos
      (genLoopToEuclidean f)
      (fun z hz => congrArg Subtype.val (_root_.GenLoop.boundary f z hz))
      (fun y => norm_coe_sph (f y)) A.dist_le_half (norm_coe_sph x) ht
  let f' := radialBasedInteriorTranslateGenLoop A.mesh A.mesh_pos f t hne
  have hHne : ∀ p,
      basedInteriorTranslateRadialHomotopyAmbient A.mesh (genLoopToEuclidean f) t p ≠ 0 :=
    basedInteriorTranslateRadialHomotopyAmbient_ne_zero_of_dist_le_half
      (genLoopToEuclidean f) (fun y => norm_coe_sph (f y)) A.dist_le_half ht
  have hstep : _root_.GenLoop.Homotopic A.approx f' := by
    apply genLoopHomotopic_of_radialHomotopy A.approx f'
      (basedInteriorTranslateRadialHomotopyAmbient A.mesh (genLoopToEuclidean f) t) hHne
    · intro y
      rw [basedInteriorTranslateRadialHomotopyAmbient_zero]
      exact (A.coe_approx y).symm
    · intro y
      rw [basedInteriorTranslateRadialHomotopyAmbient_one]
      exact (coe_radialBasedInteriorTranslateGenLoop A.mesh A.mesh_pos f t hne y).symm
    · intro s y hy
      rw [basedInteriorTranslateRadialHomotopyAmbient_eq_of_mem_boundary A.mesh_pos
        (genLoopToEuclidean f)
        (fun z hz => congrArg Subtype.val (_root_.GenLoop.boundary f z hz)) s hy,
        radialProj_of_norm_eq_one (norm_coe_sph x)]
  exact A.homotopic.trans hstep

end SphereRepresentatives

section SphereGeneralPosition

variable {d : ℕ} {x : Sph d}

/-- **Based pairwise general position in a sphere.**  If two positive-dimensional based cube
maps have dimensions whose sum is strictly smaller than the sphere dimension, they have based-
homotopic representatives whose images meet only at the basepoint. -/
theorem exists_homotopic_sphere_genLoops_range_inter_subset_singleton
    (hn : 1 ≤ n) (hdim : n + m + 1 ≤ d)
    (f : Ω^ (Fin n) (Sph d) x) (g : Ω^ (Fin m) (Sph d) x) :
    ∃ (f' : Ω^ (Fin n) (Sph d) x) (g' : Ω^ (Fin m) (Sph d) x),
      _root_.GenLoop.Homotopic f f' ∧ _root_.GenLoop.Homotopic g g' ∧
      Set.range f' ∩ Set.range g' ⊆ {x} := by
  obtain ⟨A⟩ := exists_spherePLApproximation f
  obtain ⟨B⟩ := exists_spherePLApproximation g
  let E := EuclideanSpace ℝ (Fin (d + 1))
  have hdimE : n + m + 2 ≤ finrank ℝ E := by
    rw [finrank_euclideanSpace_fin]
    omega
  obtain ⟨t, htball, hcore, hcollar⟩ :=
    exists_translation_disjoint_range_gridConeSpan_and_notMem_gridBaseConeSpan
      (volume : Measure E) A.mesh_pos hn hdimE
      (genLoopToEuclidean f) (genLoopToEuclidean g)
      ((x : Sph d) : E) Metric.isOpen_ball
      ⟨0, Metric.mem_ball_self (by norm_num : (0 : ℝ) < 1 / 2)⟩
  have ht : ‖t‖ < 1 / 2 := by
    simpa [Metric.mem_ball, dist_eq_norm] using htball
  let hne : ∀ y,
      basedInteriorTranslate A.mesh (genLoopToEuclidean f) t y ≠ 0 :=
    basedInteriorTranslate_ne_zero_of_dist_le_half A.mesh_pos
      (genLoopToEuclidean f)
      (fun z hz => congrArg Subtype.val (_root_.GenLoop.boundary f z hz))
      (fun y => norm_coe_sph (f y)) A.dist_le_half (norm_coe_sph x) ht
  let f' := radialBasedInteriorTranslateGenLoop A.mesh A.mesh_pos f t hne
  refine ⟨f', B.approx, ?_, B.homotopic, ?_⟩
  · dsimp [f']
    exact spherePLApproximation_homotopic_radialBasedInteriorTranslate f A ht
  · have hinter := radialProj_basedInteriorTranslate_inter_subset_singleton
      A.mesh_pos B.mesh_pos (genLoopToEuclidean f) (genLoopToEuclidean g)
      (fun z hz => congrArg Subtype.val (_root_.GenLoop.boundary f z hz))
      (norm_coe_sph x) hne hcore hcollar
    rintro q ⟨hqf, hqg⟩
    obtain ⟨y, hy⟩ := hqf
    obtain ⟨z, hz⟩ := hqg
    apply Set.mem_singleton_iff.mpr
    apply Subtype.ext
    apply Set.mem_singleton_iff.mp
    apply hinter
    constructor
    · refine ⟨y, ?_⟩
      change radialProj (basedInteriorTranslate A.mesh (genLoopToEuclidean f) t y) =
        ((q : Sph d) : E)
      rw [← hy]
      rfl
    · refine ⟨z, ?_⟩
      change radialProj (cubeGridAffineApprox m B.mesh (genLoopToEuclidean g) z) =
        ((q : Sph d) : E)
      rw [← hz]
      exact (B.coe_approx z).symm

end SphereGeneralPosition

end Submission
